/**
 * Vorlage: Lysandre Abendlied – Barde, Halbelf.
 *
 * Einer der zwölf fertigen Charaktere, die jede neue Kampagne hinter dem
 * Schirm vorfindet (siehe ../helden.js für die Auswahl und ../index.js fürs
 * Säen). Hier steht nur der Steckbrief – was diesen Charakter ausmacht.
 * Zum vollständigen Blatt mit allen achtzehn Fertigkeiten und leeren
 * Feldern macht ihn erst ../bauen.js.
 */
export default {
  schluessel: 'barde-halbelf',
  name: 'Lysandre Abendlied',
  spezies: 'Halbelf',
  unterart: '',
  klasse: 'Barde',
  hintergrund: 'Gaukler',
  gesinnung: 'Chaotisch Gut',
  werte: { str: 8, dex: 14, con: 14, int: 10, wis: 12, cha: 17 },
  rettungswuerfe: ['dex', 'cha'],
  fertigkeiten: ['acrobatics', 'performance', 'persuasion', 'deception', 'insight'],
  expertise: ['performance', 'persuasion'],
  ruestungsklasse: 13,
  initiativeBonus: 0,
  trefferpunkte: 10,
  trefferwuerfel: '1d8',
  bewegung: 30,
  sinne: { darkvision: 60 },
  verteidigung: {},
  rettungswurfVermerk: 'Vorteil auf Rettungswürfe gegen Bezauberung (Feenblut).',
  uebungen: {
    armor: 'Leichte Rüstung',
    weapons: 'Einfache Waffen',
    tools: 'Laute, Blockflöte, Trommel',
    languages: 'Gemeinsprache, Elfisch, Zwergisch',
  },
  angriffe: [
    { name: 'Dolch', bonus: '+4', damage: '1W4+2 Stich', notes: 'Finesse, Leicht, Wurf 6/18 m' },
    { name: 'Bösartiger Spott', bonus: 'SG 13', damage: '1W6 psychisch', notes: 'Weisheit-RW; bei Misslingen Nachteil auf den nächsten Angriff' },
  ],
  aktionen: [
    {
      name: 'Bardische Inspiration',
      art: 'bonus',
      description:
        'Ein Verbündeter in 18 m, der dich hört, erhält einen W6. Er darf ihn binnen 10 Minuten auf einen Wurf addieren – auch nachdem er gewürfelt hat. Dreimal je Lange Rast.',
    },
  ],
  ressourcen: [{ name: 'Bardische Inspiration (W6)', current: 3, max: 3, recharge: 'lang' }],
  merkmale: [
    {
      name: 'Bardische Inspiration',
      category: 'klasse',
      source: 'PHB-2024',
      page: '52',
      description:
        'Als Bonusaktion einem Verbündeten einen W6 geben, den er auf eine Probe, einen Angriff oder einen Rettungswurf addieren darf. Charisma-Modifikator-mal je Lange Rast.',
    },
    {
      name: 'Zauberwirken',
      category: 'klasse',
      source: 'PHB-2024',
      page: '52',
      description: 'Charisma ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5.',
    },
    {
      name: 'Dunkelsicht',
      category: 'spezies',
      source: 'PHB',
      page: '',
      description: '18 m weit – das Erbe der elfischen Seite.',
    },
    {
      name: 'Feenblut',
      category: 'spezies',
      source: 'PHB',
      page: '',
      description: 'Vorteil auf Rettungswürfe gegen Bezauberung, und Magie kann dich nicht schlafen legen.',
    },
    {
      name: 'Vielseitige Begabung',
      category: 'spezies',
      source: 'PHB',
      page: '',
      description: 'Du erhältst Übung in zwei Fertigkeiten deiner Wahl – hier Überzeugen und Motiv erkennen.',
    },
    {
      name: 'Musiker',
      category: 'talent',
      source: 'PHB-2024',
      page: '203',
      description:
        'Nach einer Rast kannst du Übungsbonus-vielen Verbündeten, die zuhören, Heldenhafte Inspiration schenken.',
    },
  ],
  zauber: {
    attribut: 'cha',
    plaetze: { 1: { max: 2, used: 0 } },
    liste: [
      {
        name: 'Bösartiger Spott',
        level: 0,
        prepared: true,
        index: 'vicious-mockery',
        source: 'Barde',
        save: 'WEI-RW',
        time: '1 A',
        range: '18 m',
        components: 'V',
        duration: 'Sofort',
        page: 'PHB-2024 312',
        notes: 'Bei Misslingen 1W6 psychisch und Nachteil auf den nächsten Angriffswurf.',
      },
      {
        name: 'Blendwerk',
        level: 0,
        prepared: true,
        index: 'prestidigitation',
        source: 'Barde',
        save: '--',
        time: '1 A',
        range: '3 m',
        components: 'V, S',
        duration: 'bis 1 Std.',
        page: 'PHB-2024 289',
        notes: 'Das Werkzeug für alles, was kein Kampf ist.',
      },
      {
        name: 'Heilendes Wort',
        level: 1,
        prepared: true,
        index: 'healing-word',
        source: 'Barde',
        save: '--',
        time: '1 BA',
        range: '18 m',
        components: 'V',
        duration: 'Sofort',
        page: 'PHB-2024 268',
        notes: 'Bonusaktion – hebt einen Gefallenen aus 18 m wieder auf die Beine.',
      },
      {
        name: 'Feenfeuer',
        level: 1,
        prepared: true,
        index: 'faerie-fire',
        source: 'Barde',
        save: 'GES-RW',
        time: '1 A',
        range: '18 m',
        components: 'V',
        duration: 'K, 1 Min.',
        page: 'PHB-2024 261',
        notes: 'Würfel 6 m: Angriffe gegen Umrissene haben Vorteil. Der beste erste Zug der Gruppe.',
      },
      {
        name: 'Dissonantes Flüstern',
        level: 1,
        prepared: true,
        index: 'dissonant-whispers',
        source: 'Barde',
        save: 'WEI-RW',
        time: '1 A',
        range: '18 m',
        components: 'V',
        duration: 'Sofort',
        page: 'PHB-2024 259',
        notes: '3W6 psychisch; bei Misslingen flieht das Ziel und löst Gelegenheitsangriffe aus.',
      },
      {
        name: 'Person bezaubern',
        level: 1,
        prepared: true,
        index: 'charm-person',
        source: 'Barde',
        save: 'WEI-RW',
        time: '1 A',
        range: '9 m',
        components: 'V, S',
        duration: '1 Std.',
        page: 'PHB-2024 249',
        notes: 'Außerhalb des Kampfes. Das Ziel weiß hinterher, dass es bezaubert war.',
      },
    ],
  },
  ausruestung: [
    { name: 'Lederrüstung', qty: 1, weight: 10, notes: 'RK 11 + Geschicklichkeit' },
    { name: 'Dolch', qty: 2, weight: 1, notes: '' },
    { name: 'Laute', qty: 1, weight: 2, notes: 'Zauberfokus' },
    { name: 'Kostüm', qty: 2, weight: 4, notes: '' },
    { name: 'Spiegel', qty: 1, weight: 0.5, notes: '' },
    { name: 'Parfüm', qty: 1, weight: 0, notes: '' },
    { name: 'Reisekleidung', qty: 1, weight: 4, notes: '' },
    {
      name: 'Gauklerpaket',
      qty: 1,
      weight: 38,
      notes: 'Rucksack, Schlafrolle, Kostüme ×2, Kerzen ×5, Rationen ×5, Wasserschlauch, Verkleidungsset',
    },
  ],
  muenzen: { gp: 30 },
  aussehen: {
    gender: 'weiblich',
    age: '34',
    size: 'Mittelgroß',
    height: '174 cm',
    weight: '61 kg',
    faith: 'keiner, aber allen freundlich',
    skin: 'hell mit Sommersprossen',
    eyes: 'haselnussbraun, das linke heller',
    hair: 'dunkelblond, kurz geschnitten',
  },
  wesen: {
    personality: 'Ich merke mir jeden Namen beim ersten Hören. Das kostet nichts und öffnet alles.',
    ideals: 'Freiheit. Ein Lied gehört niemandem, und ein Mensch auch nicht.',
    bonds: 'Die Truppe, die mich aufnahm, als beide Elternhäuser mich nicht wollten. Sie ist auseinander – ich suche sie.',
    flaws: 'Ich verspreche im Rausch des Auftritts Dinge, an die ich mich am Morgen nur ungefähr erinnere.',
    backstory:
      'Zu elfisch für das Dorf, zu menschlich für den Hain – Lysandre hörte das, bevor sie lesen konnte. Mit vierzehn hängte sie sich an eine fahrende Truppe, die keine Fragen stellte, und lernte dort, dass ein Publikum nicht wissen will, woher jemand kommt, sondern nur, ob er es kann. Als die Truppe nach einem schlechten Winter auseinanderfiel, blieb ihr die Laute und die Liste der Orte, an denen die anderen zuletzt gesehen wurden.',
    look: 'Auffällig gekleidet, aber immer beweglich. Spricht mit den Händen und hört mit dem ganzen Gesicht zu.',
    allies: 'Die fahrende Truppe „Sieben Fenster“ – zerstreut über vier Städte.',
  },
};
