/**
 * Vorlage: Fibbel Wurzelbart – Druide, Gnom.
 *
 * Einer der zwölf fertigen Charaktere, die jede neue Kampagne hinter dem
 * Schirm vorfindet (siehe ../helden.js für die Auswahl und ../index.js fürs
 * Säen). Hier steht nur der Steckbrief – was diesen Charakter ausmacht.
 * Zum vollständigen Blatt mit allen achtzehn Fertigkeiten und leeren
 * Feldern macht ihn erst ../bauen.js.
 */
export default {
  schluessel: 'druide-gnom',
  name: 'Fibbel Wurzelbart',
  spezies: 'Gnom',
  unterart: 'Waldgnom',
  klasse: 'Druide',
  hintergrund: 'Einsiedler',
  gesinnung: 'Neutral Gut',
  werte: { str: 8, dex: 13, con: 15, int: 12, wis: 17, cha: 10 },
  rettungswuerfe: ['int', 'wis'],
  fertigkeiten: ['medicine', 'religion', 'nature', 'perception'],
  ruestungsklasse: 14,
  initiativeBonus: 0,
  trefferpunkte: 10,
  trefferwuerfel: '1d8',
  bewegung: 30,
  sinne: { darkvision: 60 },
  verteidigung: {},
  rettungswurfVermerk: 'Vorteil auf Rettungswürfe gegen Magie bei Intelligenz, Weisheit und Charisma (Gnomenschläue).',
  uebungen: {
    armor: 'Leichte und mittlere Rüstung, Schilde (nichts aus Metall)',
    weapons: 'Einfache Waffen',
    tools: 'Kräuterkundeausrüstung',
    languages: 'Gemeinsprache, Gnomisch, Druidisch',
  },
  angriffe: [
    { name: 'Sichel', bonus: '+1', damage: '1W4-1 Hieb', notes: 'Leicht – im Ernstfall lieber zaubern' },
    { name: 'Flamme erzeugen', bonus: '+5', damage: '1W8 Feuer', notes: 'Fernkampf 9 m, Licht in der Hand' },
  ],
  aktionen: [
    {
      name: 'Verstricken (Konzentration)',
      art: 'aktion',
      description: '6-m-Quadrat wird schwieriges Gelände; wer den Stärke-RW nicht schafft, ist festgesetzt.',
    },
    {
      name: 'Donnerwoge',
      art: 'aktion',
      description: '4,5-m-Würfel: 2W8 Donner und 3 m weggestoßen. Der Notausgang, wenn zu viele zu nah stehen.',
    },
  ],
  ressourcen: [{ name: 'Druidenkunde: Wetterfühlig', current: 1, max: 1, recharge: 'lang' }],
  merkmale: [
    {
      name: 'Zauberwirken',
      category: 'klasse',
      source: 'PHB-2024',
      page: '82',
      description: 'Weisheit ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5. Du bereitest vier Zauber vor.',
    },
    {
      name: 'Druidisch',
      category: 'klasse',
      source: 'PHB-2024',
      page: '82',
      description: 'Die Geheimsprache der Druiden. Du hinterlässt damit Zeichen, die nur Eingeweihte lesen.',
    },
    {
      name: 'Grundausbildung: Druidenkunde',
      category: 'klasse',
      source: 'PHB-2024',
      page: '82',
      description: 'Der Zaubertrick Druidenkunde ist immer vorbereitet.',
    },
    { name: 'Dunkelsicht', category: 'spezies', source: 'PHB-2024', page: '191', description: '18 m weit.' },
    {
      name: 'Gnomenschläue',
      category: 'spezies',
      source: 'PHB-2024',
      page: '191',
      description: 'Vorteil auf Intelligenz-, Weisheits- und Charisma-Rettungswürfe.',
    },
    {
      name: 'Gnomenabstammung: Waldgnom',
      category: 'spezies',
      source: 'PHB-2024',
      page: '191',
      description: 'Du kennst den Zaubertrick Kleine Illusion und kannst mit kleinen Tieren sprechen.',
    },
    {
      name: 'Heiler',
      category: 'talent',
      source: 'PHB-2024',
      page: '202',
      description:
        'Mit einer Heilerausrüstung als Bonusaktion 1W6 + 4 Trefferpunkte heilen. Außerdem würfelst du eine 1 bei Heilwürfeln neu.',
    },
  ],
  zauber: {
    attribut: 'wis',
    plaetze: { 1: { max: 2, used: 0 } },
    liste: [
      {
        name: 'Druidenkunst',
        level: 0,
        prepared: true,
        index: 'druidcraft',
        source: 'Druide',
        save: '--',
        time: '1 A',
        range: '9 m',
        components: 'V, S',
        duration: 'Sofort',
        page: 'PHB-2024 260',
        notes: 'Wetter voraussagen, eine Blüte öffnen, ein Feuer löschen.',
      },
      {
        name: 'Flamme erzeugen',
        level: 0,
        prepared: true,
        index: 'produce-flame',
        source: 'Druide',
        save: '--',
        time: '1 A',
        range: 'Selbst / 9 m',
        components: 'V, S',
        duration: '10 Min.',
        page: 'PHB-2024 289',
        notes: 'Licht und Angriff in einem – die Flamme bleibt, bis du sie wirfst.',
      },
      {
        name: 'Kleine Illusion',
        level: 0,
        prepared: true,
        index: 'minor-illusion',
        source: 'Waldgnom',
        save: '--',
        time: '1 A',
        range: '9 m',
        components: 'S, M',
        duration: '1 Min.',
        page: 'PHB-2024 280',
        notes: '',
      },
      {
        name: 'Verstricken',
        level: 1,
        prepared: true,
        index: 'entangle',
        source: 'Druide',
        save: 'STÄ-RW',
        time: '1 A',
        range: '27 m',
        components: 'V, S',
        duration: 'K, 1 Min.',
        page: 'PHB-2024 261',
        notes: 'Hält eine ganze Reihe von Gegnern auf, ohne dass jemand Schaden nimmt.',
      },
      {
        name: 'Feenfeuer',
        level: 1,
        prepared: true,
        index: 'faerie-fire',
        source: 'Druide',
        save: 'GES-RW',
        time: '1 A',
        range: '18 m',
        components: 'V',
        duration: 'K, 1 Min.',
        page: 'PHB-2024 261',
        notes: 'Vorteil für alle Angriffe der Gruppe gegen die Umrissenen.',
      },
      {
        name: 'Heilendes Wort',
        level: 1,
        prepared: true,
        index: 'healing-word',
        source: 'Druide',
        save: '--',
        time: '1 BA',
        range: '18 m',
        components: 'V',
        duration: 'Sofort',
        page: 'PHB-2024 268',
        notes: '',
      },
      {
        name: 'Donnerwoge',
        level: 1,
        prepared: true,
        index: 'thunderwave',
        source: 'Druide',
        save: 'KON-RW',
        time: '1 A',
        range: 'Selbst (4,5-m-Würfel)',
        components: 'V, S',
        duration: 'Sofort',
        page: 'PHB-2024 303',
        notes: '2W8 Donner und 3 m Stoß – schafft Luft.',
      },
    ],
  },
  ausruestung: [
    { name: 'Lederrüstung', qty: 1, weight: 10, notes: 'RK 11 + Geschicklichkeit' },
    { name: 'Holzschild', qty: 1, weight: 6, notes: '+2 RK, kein Metall' },
    { name: 'Sichel', qty: 1, weight: 2, notes: '' },
    { name: 'Kampfstab', qty: 1, weight: 4, notes: 'Druidenfokus' },
    { name: 'Kräuterkundeausrüstung', qty: 1, weight: 3, notes: '' },
    { name: 'Heilerausrüstung', qty: 1, weight: 3, notes: 'für das Talent Heiler' },
    { name: 'Schlafrolle', qty: 1, weight: 7, notes: '' },
    { name: 'Buch über Pilze', qty: 1, weight: 5, notes: 'eigenhändig geschrieben' },
    { name: 'Lampe', qty: 1, weight: 1, notes: '' },
    { name: 'Öl', qty: 3, weight: 1, notes: '' },
    { name: 'Reisekleidung', qty: 1, weight: 4, notes: '' },
    {
      name: 'Entdeckerpaket',
      qty: 1,
      weight: 59,
      notes: 'Rucksack, Schlafrolle, Zunderkästchen, Fackeln ×10, Rationen ×10, Wasserschlauch, Seil 15 m',
    },
  ],
  muenzen: { gp: 25 },
  aussehen: {
    gender: 'männlich',
    age: '118',
    size: 'Klein',
    height: '99 cm',
    weight: '19 kg',
    faith: 'der Alte Hain',
    skin: 'nussbraun',
    eyes: 'moosgrün',
    hair: 'grau, mit Flechten im Bart',
  },
  wesen: {
    personality: 'Ich rede mit allem, was wächst, und warte tatsächlich die Antwort ab.',
    ideals: 'Gleichgewicht. Nimm, was du brauchst, und lege zurück, was du kannst.',
    bonds: 'Der Alte Hain hat mich vierzig Jahre beherbergt. Was ihn kahl frisst, geht mich an.',
    flaws: 'Menschen und ihre Eile ermüden mich, und das merkt man mir an.',
    backstory:
      'Vierzig Jahre lebte Fibbel allein am Rand des Alten Hains, sammelte Pilze, schrieb ein Buch darüber, das niemand las, und sprach mit den Eichhörnchen, die ihm antworteten. Dann kam die Fäule aus dem Norden, und die Bäume, die er beim Namen kannte, starben von innen. Er packte seinen Stab und ging los, weil man von einer Sache nicht heilen kann, deren Ursache man nicht kennt.',
    look: 'Reicht den meisten bis zur Hüfte und wirkt trotzdem nie klein. Trägt Flechten im Bart, die er als Vorrat bezeichnet.',
    allies: 'Der Alte Hain und ein Marder namens Nussknack, der ihm manchmal folgt.',
  },
};
