/**
 * Vorlage: Mek Halbmond – Hexenmeister, Halbork.
 *
 * Einer der zwölf fertigen Charaktere, die jede neue Kampagne hinter dem
 * Schirm vorfindet (siehe ../helden.js für die Auswahl und ../index.js fürs
 * Säen). Hier steht nur der Steckbrief – was diesen Charakter ausmacht.
 * Zum vollständigen Blatt mit allen achtzehn Fertigkeiten und leeren
 * Feldern macht ihn erst ../bauen.js.
 */
export default {
  schluessel: 'hexenmeister-halbork',
  name: 'Mek Halbmond',
  spezies: 'Halbork',
  unterart: '',
  klasse: 'Hexenmeister',
  hintergrund: 'Scharlatan',
  gesinnung: 'Neutral',
  werte: { str: 8, dex: 14, con: 14, int: 10, wis: 12, cha: 17 },
  rettungswuerfe: ['wis', 'cha'],
  fertigkeiten: ['deception', 'sleightOfHand', 'arcana', 'intimidation'],
  ruestungsklasse: 13,
  initiativeBonus: 0,
  trefferpunkte: 10,
  trefferwuerfel: '1d8',
  bewegung: 30,
  sinne: { darkvision: 60 },
  verteidigung: {},
  rettungswurfVermerk: 'Fällst du auf 0 Trefferpunkte, ohne getötet zu werden, bleibst du einmal je Lange Rast bei 1 (Unbeugsame Ausdauer).',
  uebungen: {
    armor: 'Leichte Rüstung',
    weapons: 'Einfache Waffen',
    tools: 'Fälscherausrüstung',
    languages: 'Gemeinsprache, Orkisch, Abyssisch',
  },
  angriffe: [
    { name: 'Schauerlicher Strahl', bonus: '+5', damage: '1W10+3 Energie', notes: 'Fernkampf 36 m, Zermalmender Strahl' },
    { name: 'Sichel', bonus: '+4', damage: '1W4+2 Hieb', notes: 'Leicht' },
    { name: 'Dolch', bonus: '+4', damage: '1W4+2 Stich', notes: 'Finesse, Wurf 6/18 m' },
  ],
  aktionen: [
    {
      name: 'Fluch (Konzentration)',
      art: 'bonus',
      description: '+1W6 Energieschaden bei jedem deiner Treffer gegen das Ziel, dazu Nachteil auf Proben eines Attributs deiner Wahl.',
    },
    {
      name: 'Rüstung des Agathys',
      art: 'aktion',
      description: '5 temporäre Trefferpunkte, und wer dich im Nahkampf trifft, nimmt 5 Kälteschaden.',
    },
  ],
  ressourcen: [
    { name: 'Pakt-Zauberplatz (Grad 1)', current: 1, max: 1, recharge: 'kurz' },
    { name: 'Unbeugsame Ausdauer', current: 1, max: 1, recharge: 'lang' },
  ],
  merkmale: [
    {
      name: 'Paktmagie',
      category: 'klasse',
      source: 'PHB-2024',
      page: '154',
      description:
        'Ein Zauberplatz vom 1. Grad, der sich schon nach einer Kurzen Rast erneuert. Deshalb lohnt es sich, ihn früh auszugeben.',
    },
    {
      name: 'Schauerliche Anrufung: Zermalmender Strahl',
      category: 'klasse',
      source: 'PHB-2024',
      page: '155',
      description: 'Du addierst deinen Charisma-Modifikator auf den Schaden jedes Strahls des Schauerlichen Strahls.',
    },
    {
      name: 'Jenseitiger Fürsprecher',
      category: 'klasse',
      source: 'PHB-2024',
      page: '154',
      description: 'Charisma ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5.',
    },
    { name: 'Dunkelsicht', category: 'spezies', source: 'PHB', page: '', description: '18 m weit.' },
    {
      name: 'Unbeugsame Ausdauer',
      category: 'spezies',
      source: 'PHB',
      page: '',
      description: 'Fällst du auf 0 Trefferpunkte, ohne getötet zu werden, bleibst du stattdessen bei 1. Einmal je Lange Rast.',
    },
    {
      name: 'Wilde Angriffe',
      category: 'spezies',
      source: 'PHB',
      page: '',
      description: 'Bei einem kritischen Treffer mit einer Waffe würfelst du einen zusätzlichen Schadenswürfel.',
    },
    {
      name: 'Bedrohlich',
      category: 'spezies',
      source: 'PHB',
      page: '',
      description: 'Übung in Einschüchtern.',
    },
    {
      name: 'Geübt',
      category: 'talent',
      source: 'PHB-2024',
      page: '207',
      description: 'Übung in drei weiteren Fertigkeiten oder Werkzeugen – hier Arkane Kunde, Fingerfertigkeit und die Fälscherausrüstung.',
    },
  ],
  zauber: {
    attribut: 'cha',
    plaetze: { 1: { max: 1, used: 0 } },
    liste: [
      {
        name: 'Schauerlicher Strahl',
        level: 0,
        prepared: true,
        index: 'eldritch-blast',
        source: 'Hexenmeister',
        save: '--',
        time: '1 A',
        range: '36 m',
        components: 'V, S',
        duration: 'Sofort',
        page: 'PHB-2024 261',
        notes: 'Mit Zermalmendem Strahl 1W10+3. Der beste Grundangriff, den Stufe 1 zu bieten hat.',
      },
      {
        name: 'Kleine Illusion',
        level: 0,
        prepared: true,
        index: 'minor-illusion',
        source: 'Hexenmeister',
        save: '--',
        time: '1 A',
        range: '9 m',
        components: 'S, M',
        duration: '1 Min.',
        page: 'PHB-2024 280',
        notes: 'Das Handwerkszeug eines Scharlatans.',
      },
      {
        name: 'Fluch',
        level: 1,
        prepared: true,
        index: 'hex',
        source: 'Hexenmeister',
        save: '--',
        time: '1 BA',
        range: '27 m',
        components: 'V, S, M',
        duration: 'K, 1 Std.',
        page: 'PHB-2024 271',
        notes: 'Erste Bonusaktion des Kampfes: +1W6 auf jeden Strahl.',
      },
      {
        name: 'Rüstung des Agathys',
        level: 1,
        prepared: true,
        index: 'armor-of-agathys',
        source: 'Hexenmeister',
        save: '--',
        time: '1 A',
        range: 'Selbst',
        components: 'V, S, M',
        duration: '1 Std.',
        page: 'PHB-2024 245',
        notes: '5 temporäre TP, und wer dich im Nahkampf trifft, bekommt 5 Kälteschaden zurück.',
      },
    ],
  },
  ausruestung: [
    { name: 'Lederrüstung', qty: 1, weight: 10, notes: 'RK 11 + Geschicklichkeit' },
    { name: 'Sichel', qty: 1, weight: 2, notes: '' },
    { name: 'Dolch', qty: 2, weight: 1, notes: '' },
    { name: 'Arkaner Fokus (Kugel)', qty: 1, weight: 3, notes: 'trüb, und nachts wärmer als die Luft' },
    { name: 'Buch okkulter Überlieferungen', qty: 1, weight: 5, notes: 'zur Hälfte in fremder Handschrift' },
    { name: 'Fälscherausrüstung', qty: 1, weight: 5, notes: '' },
    { name: 'Kostüm', qty: 1, weight: 4, notes: '' },
    { name: 'Feine Kleidung', qty: 1, weight: 6, notes: 'für Auftritte als jemand anderes' },
    {
      name: 'Gelehrtenpaket',
      qty: 1,
      weight: 40,
      notes: 'Rucksack, Buch, Tinte, Federkiel, Pergament ×10, Beutel Sand, Federmesser',
    },
  ],
  muenzen: { gp: 30 },
  aussehen: {
    gender: 'männlich',
    age: '31',
    size: 'Mittelgroß',
    height: '191 cm',
    weight: '101 kg',
    faith: 'er nennt keinen Namen',
    skin: 'olivgrün, an den Wangen heller',
    eyes: 'braun, das rechte seit dem Pakt milchig',
    hair: 'dunkel, zurückgebunden',
  },
  wesen: {
    personality: 'Ich rede mich aus allem heraus, und wenn nicht, rede ich weiter, bis es klappt.',
    ideals: 'Selbstbestimmung. Ich habe unterschrieben, also gehört mir wenigstens die Entscheidung.',
    bonds: 'Das Dorf Halbmond hätte den Winter nicht überstanden. Deshalb steht mein Name in diesem Buch.',
    flaws: 'Ich lüge auch dann, wenn die Wahrheit mir mehr nützen würde. Übung schlägt Verstand.',
    backstory:
      'Als der Winter über Halbmond kam und die Vorräte verbrannt waren, ging Mek in die Ruine, von der alle abrieten, und kam mit Korn zurück – und mit etwas, das seither in seinem rechten Auge sitzt. Das Dorf überstand den Winter und warf ihn im Frühjahr hinaus, weil man das eine dem anderen vorzog. Er zieht seitdem als Wahrsager, Heiler und was sonst gefragt ist von Ort zu Ort, sammelt Bücher über Pakte und sucht nach der Klausel, die er damals überlesen hat.',
    look: 'Wirkt teurer gekleidet, als er ist. Lächelt viel, und das rechte Auge lächelt nicht mit.',
    allies: 'Das Dorf Halbmond, das ihn nicht zurückhaben will, ihm aber jedes Jahr ein Fass schickt.',
  },
};
