/**
 * Vorlage: Seraphine Morgenlicht – Kleriker, Aasimar.
 *
 * Einer der zwölf fertigen Charaktere, die jede neue Kampagne hinter dem
 * Schirm vorfindet (siehe ../helden.js für die Auswahl und ../index.js fürs
 * Säen). Hier steht nur der Steckbrief – was diesen Charakter ausmacht.
 * Zum vollständigen Blatt mit allen achtzehn Fertigkeiten und leeren
 * Feldern macht ihn erst ../bauen.js.
 */
export default {
  schluessel: 'kleriker-aasimar',
  name: 'Seraphine Morgenlicht',
  spezies: 'Aasimar',
  unterart: '',
  klasse: 'Kleriker',
  hintergrund: 'Akolyth',
  gesinnung: 'Rechtschaffen Gut',
  werte: { str: 12, dex: 10, con: 14, int: 8, wis: 17, cha: 14 },
  rettungswuerfe: ['wis', 'cha'],
  fertigkeiten: ['insight', 'religion', 'medicine', 'persuasion'],
  ruestungsklasse: 15,
  initiativeBonus: 0,
  trefferpunkte: 10,
  trefferwuerfel: '1d8',
  bewegung: 30,
  sinne: { darkvision: 60 },
  verteidigung: { resistances: 'Nekrotisch, gleißend' },
  rettungswurfVermerk: '',
  uebungen: {
    armor: 'Leichte und mittlere Rüstung, Schilde',
    weapons: 'Einfache Waffen',
    tools: 'Kalligraphenbedarf',
    languages: 'Gemeinsprache, Himmlisch',
  },
  angriffe: [
    { name: 'Streitkolben', bonus: '+3', damage: '1W6+1 Wucht', notes: '' },
    { name: 'Heilige Flamme', bonus: 'SG 13', damage: '1W8 gleißend', notes: 'GES-RW, Deckung hilft nicht' },
  ],
  aktionen: [
    {
      name: 'Heilende Hände',
      art: 'aktion',
      description: 'Berührung: 1W4 Trefferpunkte zurück. Einmal je Lange Rast.',
    },
    {
      name: 'Segnen (Konzentration)',
      art: 'aktion',
      description: 'Drei Verbündete addieren 1W4 auf Angriffe und Rettungswürfe. Der stärkste Zauber, den du auf Stufe 1 hast.',
    },
  ],
  ressourcen: [
    { name: 'Heilende Hände', current: 1, max: 1, recharge: 'lang' },
    { name: 'Kanalisierte Göttlichkeit', current: 2, max: 2, recharge: 'kurz' },
  ],
  merkmale: [
    {
      name: 'Zauberwirken',
      category: 'klasse',
      source: 'PHB-2024',
      page: '68',
      description: 'Weisheit ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5. Du bereitest vier Zauber vor.',
    },
    {
      name: 'Göttlicher Orden: Beschützer',
      category: 'klasse',
      source: 'PHB-2024',
      page: '68',
      description: 'Übung mit schweren Rüstungen und Kriegswaffen – für den Fall, dass du sie findest.',
    },
    {
      name: 'Dunkelsicht',
      category: 'spezies',
      source: 'PHB-2024',
      page: '184',
      description: '18 m weit.',
    },
    {
      name: 'Himmlische Widerstandskraft',
      category: 'spezies',
      source: 'PHB-2024',
      page: '184',
      description: 'Resistenz gegen nekrotischen und gleißenden Schaden.',
    },
    {
      name: 'Heilende Hände',
      category: 'spezies',
      source: 'PHB-2024',
      page: '184',
      description: 'Als Aktion 1W4 Trefferpunkte durch Berührung. Einmal je Lange Rast.',
    },
    {
      name: 'Lichtträger',
      category: 'spezies',
      source: 'PHB-2024',
      page: '184',
      description: 'Du kennst den Zaubertrick Licht.',
    },
    {
      name: 'Magiekundig (Kleriker)',
      category: 'hintergrund',
      source: 'PHB-2024',
      page: '202',
      description: 'Zwei Zaubertricks und ein Zauber vom 1. Grad aus der Klerikerliste, einmal je Lange Rast ohne Platz.',
    },
  ],
  zauber: {
    attribut: 'wis',
    plaetze: { 1: { max: 2, used: 0 } },
    liste: [
      {
        name: 'Heilige Flamme',
        level: 0,
        prepared: true,
        index: 'sacred-flame',
        source: 'Kleriker',
        save: 'GES-RW',
        time: '1 A',
        range: '18 m',
        components: 'V, S',
        duration: 'Sofort',
        page: 'PHB-2024 293',
        notes: 'Deckung nützt dem Ziel nichts – gut gegen alles hinter Steinen.',
      },
      {
        name: 'Führung',
        level: 0,
        prepared: true,
        index: 'guidance',
        source: 'Kleriker',
        save: '--',
        time: '1 A',
        range: 'Berührung',
        components: 'V, S',
        duration: 'K, 1 Min.',
        page: 'PHB-2024 267',
        notes: '+1W4 auf eine Attributsprobe. Außerhalb des Kampfes fast immer angebracht.',
      },
      {
        name: 'Licht',
        level: 0,
        prepared: true,
        index: 'light',
        source: 'Aasimar',
        save: '--',
        time: '1 A',
        range: 'Berührung',
        components: 'V, M',
        duration: '1 Std.',
        page: 'PHB-2024 275',
        notes: '',
      },
      {
        name: 'Segnen',
        level: 1,
        prepared: true,
        index: 'bless',
        source: 'Kleriker',
        save: '--',
        time: '1 A',
        range: '9 m',
        components: 'V, S, M',
        duration: 'K, 1 Min.',
        page: 'PHB-2024 247',
        notes: 'Drei Ziele, +1W4 auf Angriffe und Rettungswürfe. Zuerst wirken, dann alles andere.',
      },
      {
        name: 'Wunden heilen',
        level: 1,
        prepared: true,
        index: 'cure-wounds',
        source: 'Kleriker',
        save: '--',
        time: '1 A',
        range: 'Berührung',
        components: 'V, S',
        duration: 'Sofort',
        page: 'PHB-2024 255',
        notes: '2W8 + 3 Trefferpunkte.',
      },
      {
        name: 'Führender Blitz',
        level: 1,
        prepared: true,
        index: 'guiding-bolt',
        source: 'Kleriker',
        save: '--',
        time: '1 A',
        range: '36 m',
        components: 'V, S',
        duration: '1 Runde',
        page: 'PHB-2024 268',
        notes: '4W6 gleißend, und der nächste Angriff gegen das Ziel hat Vorteil.',
      },
      {
        name: 'Schild des Glaubens',
        level: 1,
        prepared: true,
        index: 'shield-of-faith',
        source: 'Kleriker',
        save: '--',
        time: '1 BA',
        range: '18 m',
        components: 'V, S, M',
        duration: 'K, 10 Min.',
        page: 'PHB-2024 296',
        notes: '+2 RK für einen Verbündeten. Bonusaktion.',
      },
    ],
  },
  ausruestung: [
    { name: 'Kettenhemd', qty: 1, weight: 20, notes: 'RK 13 + Geschicklichkeit (max. 2)' },
    { name: 'Schild', qty: 1, weight: 6, notes: '+2 RK' },
    { name: 'Streitkolben', qty: 1, weight: 4, notes: '' },
    { name: 'Heiliges Symbol', qty: 1, weight: 1, notes: 'Zauberfokus' },
    { name: 'Kalligraphenbedarf', qty: 1, weight: 5, notes: '' },
    { name: 'Gebetbuch', qty: 1, weight: 5, notes: '' },
    { name: 'Pergament', qty: 10, weight: 0, notes: '' },
    { name: 'Robe', qty: 1, weight: 4, notes: '' },
    {
      name: 'Priesterpaket',
      qty: 1,
      weight: 25,
      notes: 'Rucksack, Decke, Kerzen ×10, Zunderkästchen, Almosenbüchse, Weihrauch ×2, Räuchergefäß, Gewand, Rationen ×2, Wasserschlauch',
    },
  ],
  muenzen: { gp: 15 },
  aussehen: {
    gender: 'weiblich',
    age: '27',
    size: 'Mittelgroß',
    height: '169 cm',
    weight: '63 kg',
    faith: 'Lathander',
    skin: 'warm, mit einem schwachen Schimmer an den Schläfen',
    eyes: 'bernsteinfarben, ohne sichtbare Pupille im Licht',
    hair: 'weißblond',
  },
  wesen: {
    personality: 'Ich frage zuerst, was jemand braucht, und erst danach, wer er ist.',
    ideals: 'Barmherzigkeit. Wer um Hilfe bittet, hat damit genug gesagt.',
    bonds: 'Das Waisenhaus am Morgentor hat mich großgezogen, ohne zu wissen, was ich bin. Es hat kein Geld.',
    flaws: 'Ich heile weiter, wenn längst Zeit wäre zu fliehen, und reiße die anderen mit hinein.',
    backstory:
      'Sie wurde in einem Korb an der Tür des Waisenhauses am Morgentor gefunden, und die Schwestern behielten für sich, dass das Kind im Dunkeln leuchtete. Mit siebzehn hörte Seraphine zum ersten Mal die Stimme, die ihr sagte, wohin sie gehen solle – und sie ging, weil die Alternative war, weiter Suppe auszuteilen, während draußen etwas Falsches geschah. Zurück schickt sie jeden Monat, was sie erübrigen kann.',
    look: 'Ruhig, aufrecht, mit einem Blick, den Leute länger halten als beabsichtigt. Im Halbdunkel sieht man, dass ihre Haut ein wenig Licht abgibt.',
    allies: 'Das Waisenhaus am Morgentor und Schwester Ilva, die ihr schreibt.',
  },
};
