/**
 * Vorlage: Aldric Fenn – Magier, Mensch.
 *
 * Einer der zwölf fertigen Charaktere, die jede neue Kampagne hinter dem
 * Schirm vorfindet (siehe ../helden.js für die Auswahl und ../index.js fürs
 * Säen). Hier steht nur der Steckbrief – was diesen Charakter ausmacht.
 * Zum vollständigen Blatt mit allen achtzehn Fertigkeiten und leeren
 * Feldern macht ihn erst ../bauen.js.
 */
export default {
  schluessel: 'magier-mensch',
  name: 'Aldric Fenn',
  spezies: 'Mensch',
  unterart: '',
  klasse: 'Magier',
  hintergrund: 'Gelehrter',
  gesinnung: 'Neutral Gut',
  werte: { str: 8, dex: 14, con: 14, int: 17, wis: 12, cha: 10 },
  rettungswuerfe: ['int', 'wis'],
  fertigkeiten: ['arcana', 'history', 'investigation', 'insight', 'perception'],
  // Ohne Rüstung 12; mit Magierrüstung 15.
  ruestungsklasse: 12,
  // Wachsam legt den Übungsbonus auf die Initiative.
  initiativeBonus: 2,
  trefferpunkte: 8,
  trefferwuerfel: '1d6',
  bewegung: 30,
  sinne: {},
  verteidigung: {},
  rettungswurfVermerk: '',
  uebungen: {
    armor: 'keine',
    weapons: 'Einfache Waffen',
    tools: 'Kalligraphenbedarf',
    languages: 'Gemeinsprache, Draconisch, Zwergisch, Elfisch',
  },
  angriffe: [
    { name: 'Feuerblitz', bonus: '+5', damage: '1W10 Feuer', notes: 'Fernkampf 36 m – dein Grundangriff' },
    { name: 'Magisches Geschoss', bonus: 'trifft immer', damage: '3 × (1W4+1) Energie', notes: 'Kein Wurf, keine Rettung' },
    { name: 'Dolch', bonus: '+4', damage: '1W4+2 Stich', notes: 'Finesse, Wurf 6/18 m' },
  ],
  aktionen: [
    {
      name: 'Schild',
      art: 'reaktion',
      description: 'Wenn dich ein Angriff trifft: +5 RK bis zum Beginn deines nächsten Zuges. Wehrt Magisches Geschoss ganz ab.',
    },
    {
      name: 'Schlaf',
      art: 'aktion',
      description: '5W8 Trefferpunkte an Geschöpfen in einer 6-m-Kugel schlafen ein, von den schwächsten aufwärts. Beendet ganze Kämpfe.',
    },
    {
      name: 'Ritual: Magie entdecken',
      art: 'frei',
      description: 'Als Ritual gewirkt kostet es keinen Zauberplatz, nur zehn Minuten mehr.',
    },
  ],
  ressourcen: [{ name: 'Heldenhafte Inspiration', current: 1, max: 1, recharge: 'lang' }],
  merkmale: [
    {
      name: 'Zauberwirken',
      category: 'klasse',
      source: 'PHB-2024',
      page: '162',
      description:
        'Intelligenz ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5. Vier Zauber aus dem Buch vorbereitet.',
    },
    {
      name: 'Ritualwirken',
      category: 'klasse',
      source: 'PHB-2024',
      page: '162',
      description: 'Zauber mit dem Vermerk Ritual kannst du aus dem Buch wirken, ohne einen Platz auszugeben.',
    },
    {
      name: 'Arkane Erholung',
      category: 'klasse',
      source: 'PHB-2024',
      page: '162',
      description: 'Nach einer Kurzen Rast einmal am Tag einen Zauberplatz vom 1. Grad zurückgewinnen.',
    },
    {
      name: 'Findig',
      category: 'spezies',
      source: 'PHB-2024',
      page: '194',
      description: 'Nach jeder Langen Rast erhältst du Heldenhafte Inspiration.',
    },
    {
      name: 'Geschickt',
      category: 'spezies',
      source: 'PHB-2024',
      page: '194',
      description: 'Übung in einer weiteren Fertigkeit – hier Wahrnehmung.',
    },
    {
      name: 'Vielseitig',
      category: 'spezies',
      source: 'PHB-2024',
      page: '194',
      description: 'Ein zusätzliches Ursprungstalent – hier Wachsam.',
    },
    {
      name: 'Wachsam',
      category: 'talent',
      source: 'PHB-2024',
      page: '200',
      description: 'Übungsbonus auf die Initiative, und du darfst sie mit einem einverstandenen Verbündeten tauschen.',
    },
    {
      name: 'Magiekundig (Magier)',
      category: 'hintergrund',
      source: 'PHB-2024',
      page: '202',
      description: 'Zwei Zaubertricks und ein Zauber vom 1. Grad aus der Magierliste, einmal je Lange Rast ohne Platz.',
    },
  ],
  zauber: {
    attribut: 'int',
    plaetze: { 1: { max: 2, used: 0 } },
    liste: [
      {
        name: 'Feuerblitz',
        level: 0,
        prepared: true,
        index: 'fire-bolt',
        source: 'Magier',
        save: '--',
        time: '1 A',
        range: '36 m',
        components: 'V, S',
        duration: 'Sofort',
        page: 'PHB-2024 264',
        notes: 'Dein Grundangriff, solange Plätze knapp sind.',
      },
      {
        name: 'Magierhand',
        level: 0,
        prepared: true,
        index: 'mage-hand',
        source: 'Magier',
        save: '--',
        time: '1 A',
        range: '9 m',
        components: 'V, S',
        duration: '1 Min.',
        page: 'PHB-2024 278',
        notes: 'Hebel ziehen, Fallen auslösen, Dinge holen – aus sicherer Entfernung.',
      },
      {
        name: 'Blendwerk',
        level: 0,
        prepared: true,
        index: 'prestidigitation',
        source: 'Magier',
        save: '--',
        time: '1 A',
        range: '3 m',
        components: 'V, S',
        duration: 'bis 1 Std.',
        page: 'PHB-2024 289',
        notes: '',
      },
      {
        name: 'Magisches Geschoss',
        level: 1,
        prepared: true,
        index: 'magic-missile',
        source: 'Zauberbuch',
        save: '--',
        time: '1 A',
        range: '36 m',
        components: 'V, S',
        duration: 'Sofort',
        page: 'PHB-2024 278',
        notes: 'Trifft ohne Wurf. Der sichere Schaden.',
      },
      {
        name: 'Schild',
        level: 1,
        prepared: true,
        index: 'shield',
        source: 'Zauberbuch',
        save: '--',
        time: '1 R',
        range: 'Selbst',
        components: 'V, S',
        duration: '1 Runde',
        page: 'PHB-2024 296',
        notes: 'Reaktion: +5 RK. Der Grund, warum du mit RK 12 überlebst.',
      },
      {
        name: 'Schlaf',
        level: 1,
        prepared: true,
        index: 'sleep',
        source: 'Zauberbuch',
        save: '--',
        time: '1 A',
        range: '27 m',
        components: 'V, S, M',
        duration: 'K, 1 Min.',
        page: 'PHB-2024 298',
        notes: 'Der stärkste Zauber vom 1. Grad auf niedrigen Stufen.',
      },
      {
        name: 'Magierrüstung',
        level: 1,
        prepared: false,
        index: 'mage-armor',
        source: 'Zauberbuch',
        save: '--',
        time: '1 A',
        range: 'Berührung',
        components: 'V, S, M',
        duration: '8 Std.',
        page: 'PHB-2024 278',
        notes: 'Im Buch. Morgens vorbereiten, dann RK 15 für den ganzen Tag.',
      },
      {
        name: 'Magie entdecken',
        level: 1,
        prepared: false,
        index: 'detect-magic',
        source: 'Zauberbuch',
        save: '--',
        time: '1 A',
        range: 'Selbst (9 m)',
        components: 'V, S',
        duration: 'K, 10 Min.',
        page: 'PHB-2024 258',
        notes: 'Ritual – kostet als solches keinen Platz.',
      },
      {
        name: 'Schmierfett',
        level: 1,
        prepared: false,
        index: 'grease',
        source: 'Zauberbuch',
        save: 'GES-RW',
        time: '1 A',
        range: '18 m',
        components: 'V, S, M',
        duration: '1 Min.',
        page: 'PHB-2024 267',
        notes: 'Im Buch. 3-m-Quadrat schwieriges Gelände, wer nicht besteht, wird liegend.',
      },
    ],
  },
  ausruestung: [
    { name: 'Dolch', qty: 2, weight: 1, notes: '' },
    { name: 'Kampfstab', qty: 1, weight: 4, notes: 'Arkaner Fokus' },
    { name: 'Robe', qty: 1, weight: 4, notes: '' },
    { name: 'Zauberbuch', qty: 1, weight: 3, notes: 'sechs Zauber vom 1. Grad' },
    { name: 'Kalligraphenbedarf', qty: 1, weight: 5, notes: '' },
    { name: 'Buch über die Belagerung von Fenn', qty: 1, weight: 5, notes: 'sein eigenes, unvollendet' },
    { name: 'Pergament', qty: 8, weight: 0, notes: '' },
    {
      name: 'Gelehrtenpaket',
      qty: 1,
      weight: 40,
      notes: 'Rucksack, Buch, Tinte, Federkiel, Pergament ×10, Beutel Sand, Federmesser',
    },
  ],
  muenzen: { gp: 13 },
  aussehen: {
    gender: 'männlich',
    age: '41',
    size: 'Mittelgroß',
    height: '177 cm',
    weight: '70 kg',
    faith: 'die Archive',
    skin: 'blass, wenig draußen gewesen',
    eyes: 'grau',
    hair: 'dunkelbraun, an den Schläfen ergraut',
  },
  wesen: {
    personality: 'Ich schreibe mit, während andere reden. Nicht aus Misstrauen – ich vergesse sonst.',
    ideals: 'Wahrheit. Eine Quelle, die nicht geprüft ist, ist ein Gerücht mit Fußnote.',
    bonds: 'Die Bibliothek von Fenn brannte, und ich rettete elf Bände. Ich weiß bis heute, welche zwölf ich liegen ließ.',
    flaws: 'Ich halte einen Streit für gewonnen, sobald ich recht habe – und merke zu spät, dass das nicht dasselbe ist.',
    backstory:
      'Aldric verbrachte zwanzig Jahre im Archiv seiner Heimatstadt und hätte dort auch die nächsten zwanzig verbracht, hätte in der Nacht der Belagerung nicht das Dach gebrannt. Er trug hinaus, was er tragen konnte, und schrieb später auf, was in den verlorenen Bänden gestanden hatte – aus dem Gedächtnis, mit einer Sorgfalt, die ihn selbst quält. Um die Lücken zu füllen, muss er nun an die Orte, über die er bisher nur gelesen hat.',
    look: 'Schmal, immer ein wenig zerstreut wirkend, mit Tinte an den Fingern und einem Blick, der Räume liest wie Seiten.',
    allies: 'Die Archivarsgilde von Fenn, die ihm Ausleihen gewährt, die sonst niemand bekommt.',
  },
};
