/**
 * Vorlage: Naelith Silberpfeil – Waldläufer, Elf.
 *
 * Einer der zwölf fertigen Charaktere, die jede neue Kampagne hinter dem
 * Schirm vorfindet (siehe ../helden.js für die Auswahl und ../index.js fürs
 * Säen). Hier steht nur der Steckbrief – was diesen Charakter ausmacht.
 * Zum vollständigen Blatt mit allen achtzehn Fertigkeiten und leeren
 * Feldern macht ihn erst ../bauen.js.
 */
export default {
  schluessel: 'waldlaeufer-elf',
  name: 'Naelith Silberpfeil',
  spezies: 'Elf',
  unterart: 'Waldelf',
  klasse: 'Waldläufer',
  hintergrund: 'Fährtensucher',
  gesinnung: 'Neutral Gut',
  werte: { str: 12, dex: 17, con: 14, int: 10, wis: 14, cha: 8 },
  rettungswuerfe: ['str', 'dex'],
  fertigkeiten: ['stealth', 'survival', 'perception', 'nature', 'insight'],
  expertise: [],
  ruestungsklasse: 15,
  initiativeBonus: 0,
  trefferpunkte: 12,
  trefferwuerfel: '1d10',
  bewegung: 35,
  sinne: { darkvision: 60 },
  verteidigung: {},
  rettungswurfVermerk: 'Vorteil auf Rettungswürfe gegen Bezauberung, und Magie kann dich nicht schlafen legen (Feenblut, Trance).',
  uebungen: {
    armor: 'Leichte und mittlere Rüstung, Schilde',
    weapons: 'Einfache Waffen, Kriegswaffen',
    tools: 'Kartografenwerkzeug',
    languages: 'Gemeinsprache, Elfisch, Sylvanisch',
  },
  angriffe: [
    { name: 'Langbogen', bonus: '+5', damage: '1W8+3 Stich', notes: '45/180 m, Schwer, Zweihändig · Meisterschaft: Verlangsamen' },
    { name: 'Kurzschwert', bonus: '+5', damage: '1W6+3 Stich', notes: 'Finesse, Leicht · Meisterschaft: Ärgern' },
    { name: 'Krummsäbel', bonus: '+5', damage: '1W6+3 Hieb', notes: 'Finesse, Leicht' },
  ],
  aktionen: [
    {
      name: 'Jagdzeichen',
      art: 'bonus',
      description:
        'Ein Ziel in 27 m markieren: +1W6 Schaden bei jedem deiner Treffer, solange du dich konzentrierst. Zweimal ohne Zauberplatz je Lange Rast.',
    },
    {
      name: 'Fesselnder Schlag',
      art: 'bonus',
      description: 'Der nächste Treffer umschlingt das Ziel: 1W6 Stich je Runde, festgesetzt bis zum Befreien (STÄ, SG 13).',
    },
  ],
  ressourcen: [{ name: 'Jagdzeichen (frei)', current: 2, max: 2, recharge: 'lang' }],
  merkmale: [
    {
      name: 'Bevorzugter Feind: Jagdzeichen',
      category: 'klasse',
      source: 'PHB-2024',
      page: '131',
      description:
        'Jagdzeichen ist immer vorbereitet und kostet dich übungsbonus-mal je Lange Rast keinen Zauberplatz.',
    },
    {
      name: 'Zauberwirken',
      category: 'klasse',
      source: 'PHB-2024',
      page: '131',
      description: 'Weisheit ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5. Du bereitest zwei Zauber vor.',
    },
    {
      name: 'Waffenmeisterschaft',
      category: 'klasse',
      source: 'PHB-2024',
      page: '131',
      description:
        'Zwei Waffen: Langbogen (Verlangsamen – 3 m weniger Bewegung), Kurzschwert (Ärgern – dein nächster Angriff gegen dasselbe Ziel hat Vorteil).',
    },
    { name: 'Dunkelsicht', category: 'spezies', source: 'PHB-2024', page: '190', description: '18 m weit.' },
    {
      name: 'Feenblut',
      category: 'spezies',
      source: 'PHB-2024',
      page: '190',
      description: 'Vorteil auf Rettungswürfe, um die Bedingung Bezaubert zu vermeiden oder zu beenden.',
    },
    {
      name: 'Scharfe Sinne',
      category: 'spezies',
      source: 'PHB-2024',
      page: '190',
      description: 'Übung in Wahrnehmung.',
    },
    {
      name: 'Trance',
      category: 'spezies',
      source: 'PHB-2024',
      page: '190',
      description: 'Du schläfst nicht. Eine Lange Rast dauert für dich vier Stunden wacher Meditation.',
    },
    {
      name: 'Elfische Abstammung: Waldelf',
      category: 'spezies',
      source: 'PHB-2024',
      page: '190',
      description: 'Bewegungsrate 10,5 m, und du kennst den Zauber Weitschritt (einmal je Lange Rast ohne Platz).',
    },
    {
      name: 'Magiekundig (Urtümlich)',
      category: 'hintergrund',
      source: 'PHB-2024',
      page: '202',
      description: 'Zwei Zaubertricks und ein Zauber vom 1. Grad aus der Druidenliste, einmal je Lange Rast ohne Platz.',
    },
  ],
  zauber: {
    attribut: 'wis',
    plaetze: { 1: { max: 2, used: 0 } },
    liste: [
      {
        name: 'Jagdzeichen',
        level: 1,
        prepared: true,
        index: 'hunters-mark',
        source: 'Bevorzugter Feind',
        save: '--',
        time: '1 BA',
        range: '27 m',
        components: 'V',
        duration: 'K, 1 Std.',
        page: 'PHB-2024 272',
        notes: 'Immer vorbereitet. Erste Bonusaktion jedes Kampfes.',
      },
      {
        name: 'Fesselnder Schlag',
        level: 1,
        prepared: true,
        index: 'ensnaring-strike',
        source: 'Waldläufer',
        save: 'STÄ-RW',
        time: '1 BA',
        range: 'Selbst',
        components: 'V',
        duration: 'K, 1 Min.',
        page: 'PHB-2024 261',
        notes: 'Hält einen Gegner fest, ohne dass jemand hin muss.',
      },
      {
        name: 'Wunden heilen',
        level: 1,
        prepared: true,
        index: 'cure-wounds',
        source: 'Waldläufer',
        save: '--',
        time: '1 A',
        range: 'Berührung',
        components: 'V, S',
        duration: 'Sofort',
        page: 'PHB-2024 255',
        notes: '2W8 + 2 – die einzige Heilung der Gruppe, wenn kein Kleriker dabei ist.',
      },
      {
        name: 'Druidenkunst',
        level: 0,
        prepared: true,
        index: 'druidcraft',
        source: 'Magiekundig',
        save: '--',
        time: '1 A',
        range: '9 m',
        components: 'V, S',
        duration: 'Sofort',
        page: 'PHB-2024 260',
        notes: '',
      },
      {
        name: 'Weitschritt',
        level: 1,
        prepared: true,
        index: 'longstrider',
        source: 'Waldelf',
        save: '--',
        time: '1 A',
        range: 'Berührung',
        components: 'V, S, M',
        duration: '1 Std.',
        page: 'PHB-2024 277',
        notes: 'Einmal je Lange Rast ohne Zauberplatz. +3 m Bewegung für eine Stunde.',
      },
    ],
  },
  ausruestung: [
    { name: 'Nietlederrüstung', qty: 1, weight: 13, notes: 'RK 12 + Geschicklichkeit' },
    { name: 'Langbogen', qty: 1, weight: 2, notes: '' },
    { name: 'Pfeile', qty: 40, weight: 0.05, notes: 'zwanzig aus der Klasse, zwanzig vom Hintergrund' },
    { name: 'Köcher', qty: 2, weight: 1, notes: '' },
    { name: 'Kurzschwert', qty: 1, weight: 2, notes: '' },
    { name: 'Krummsäbel', qty: 1, weight: 3, notes: '' },
    { name: 'Kurzbogen', qty: 1, weight: 2, notes: 'als Ersatz im Gepäck' },
    { name: 'Druidenfokus (Mistelzweig)', qty: 1, weight: 0, notes: '' },
    { name: 'Kartografenwerkzeug', qty: 1, weight: 6, notes: '' },
    { name: 'Schlafrolle', qty: 1, weight: 7, notes: '' },
    { name: 'Zelt', qty: 1, weight: 20, notes: 'für zwei Personen' },
    { name: 'Reisekleidung', qty: 1, weight: 4, notes: '' },
    {
      name: 'Entdeckerpaket',
      qty: 1,
      weight: 59,
      notes: 'Rucksack, Schlafrolle, Zunderkästchen, Fackeln ×10, Rationen ×10, Wasserschlauch, Seil 15 m',
    },
  ],
  muenzen: { gp: 10 },
  aussehen: {
    gender: 'weiblich',
    age: '142',
    size: 'Mittelgroß',
    height: '178 cm',
    weight: '58 kg',
    faith: 'die Wege selbst',
    skin: 'kupferbraun',
    eyes: 'waldgrün',
    hair: 'kastanienbraun, an einer Seite geflochten',
  },
  wesen: {
    personality: 'Ich gehe voraus und sage erst etwas, wenn ich etwas gefunden habe.',
    ideals: 'Umsicht. Der Weg, den man kennt, ist den Umweg wert.',
    bonds: 'Ich habe eine Karawane in einen Pass geführt, aus dem nur ich zurückkam. Die Karte war meine.',
    flaws: 'Ich vertraue meinen eigenen Augen mehr als jedem Menschen, auch wenn beide sich irren.',
    backstory:
      'Naelith führte vierzig Jahre lang Leute über die Nordpässe und verlor in dieser Zeit niemanden – bis zu dem Winter, in dem ein Weg, den sie hundertmal gegangen war, unter einer Karawane wegbrach. Man gab ihr keine Schuld; das machte es nicht besser. Seither zeichnet sie jede Route doppelt, geht als Erste und ist bei jeder Gruppe, die sie begleitet, unangenehm gründlich.',
    look: 'Bewegt sich, ohne Geräusche zu machen, und bleibt oft stehen, um etwas anzusehen, das sonst niemand bemerkt hat.',
    allies: 'Die Kartografengilde von Weißfurt, die ihre Karten noch immer kauft.',
  },
};
