/**
 * Vorlage: Ghorza Sturmader – Zauberer, Ork.
 *
 * Einer der zwölf fertigen Charaktere, die jede neue Kampagne hinter dem
 * Schirm vorfindet (siehe ../helden.js für die Auswahl und ../index.js fürs
 * Säen). Hier steht nur der Steckbrief – was diesen Charakter ausmacht.
 * Zum vollständigen Blatt mit allen achtzehn Fertigkeiten und leeren
 * Feldern macht ihn erst ../bauen.js.
 */
export default {
  schluessel: 'zauberer-ork',
  name: 'Ghorza Sturmader',
  spezies: 'Ork',
  unterart: '',
  klasse: 'Zauberer',
  hintergrund: 'Händler',
  gesinnung: 'Chaotisch Neutral',
  werte: { str: 8, dex: 14, con: 14, int: 10, wis: 12, cha: 17 },
  rettungswuerfe: ['con', 'cha'],
  fertigkeiten: ['animalHandling', 'persuasion', 'arcana', 'intimidation'],
  // Ohne Rüstung 12; mit Magierrüstung 15.
  ruestungsklasse: 12,
  initiativeBonus: 0,
  trefferpunkte: 8,
  trefferwuerfel: '1d6',
  bewegung: 30,
  sinne: { darkvision: 120 },
  verteidigung: {},
  rettungswurfVermerk: 'Fällst du auf 0 Trefferpunkte, ohne getötet zu werden, bleibst du einmal je Lange Rast bei 1 (Unbeugsame Ausdauer).',
  uebungen: {
    armor: 'keine',
    weapons: 'Einfache Waffen',
    tools: 'Navigationswerkzeug',
    languages: 'Gemeinsprache, Orkisch',
  },
  angriffe: [
    { name: 'Feuerblitz', bonus: '+5', damage: '1W10 Feuer', notes: 'Fernkampf 36 m – dein Grundangriff' },
    { name: 'Speer', bonus: '+1', damage: '1W6-1 Stich', notes: 'nur im Notfall' },
    { name: 'Magisches Geschoss', bonus: 'trifft immer', damage: '3 × (1W4+1) Energie', notes: 'Kein Wurf, keine Rettung' },
  ],
  aktionen: [
    {
      name: 'Angeborene Zauberei',
      art: 'bonus',
      description:
        'Für 1 Minute: +1 auf deinen Zauber-SG und Vorteil auf alle deine Zauberangriffe. Zweimal je Lange Rast.',
    },
    {
      name: 'Adrenalinschub',
      art: 'bonus',
      description: 'Spurten als Bonusaktion und 2 temporäre Trefferpunkte. Übungsbonus-mal je Rast.',
    },
  ],
  ressourcen: [
    { name: 'Angeborene Zauberei', current: 2, max: 2, recharge: 'lang' },
    { name: 'Adrenalinschub', current: 2, max: 2, recharge: 'kurz' },
    { name: 'Unbeugsame Ausdauer', current: 1, max: 1, recharge: 'lang' },
  ],
  merkmale: [
    {
      name: 'Angeborene Zauberei',
      category: 'klasse',
      source: 'PHB-2024',
      page: '139',
      description:
        'Als Bonusaktion für 1 Minute: Zauber-SG +1 und Vorteil auf alle Zauberangriffswürfe. Zweimal je Lange Rast.',
    },
    {
      name: 'Zauberwirken',
      category: 'klasse',
      source: 'PHB-2024',
      page: '139',
      description: 'Charisma ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5. Vier Zaubertricks, zwei Zauber bekannt.',
    },
    { name: 'Dunkelsicht', category: 'spezies', source: 'PHB-2024', page: '194', description: '36 m weit.' },
    {
      name: 'Adrenalinschub',
      category: 'spezies',
      source: 'PHB-2024',
      page: '194',
      description:
        'Spurten als Bonusaktion, dazu temporäre Trefferpunkte in Höhe deines Übungsbonus. Übungsbonus-mal, erneuert sich nach einer Rast.',
    },
    {
      name: 'Unbeugsame Ausdauer',
      category: 'spezies',
      source: 'PHB-2024',
      page: '194',
      description: 'Fällst du auf 0 Trefferpunkte, ohne getötet zu werden, bleibst du stattdessen bei 1. Einmal je Lange Rast.',
    },
    {
      name: 'Glückspilz',
      category: 'talent',
      source: 'PHB-2024',
      page: '202',
      description: 'Übungsbonus-viele Glückspunkte je Lange Rast: Vorteil auf einen eigenen W20 oder Nachteil auf einen Angriff gegen dich.',
    },
  ],
  zauber: {
    attribut: 'cha',
    plaetze: { 1: { max: 2, used: 0 } },
    liste: [
      {
        name: 'Feuerblitz',
        level: 0,
        prepared: true,
        index: 'fire-bolt',
        source: 'Zauberer',
        save: '--',
        time: '1 A',
        range: '36 m',
        components: 'V, S',
        duration: 'Sofort',
        page: 'PHB-2024 264',
        notes: 'Dein Grundangriff. 1W10 Feuer, entzündet brennbare Gegenstände.',
      },
      {
        name: 'Licht',
        level: 0,
        prepared: true,
        index: 'light',
        source: 'Zauberer',
        save: '--',
        time: '1 A',
        range: 'Berührung',
        components: 'V, M',
        duration: '1 Std.',
        page: 'PHB-2024 275',
        notes: '',
      },
      {
        name: 'Kleine Illusion',
        level: 0,
        prepared: true,
        index: 'minor-illusion',
        source: 'Zauberer',
        save: '--',
        time: '1 A',
        range: '9 m',
        components: 'S, M',
        duration: '1 Min.',
        page: 'PHB-2024 280',
        notes: '',
      },
      {
        name: 'Blendwerk',
        level: 0,
        prepared: true,
        index: 'prestidigitation',
        source: 'Zauberer',
        save: '--',
        time: '1 A',
        range: '3 m',
        components: 'V, S',
        duration: 'bis 1 Std.',
        page: 'PHB-2024 289',
        notes: '',
      },
      {
        name: 'Magierrüstung',
        level: 1,
        prepared: true,
        index: 'mage-armor',
        source: 'Zauberer',
        save: '--',
        time: '1 A',
        range: 'Berührung',
        components: 'V, S, M',
        duration: '8 Std.',
        page: 'PHB-2024 278',
        notes: 'Morgens auf dich selbst: RK 15 statt 12, den ganzen Tag.',
      },
      {
        name: 'Magisches Geschoss',
        level: 1,
        prepared: true,
        index: 'magic-missile',
        source: 'Zauberer',
        save: '--',
        time: '1 A',
        range: '36 m',
        components: 'V, S',
        duration: 'Sofort',
        page: 'PHB-2024 278',
        notes: 'Trifft ohne Wurf – der sichere Schaden, wenn es knapp wird.',
      },
    ],
  },
  ausruestung: [
    { name: 'Speer', qty: 1, weight: 3, notes: '' },
    { name: 'Dolch', qty: 2, weight: 1, notes: '' },
    { name: 'Arkaner Fokus (Kristall)', qty: 1, weight: 1, notes: 'ein Stück Blitzglas aus der Steppe' },
    { name: 'Navigationswerkzeug', qty: 1, weight: 2, notes: '' },
    { name: 'Beutel', qty: 2, weight: 1, notes: '' },
    { name: 'Reisekleidung', qty: 1, weight: 4, notes: '' },
    {
      name: 'Höhlenforscherpaket',
      qty: 1,
      weight: 55,
      notes: 'Rucksack, Brecheisen, Hammer, Pitons ×10, Fackeln ×10, Zunderkästchen, Rationen ×10, Wasserschlauch, Seil 15 m',
    },
  ],
  muenzen: { gp: 50 },
  aussehen: {
    gender: 'weiblich',
    age: '24',
    size: 'Mittelgroß',
    height: '188 cm',
    weight: '94 kg',
    faith: 'keiner, aber sie dankt dem Sturm',
    skin: 'graugrün',
    eyes: 'gelb',
    hair: 'schwarz, an den Seiten geschoren',
  },
  wesen: {
    personality: 'Ich handle über alles, auch wenn ich es gar nicht will. Feilschen beruhigt mich.',
    ideals: 'Vertrag. Ein Handschlag gilt, sonst funktioniert nichts davon.',
    bonds: 'Der Karren meiner Mutter, mit dem sie dreißig Jahre über die Steppe fuhr. Er steht noch bei mir.',
    flaws: 'Wenn die Magie in mir hochkommt, tue ich Dinge, für die ich mich hinterher entschuldigen muss.',
    backstory:
      'Ghorza wuchs auf einem Handelskarren auf und lernte rechnen, bevor sie sprechen konnte. Mit neunzehn schlug ein Blitz in den Karren, tötete das Zugtier und ließ sie unversehrt zurück – mit etwas im Blut, das seither knistert, wenn sie sich aufregt. Ihre Mutter starb ein Jahr später, und Ghorza fährt weiter, verkauft, was sie findet, und sucht nach jemandem, der ihr erklären kann, was der Blitz in ihr gelassen hat.',
    look: 'Groß, breit, mit einem Lächeln, das gleichzeitig freundlich und geschäftlich ist. Bei Aufregung stehen ihr die Haare buchstäblich ab.',
    allies: 'Die Steppenhändler vom Langen Weg, die ihren Namen kennen und ihr Kredit geben.',
  },
};
