/**
 * Wörterbuch: was der Browser anbietet – das Dokument, das Fenster, der
 * lokale Speicher, Ereignisse, Dateien, Zeichenflächen.
 *
 * Das gilt nur für die Oberfläche (frontend/): Der Server läuft in Node und
 * kennt weder `document` noch `window`.
 */

/** `objekt.methode` bzw. `objekt.eigenschaft` → was es tut. */
export const BROWSER = {
  'document.createElement': 'legt ein neues HTML-Element an (noch nicht auf der Seite)',
  'document.getElementById': 'sucht das Element mit dieser id auf der Seite',
  'document.querySelector': 'sucht das erste Element, das zum CSS-Selektor passt',
  'document.querySelectorAll': 'sucht alle Elemente, die zum CSS-Selektor passen',
  'document.addEventListener': 'meldet eine Funktion für ein Ereignis der ganzen Seite an',
  'document.removeEventListener': 'meldet die Funktion für das Ereignis wieder ab',
  'document.documentElement': 'das <html>-Element – die Wurzel der Seite',
  'document.body': 'das <body>-Element',
  'document.title': 'der Titel im Browser-Tab',
  'document.adoptedStyleSheets': 'die Stilblätter, die das Dokument zusätzlich übernommen hat (aus JavaScript angelegt)',
  'document.visibilityState': 'ob die Seite gerade zu sehen ist (visible) oder im Hintergrund liegt (hidden)',
  'document.hidden': 'ob die Seite gerade im Hintergrund liegt',
  'window.addEventListener': 'meldet eine Funktion für ein Ereignis des Fensters an',
  'window.removeEventListener': 'meldet die Funktion für das Ereignis wieder ab',
  'window.confirm': 'fragt mit einem Dialog „OK / Abbrechen“ nach; liefert wahr bei OK',
  'window.alert': 'zeigt eine Meldung in einem Dialog',
  'window.location': 'die Adresse der Seite (zum Lesen oder Umleiten)',
  'window.matchMedia': 'prüft eine Medienabfrage (etwa: bevorzugt das Gerät dunkle Farben?)',
  'window.open': 'öffnet ein neues Fenster bzw. einen neuen Tab',
  'window.scrollTo': 'rollt die Seite an eine Stelle',
  'window.innerWidth': 'die Breite des Fensters in Pixeln',
  'window.innerHeight': 'die Höhe des Fensters in Pixeln',
  'window.getComputedStyle': 'liefert das tatsächliche Aussehen eines Elements, wie der Browser es berechnet hat',
  'window.requestAnimationFrame': 'führt eine Funktion vor dem nächsten Bild aus, das der Bildschirm zeigt',
  requestAnimationFrame: 'führt eine Funktion vor dem nächsten Bild aus, das der Bildschirm zeigt (für flüssige Bewegung)',
  cancelAnimationFrame: 'bricht einen geplanten requestAnimationFrame-Aufruf ab',
  confirm: 'fragt mit einem Dialog „OK / Abbrechen“ nach; liefert wahr bei OK',
  alert: 'zeigt eine Meldung in einem Dialog',
  'localStorage.getItem': 'liest einen Wert aus dem lokalen Speicher des Browsers (bleibt auch nach dem Schließen erhalten)',
  'localStorage.setItem': 'legt einen Wert im lokalen Speicher des Browsers ab',
  'localStorage.removeItem': 'entfernt einen Wert aus dem lokalen Speicher',
  'sessionStorage.getItem': 'liest einen Wert aus dem Speicher dieses Tabs',
  'sessionStorage.setItem': 'legt einen Wert im Speicher dieses Tabs ab',
  'navigator.clipboard.writeText': 'legt Text in die Zwischenablage',
  'navigator.serviceWorker': 'der Service Worker – der Teil, der den Almanach offline und installierbar macht',
  'navigator.onLine': 'ob das Gerät gerade Netz hat',
  'navigator.vibrate': 'lässt das Gerät kurz vibrieren',
  'navigator.share': 'öffnet das Teilen-Menü des Geräts',
  EventSource: 'öffnet einen Live-Kanal (Server-Sent Events): eine Verbindung, über die der Server von sich aus Nachrichten schickt',
  FileReader: 'liest eine Datei, die jemand ausgewählt hat',
  readAsDataURL: 'liest die Datei als data:-Adresse (das Bild steckt dann als Text in der Adresse)',
  readAsText: 'liest die Datei als Text',
  Blob: 'ein Klumpen Daten im Speicher (etwa eine Datei, die zum Herunterladen angeboten wird)',
  Image: 'ein Bild-Element, das ohne Seite geladen werden kann (etwa zum Vermessen)',
  'URL.createObjectURL': 'macht aus Daten im Speicher (Blob) eine vorübergehende Adresse, etwa zum Herunterladen',
  'URL.revokeObjectURL': 'gibt eine mit createObjectURL angelegte Adresse wieder frei',
  CSSStyleSheet: 'ein Stilblatt, das JavaScript anlegt und füllt (statt einer .css-Datei)',
  replaceSync: 'ersetzt den ganzen Inhalt des Stilblatts',
  insertRule: 'fügt dem Stilblatt eine Regel hinzu',
  deleteRule: 'entfernt eine Regel aus dem Stilblatt',
  cssRules: 'die Regeln eines Stilblatts',
  getContext: 'holt das Zeichenwerkzeug einer Zeichenfläche (canvas)',
  drawImage: 'malt ein Bild auf die Zeichenfläche',
  toDataURL: 'macht aus der Zeichenfläche ein Bild als data:-Adresse',
  createImageData: 'legt ein leeres Pixelbild an',
  putImageData: 'schreibt Pixel auf die Zeichenfläche',
  getBoundingClientRect: 'liefert Lage und Größe des Elements auf dem Bildschirm (left, top, width, height)',
  setPointerCapture: 'hält den Zeiger an diesem Element fest: Auch wenn Finger oder Maus es verlassen, kommen die Bewegungen hier an',
  releasePointerCapture: 'lässt den festgehaltenen Zeiger wieder los',
  appendChild: 'hängt ein Element als letztes Kind an',
  remove: 'nimmt das Element von der Seite',
  click: 'löst einen Klick auf das Element aus (wie von Hand)',
  focus: 'setzt den Cursor in das Element',
  select: 'markiert den Inhalt des Feldes',
  blur: 'nimmt den Cursor aus dem Element',
  scrollIntoView: 'rollt die Seite, bis das Element zu sehen ist',
  preventDefault: 'verhindert, was der Browser sonst von selbst täte (bei einem Formular: die Seite neu laden)',
  stopPropagation: 'verhindert, dass das Ereignis auch noch bei den umgebenden Elementen ankommt',
  observe: 'beginnt, das Element zu beobachten',
  disconnect: 'beendet das Beobachten',
  ResizeObserver: 'meldet, wenn sich die Größe eines Elements ändert',
  IntersectionObserver: 'meldet, wenn ein Element in den sichtbaren Bereich kommt oder ihn verlässt',
  MutationObserver: 'meldet Änderungen an der Seite',
  getReader: 'öffnet einen Leser für einen Datenstrom, der Stück für Stück liest',
  read: 'liest das nächste Stück aus dem Strom',
  cancel: 'bricht das Lesen ab',
  blob: 'liest die Antwort als Datenklumpen (Blob)',
  text: 'liest die Antwort als Text',
  json: 'liest die Antwort als JSON und macht daraus Objekte',
  writeText: 'legt Text in die Zwischenablage',
};
