/**
 * Wörterbuch: CSS – Eigenschaften, Werte, Selektoren, At-Regeln.
 *
 * CSS beschreibt, wie etwas aussieht. Eine Regel besteht aus einem
 * Selektor (wen sie betrifft: `.btn`, `h1`, `:root`) und Deklarationen in
 * geschweiften Klammern (`color: red;` – Eigenschaft und Wert). Variablen
 * beginnen mit zwei Strichen (`--tinte`) und werden mit `var(--tinte)`
 * gelesen.
 */

/** Eigenschaften: Name → was sie bestimmt. */
export const EIGENSCHAFTEN = {
  color: 'die Schriftfarbe',
  'background-color': 'die Hintergrundfarbe',
  background: 'der Hintergrund (Farbe, Bild, Verlauf – alles in einem)',
  'background-image': 'das Hintergrundbild bzw. der Farbverlauf',
  'background-size': 'die Größe des Hintergrundbilds',
  'background-position': 'die Lage des Hintergrundbilds',
  'background-attachment': 'ob der Hintergrund beim Rollen mitläuft (fixed: steht still)',
  'font-family': 'die Schriftart (mehrere: die erste, die vorhanden ist)',
  'font-size': 'die Schriftgröße',
  'font-weight': 'die Schriftstärke (400 normal, 600 halbfett, 700 fett)',
  'font-style': 'die Schriftlage (italic: kursiv)',
  'font-variant-numeric': 'die Form der Ziffern (tabular-nums: alle gleich breit, damit Spalten stehen)',
  font: 'Schriftlage, -größe und -art in einem',
  'letter-spacing': 'der Abstand zwischen den Buchstaben (Sperrung)',
  'line-height': 'die Zeilenhöhe',
  'text-transform': 'die Schreibung (uppercase: Großbuchstaben)',
  'text-align': 'die Ausrichtung des Texts',
  'text-decoration': 'Unterstreichung bzw. Durchstreichung',
  'text-shadow': 'ein Schatten hinter der Schrift',
  'white-space': 'wie Leerzeichen und Umbrüche behandelt werden',
  'overflow-wrap': 'ob lange Wörter umbrechen dürfen',
  hyphens: 'Silbentrennung (auto: der Browser trennt nach den Regeln der Sprache)',
  'vertical-align': 'die senkrechte Ausrichtung in der Zeile bzw. Tabellenzelle',
  display: 'die Art der Anordnung (block, flex, grid, none …)',
  'flex-direction': 'die Richtung der Flexbox (row: nebeneinander, column: untereinander)',
  'flex-wrap': 'ob die Kinder umbrechen dürfen',
  'flex-grow': 'wie stark das Element wachsen darf, um freien Platz zu füllen',
  'flex-shrink': 'wie stark es schrumpfen darf (0: gar nicht)',
  flex: 'Wachsen, Schrumpfen und Grundgröße in einem',
  'align-items': 'die Ausrichtung der Kinder quer zur Richtung (bei einer Reihe: senkrecht)',
  'justify-content': 'die Verteilung der Kinder entlang der Richtung (bei einer Reihe: waagrecht)',
  gap: 'der Abstand zwischen den Kindern',
  'column-gap': 'der Abstand zwischen den Spalten',
  'grid-template-columns': 'die Spalten des Rasters (fr: Anteil am freien Platz)',
  'grid-column': 'über welche Spalten des Rasters das Element reicht',
  columns: 'der Text läuft in mehreren Spalten',
  width: 'die Breite',
  height: 'die Höhe',
  'min-width': 'die Mindestbreite',
  'min-height': 'die Mindesthöhe',
  'max-width': 'die Höchstbreite',
  'max-height': 'die Höchsthöhe',
  margin: 'der Außenabstand (oben rechts unten links)',
  'margin-top': 'der Außenabstand oben',
  'margin-bottom': 'der Außenabstand unten',
  'margin-left': 'der Außenabstand links',
  'margin-right': 'der Außenabstand rechts',
  padding: 'der Innenabstand (oben rechts unten links)',
  'padding-top': 'der Innenabstand oben',
  'padding-bottom': 'der Innenabstand unten',
  'padding-left': 'der Innenabstand links',
  'padding-right': 'der Innenabstand rechts',
  border: 'der Rahmen (Stärke, Art, Farbe)',
  'border-top': 'der Rahmen oben',
  'border-bottom': 'der Rahmen unten',
  'border-left': 'der Rahmen links',
  'border-right': 'der Rahmen rechts',
  'border-color': 'die Rahmenfarbe',
  'border-bottom-color': 'die Farbe des unteren Rahmens',
  'border-width': 'die Rahmenstärke',
  'border-style': 'die Rahmenart (solid, dashed, dotted)',
  'border-radius': 'die Rundung der Ecken',
  'border-collapse': 'ob Tabellenrahmen zusammenfallen',
  'box-shadow': 'ein Schatten um das Element (inset: nach innen)',
  'box-sizing': 'wie Breite und Höhe gemessen werden (border-box: Rahmen und Innenabstand zählen mit)',
  outline: 'der Umriss (etwa der Fokusrahmen)',
  position: 'die Art der Lage (relative, absolute, fixed, sticky)',
  top: 'der Abstand vom oberen Rand',
  right: 'der Abstand vom rechten Rand',
  bottom: 'der Abstand vom unteren Rand',
  left: 'der Abstand vom linken Rand',
  inset: 'die Abstände zu allen vier Rändern',
  'z-index': 'die Stapelhöhe (größer liegt weiter vorn)',
  overflow: 'was mit Inhalt geschieht, der nicht hineinpasst',
  opacity: 'die Deckkraft (1 ganz, 0 unsichtbar)',
  transform: 'eine Verschiebung, Drehung oder Skalierung',
  'transform-origin': 'der Punkt, um den gedreht bzw. von dem aus skaliert wird',
  cursor: 'die Form des Mauszeigers',
  'pointer-events': 'ob das Element auf die Maus reagiert',
  'touch-action': 'welche Gesten der Browser selbst behandelt',
  'user-select': 'ob Text markiert werden kann',
  appearance: 'ob das eingebaute Aussehen des Browsers gilt',
  '-webkit-appearance': 'ob das eingebaute Aussehen des Browsers gilt (Safari)',
  '-webkit-tap-highlight-color': 'die Farbe des Aufblitzens beim Antippen (Safari)',
  'overscroll-behavior-y': 'was beim Rollen über das Ende hinaus geschieht',
  'image-rendering': 'wie Bilder beim Vergrößern geglättet werden (pixelated: scharfe Pixel)',
  'object-fit': 'wie ein Bild seinen Rahmen füllt',
  'list-style': 'die Art der Aufzählungszeichen',
  'break-inside': 'beim Drucken: ob innerhalb des Elements umbrochen werden darf (avoid: lieber nicht)',
  'break-after': 'beim Drucken: Seitenumbruch nach dem Element',
  'break-before': 'beim Drucken: Seitenumbruch vor dem Element',
  'page-break-after': 'beim Drucken: Seitenumbruch nach dem Element (ältere Schreibweise)',
  page: 'beim Drucken: auf welcher benannten Seitenart das Element steht',
  size: 'beim Drucken: das Papierformat',
  content: 'der Inhalt, den ::before/::after oder ein Seitenrand zeigt',
  fill: 'die Füllfarbe einer Vektorzeichnung',
  stroke: 'die Linienfarbe einer Vektorzeichnung',
  'stroke-width': 'die Linienstärke einer Vektorzeichnung',
  'stroke-dasharray': 'Strich und Lücke einer gestrichelten Linie',
  'paint-order': 'was zuerst gemalt wird – Linie oder Füllung (für Schrift mit Umriss)',
  transition: 'Änderungen gleiten weich (welche Eigenschaft, wie lange)',
  animation: 'eine Animation',
  'accent-color': 'die Farbe von Häkchen und Reglern',
  'scrollbar-width': 'die Breite der Rollbalken',
};

/** Häufige Werte in Worten. */
export const WERTE = {
  flex: 'Flexbox: die Kinder in einer Reihe (oder Spalte)',
  'inline-flex': 'Flexbox im Textfluss',
  grid: 'Raster aus Spalten und Zeilen',
  block: 'als Block',
  'inline-block': 'im Textfluss mit eigener Größe',
  inline: 'im Textfluss',
  none: 'nichts / aus',
  column: 'untereinander',
  row: 'nebeneinander',
  wrap: 'darf umbrechen',
  center: 'mittig',
  'space-between': 'an die Ränder verteilt, Platz dazwischen',
  'flex-start': 'am Anfang',
  'flex-end': 'am Ende',
  baseline: 'an der Grundlinie der Schrift',
  stretch: 'gestreckt',
  absolute: 'frei gesetzt, bezogen auf das nächste umgebende Element mit Lage',
  relative: 'Bezugspunkt für frei gesetzte Kinder',
  fixed: 'am Fenster festgemacht',
  sticky: 'klebt beim Rollen fest',
  hidden: 'versteckt bzw. abgeschnitten',
  auto: 'automatisch',
  uppercase: 'in Großbuchstaben',
  italic: 'kursiv',
  normal: 'normal',
  bold: 'fett',
  solid: 'durchgezogen',
  dashed: 'gestrichelt',
  dotted: 'gepunktet',
  transparent: 'durchsichtig',
  inherit: 'wie das umgebende Element',
  currentColor: 'die aktuelle Schriftfarbe',
  avoid: 'möglichst nicht',
  page: 'immer',
  pointer: 'Hand (anklickbar)',
  'border-box': 'Rahmen und Innenabstand zählen zur Größe',
  pixelated: 'als scharfe Pixel',
  cover: 'füllt den Rahmen (mit Beschnitt)',
  contain: 'passt ganz hinein',
  'pre-wrap': 'Umbrüche wie eingegeben',
  nowrap: 'kein Umbruch',
  collapse: 'zusammenfallend',
};

/** Pseudoklassen und -elemente. */
export const PSEUDO = {
  ':root': 'die Wurzel der Seite (das <html>-Element) – hier stehen Variablen, die überall gelten',
  ':hover': 'wenn die Maus darüber ist',
  ':focus': 'wenn das Element den Fokus hat',
  ':focus-visible': 'wenn das Element per Tastatur fokussiert ist',
  ':active': 'während es gedrückt wird',
  ':disabled': 'wenn es abgeschaltet ist',
  ':checked': 'wenn angehakt',
  ':first-child': 'wenn es das erste Kind ist',
  ':last-child': 'wenn es das letzte Kind ist',
  ':first-of-type': 'das erste seiner Art',
  ':nth-of-type': 'das n-te seiner Art',
  ':not': 'alles außer',
  '::before': 'ein erzeugtes Element vor dem Inhalt',
  '::after': 'ein erzeugtes Element nach dem Inhalt',
  '::placeholder': 'der Platzhaltertext eines Eingabefeldes',
  '::marker': 'das Aufzählungszeichen',
  '::selection': 'markierter Text',
  '::-webkit-scrollbar': 'der Rollbalken (Chrome, Safari)',
  '::-webkit-scrollbar-thumb': 'der Griff des Rollbalkens',
  '::-webkit-scrollbar-track': 'die Bahn des Rollbalkens',
  '::-webkit-inner-spin-button': 'die Pfeile in einem Zahlenfeld (Chrome, Safari)',
  '::-webkit-outer-spin-button': 'die Pfeile in einem Zahlenfeld (Chrome, Safari)',
};

/** At-Regeln: was mit `@` beginnt. */
export const AT_REGELN = {
  '@import': 'lädt ein anderes Stilblatt hinzu',
  '@theme': 'Tailwind v4: legt Farben und Schriften fest, aus denen Tailwind seine Klassen baut (aus --color-ink wird text-ink, bg-ink …)',
  '@layer': 'ordnet die Regeln einer Ebene zu (components: eigene Bausteine – Tailwind-Klassen können sie überstimmen)',
  '@media': 'Regeln, die nur unter einer Bedingung gelten (etwa ab einer Fensterbreite oder beim Drucken)',
  '@page': 'das Druckformat: Papiergröße, Ränder, Seitenzahlen',
  '@top-left': 'der Seitenrand oben links (beim Drucken)',
  '@top-center': 'der Seitenrand oben in der Mitte (beim Drucken)',
  '@bottom-center': 'der Seitenrand unten in der Mitte (beim Drucken) – hier steht die Seitenzahl',
  '@font-face': 'macht eine Schriftdatei unter einem Namen bekannt',
  '@keyframes': 'die Stufen einer Animation',
  '@supports': 'Regeln, die nur gelten, wenn der Browser etwas kann',
  '@custom-variant': 'Tailwind: ein eigener Vorsatz wie dark: oder kerzenlicht:',
  '@utility': 'Tailwind: eine eigene Klasse',
  '@source': 'Tailwind: wo nach Klassen gesucht wird',
  '@plugin': 'Tailwind: lädt eine Erweiterung',
  '@apply': 'Tailwind: übernimmt die Regeln von Tailwind-Klassen',
};

/** Funktionen in Werten. */
export const FUNKTIONEN = {
  var: 'liest eine CSS-Variable (mit Ersatzwert nach dem Komma)',
  calc: 'rechnet mit Maßen (etwa 100% − 2rem)',
  min: 'nimmt den kleinsten der Werte',
  max: 'nimmt den größten der Werte',
  clamp: 'hält einen Wert zwischen einer Unter- und Obergrenze',
  rgba: 'eine Farbe aus Rot, Grün, Blau (0–255) und Deckkraft (0–1)',
  rgb: 'eine Farbe aus Rot, Grün, Blau (0–255)',
  'linear-gradient': 'ein gerader Farbverlauf',
  'radial-gradient': 'ein kreisförmiger Farbverlauf (ein weicher Lichthof)',
  'repeating-linear-gradient': 'ein sich wiederholender Farbverlauf (etwa Streifen)',
  repeat: 'wiederholt eine Spaltenangabe',
  minmax: 'mindestens – höchstens',
  url: 'die Adresse einer Datei',
  env: 'ein Wert des Geräts (safe-area-inset: der Rand, den Notch oder Home-Leiste verdecken)',
  counter: 'ein Zähler (counter(page): die Seitenzahl)',
  translate: 'verschiebt',
  scale: 'vergrößert bzw. verkleinert',
  rotate: 'dreht',
};

/** Einheiten. */
export const EINHEITEN = {
  px: 'Pixel',
  rem: 'Vielfaches der Grundschriftgröße (1 rem = 16 px)',
  em: 'Vielfaches der aktuellen Schriftgröße',
  '%': 'Prozent des umgebenden Elements',
  vh: 'Prozent der Fensterhöhe',
  vw: 'Prozent der Fensterbreite',
  mm: 'Millimeter (für den Druck)',
  pt: 'Punkt (1/72 Zoll, für den Druck)',
  fr: 'Anteil am freien Platz (im Raster)',
  deg: 'Grad',
  s: 'Sekunden',
  ms: 'Millisekunden',
};
