/**
 * Wörterbuch: HTML- und SVG-Elemente und ihre Attribute.
 *
 * Gebraucht an zwei Stellen: im JSX der Oberfläche (`<button …>` ist dort
 * ein echtes HTML-Element, `<Wurfknopf …>` eine Komponente) und in den
 * HTML-Dateien selbst (frontend/index.html, die Entwürfe in design/, die
 * erzeugten Seiten des Drucksatzes).
 */

/** Elemente: Name → was es ist. */
export const ELEMENTE = {
  html: 'die Wurzel der Seite',
  head: 'der Kopf: Angaben über die Seite, die nicht selbst zu sehen sind',
  body: 'der Körper: alles, was auf der Seite zu sehen ist',
  meta: 'eine Angabe über die Seite',
  title: 'der Titel im Browser-Tab',
  link: 'ein Verweis auf eine zugehörige Datei (Stilblatt, Symbol, Manifest)',
  script: 'ein Skript',
  style: 'eingebettetes Stilblatt',
  noscript: 'Inhalt nur für Browser ohne JavaScript',
  template: 'eine Vorlage: Inhalt, den der Browser nicht anzeigt',
  div: 'ein Kasten – das allgemeine Block-Element',
  span: 'ein Stück im Textfluss – das allgemeine Element innerhalb einer Zeile',
  p: 'ein Absatz',
  a: 'ein Verweis (Link)',
  button: 'eine Schaltfläche',
  input: 'ein Eingabefeld',
  label: 'eine Beschriftung zu einem Eingabefeld (ein Klick darauf setzt den Cursor ins Feld)',
  select: 'eine Auswahlliste',
  option: 'ein Eintrag einer Auswahlliste',
  textarea: 'ein mehrzeiliges Textfeld',
  form: 'ein Formular (die Eingabetaste schickt es ab)',
  fieldset: 'eine Gruppe von Eingabefeldern',
  legend: 'die Überschrift einer Feldgruppe',
  datalist: 'eine Liste von Vorschlägen für ein Eingabefeld',
  ul: 'eine Aufzählung (ungeordnet)',
  ol: 'eine nummerierte Aufzählung',
  li: 'ein Eintrag einer Aufzählung',
  dl: 'eine Begriffsliste',
  dt: 'ein Begriff einer Begriffsliste',
  dd: 'die Erklärung zu einem Begriff',
  section: 'ein Abschnitt',
  article: 'ein in sich geschlossener Beitrag',
  header: 'ein Kopfbereich',
  footer: 'ein Fußbereich',
  main: 'der Hauptinhalt der Seite',
  nav: 'eine Navigation',
  aside: 'ein Randbereich',
  h1: 'eine Überschrift der ersten Ebene',
  h2: 'eine Überschrift der zweiten Ebene',
  h3: 'eine Überschrift der dritten Ebene',
  h4: 'eine Überschrift der vierten Ebene',
  h5: 'eine Überschrift der fünften Ebene',
  h6: 'eine Überschrift der sechsten Ebene',
  img: 'ein Bild',
  b: 'fett gesetzter Text',
  strong: 'stark betonter Text',
  em: 'betonter (kursiver) Text',
  i: 'kursiver Text',
  small: 'kleiner gesetzter Text',
  br: 'ein Zeilenumbruch',
  hr: 'eine waagrechte Trennlinie',
  table: 'eine Tabelle',
  thead: 'der Kopf einer Tabelle',
  tbody: 'der Rumpf einer Tabelle',
  tr: 'eine Tabellenzeile',
  th: 'eine Kopfzelle',
  td: 'eine Tabellenzelle',
  colgroup: 'die Spaltenangaben einer Tabelle',
  col: 'eine Spalte',
  pre: 'vorformatierter Text (Leerzeichen und Umbrüche bleiben stehen)',
  code: 'Code im Text',
  q: 'ein Zitat im Text',
  blockquote: 'ein abgesetztes Zitat',
  figure: 'eine Abbildung',
  figcaption: 'die Bildunterschrift',
  details: 'ein aufklappbarer Bereich',
  summary: 'die Überschrift eines aufklappbaren Bereichs',
  canvas: 'eine Zeichenfläche, auf die JavaScript malt',
  video: 'ein Video',
  audio: 'ein Tonstück',
  iframe: 'eine eingebettete fremde Seite',
  nobr: 'Text ohne Umbruch',
  svg: 'eine Vektorzeichnung (SVG) – skaliert ohne Unschärfe',
  path: 'ein Zeichenpfad der Vektorzeichnung',
  circle: 'ein Kreis der Vektorzeichnung',
  rect: 'ein Rechteck der Vektorzeichnung',
  line: 'eine Linie der Vektorzeichnung',
  polyline: 'ein Linienzug der Vektorzeichnung',
  polygon: 'ein Vieleck der Vektorzeichnung',
  ellipse: 'eine Ellipse der Vektorzeichnung',
  g: 'eine Gruppe in der Vektorzeichnung',
  defs: 'Vorlagen der Vektorzeichnung, die selbst nicht gezeichnet werden',
  use: 'eine Wiederholung einer Vorlage der Vektorzeichnung',
  text: 'Text in der Vektorzeichnung',
  tspan: 'ein Stück Text in der Vektorzeichnung',
  lineargradient: 'ein Farbverlauf der Vektorzeichnung',
  stop: 'ein Farbpunkt eines Verlaufs',
};

/** Attribute in HTML-Dateien (in JSX gelten die Namen aus react.mjs). */
export const HTML_ATTRIBUTE = {
  lang: 'die Sprache der Seite (de: Deutsch) – für Silbentrennung und Vorleseprogramme',
  charset: 'die Zeichenkodierung (utf-8: alle Zeichen, auch Umlaute)',
  name: 'der Name der Angabe bzw. des Feldes',
  content: 'der Wert der Angabe',
  rel: 'die Art des Verweises',
  href: 'das Ziel des Verweises',
  src: 'die Adresse der Datei',
  type: 'die Art des Inhalts bzw. Feldes',
  class: 'die CSS-Klassen des Elements – sie bestimmen über das Stilblatt sein Aussehen',
  id: 'eine eindeutige Kennung auf der Seite',
  title: 'Hinweistext beim Darüberfahren',
  alt: 'Ersatztext eines Bildes',
  width: 'die Breite',
  height: 'die Höhe',
  'http-equiv': 'eine Angabe, die wie eine Kopfzeile des Servers wirkt',
  sizes: 'für welche Größen das Symbol gedacht ist',
  media: 'für welche Bildschirme die Angabe gilt',
  crossorigin: 'wie Dateien von anderen Adressen geladen werden',
  defer: 'das Skript erst ausführen, wenn die Seite gelesen ist',
  async: 'das Skript ausführen, sobald es geladen ist',
  role: 'die Rolle für Vorleseprogramme',
  hidden: 'ausgeblendet',
  tabindex: 'Reihenfolge beim Springen mit der Tab-Taste',
  for: 'zu welchem Eingabefeld die Beschriftung gehört',
  value: 'der Wert',
  placeholder: 'Hinweistext im leeren Feld',
  disabled: 'abgeschaltet',
  colspan: 'über wie viele Spalten die Zelle reicht',
  rowspan: 'über wie viele Zeilen die Zelle reicht',
  viewBox: 'das Koordinatensystem der Zeichnung (x y Breite Höhe)',
  viewbox: 'das Koordinatensystem der Zeichnung (x y Breite Höhe)',
  xmlns: 'der Namensraum (bei SVG: dies ist eine Zeichnung)',
  d: 'der Zeichenpfad: Befehle wie M (gehe zu), L (Linie), C (Kurve), A (Bogen), Z (schließen)',
  fill: 'die Füllfarbe (none: ungefüllt)',
  stroke: 'die Linienfarbe',
  'stroke-width': 'die Linienstärke',
  'stroke-linecap': 'die Form der Linienenden',
  'stroke-linejoin': 'die Form der Ecken',
  'stroke-dasharray': 'Strich- und Lückenlänge einer gestrichelten Linie',
  cx: 'die x-Koordinate des Mittelpunkts',
  cy: 'die y-Koordinate des Mittelpunkts',
  r: 'der Radius',
  x: 'die x-Koordinate',
  y: 'die y-Koordinate',
  points: 'die Eckpunkte',
  transform: 'eine Verschiebung, Drehung oder Skalierung',
  'aria-hidden': 'für Vorleseprogramme ausgeblendet (nur Schmuck)',
  'aria-label': 'Beschriftung für Vorleseprogramme',
  'data-theme': 'eigenes Datenattribut: welche Farbfassung gilt (kerzenlicht = dunkel)',
};

/** Was eine `<meta name="…">`-Angabe bedeutet. */
export const META = {
  viewport: 'wie die Seite auf Telefon und Tablet skaliert: width=device-width nimmt die echte Breite des Geräts, initial-scale=1 zeigt sie ohne Zoom',
  'theme-color': 'die Farbe, in der Browser und installierte App ihre Leiste einfärben',
  description: 'eine Kurzbeschreibung der Seite',
  'apple-mobile-web-app-capable': 'auf dem iPad als eigenständige App (ohne Adressleiste) starten, wenn sie zum Home-Bildschirm hinzugefügt wurde',
  'apple-mobile-web-app-status-bar-style': 'wie die Statusleiste des iPad über der App aussieht',
  'apple-mobile-web-app-title': 'der Name unter dem Symbol auf dem Home-Bildschirm',
  'mobile-web-app-capable': 'als eigenständige App starten, wenn installiert',
  robots: 'ob Suchmaschinen die Seite aufnehmen dürfen',
  'color-scheme': 'welche Farbfassungen (hell, dunkel) die Seite kann',
};

/** Was ein `<link rel="…">` bedeutet. */
export const LINK = {
  stylesheet: 'bindet ein Stilblatt ein (das Aussehen der Seite)',
  icon: 'das Symbol der Seite im Browser-Tab',
  'apple-touch-icon': 'das Symbol auf dem Home-Bildschirm von iPad und iPhone',
  manifest: 'das Manifest: Name, Symbole und Farben, mit denen sich der Almanach als App installieren lässt',
  preconnect: 'baut die Verbindung zu einem anderen Rechner schon vorab auf',
  preload: 'lädt eine Datei schon vorab, weil sie gleich gebraucht wird',
};
