/**
 * Wörterbuch: Node, seine eingebauten Module und Express.
 *
 * Node ist das Programm, das JavaScript außerhalb des Browsers ausführt –
 * hier: den Server und die Werkzeuge in scripts/. Seine Module beginnen mit
 * `node:` (`node:fs` für Dateien, `node:path` für Pfade …). Express ist das
 * Paket, mit dem der Server Anfragen entgegennimmt und beantwortet: Ein
 * „Weg“ (Route) verbindet eine Methode und einen Pfad (`GET /api/health`)
 * mit einer Funktion, die die Antwort schreibt.
 */

/** Was ein Modul ist – für die Zeile, die es einführt. */
export const MODULE = {
  'node:fs': 'Node-Modul für Dateien und Ordner (lesen, schreiben, anlegen, löschen)',
  'node:fs/promises': 'Node-Modul für Dateien – in der asynchronen Fassung mit Zusagen',
  'node:path': 'Node-Modul für Pfade (zusammensetzen, zerlegen – mit dem richtigen Trennzeichen für jedes Betriebssystem)',
  'node:url': 'Node-Modul für Adressen (etwa: aus file:///… einen Pfad machen)',
  'node:crypto': 'Node-Modul für Kryptographie: Zufall, Prüfsummen, Schlüssel, Signaturen',
  'node:child_process': 'Node-Modul zum Starten anderer Programme',
  'node:os': 'Node-Modul mit Angaben zum Rechner (Name, Netzwerkadressen, Ordner für Vorübergehendes)',
  'node:module': 'Node-Modul rund ums Laden von Modulen',
  'node:util': 'Node-Modul mit Hilfsfunktionen',
  'node:http': 'Node-Modul für einen Webserver (HTTP)',
  'node:https': 'Node-Modul für einen verschlüsselten Webserver (HTTPS)',
  'node:sqlite': 'Node-Modul für SQLite-Datenbanken (seit Node 22 eingebaut – kein Paket, kein Compiler nötig)',
  'node:events': 'Node-Modul für Ereignisse',
  'node:stream': 'Node-Modul für Datenströme',
  'node:readline': 'Node-Modul zum zeilenweisen Lesen (etwa von Eingaben im Terminal)',
  'node:test': 'Node-Modul für Tests',
  'node:assert': 'Node-Modul für Prüfungen in Tests',
  express: 'Express – das Paket, mit dem der Server Anfragen annimmt, an Wege verteilt und beantwortet',
  react: 'React – die Bibliothek für die Oberfläche (Komponenten, Zustand, Hooks)',
  'react-dom/client': 'React DOM – bringt die React-Oberfläche in die echte HTML-Seite',
  'react-router-dom': 'React Router – verbindet die Adresse im Browser mit den Seiten der Oberfläche',
  vite: 'Vite – das Bauwerkzeug der Oberfläche (Entwicklungsserver und Bau der fertigen Dateien)',
  '@vitejs/plugin-react': 'die React-Erweiterung für Vite (übersetzt JSX, lädt Änderungen ohne Neuladen)',
  '@tailwindcss/vite': 'die Tailwind-Erweiterung für Vite (erzeugt die CSS-Klassen, die im Code vorkommen)',
  'vite-plugin-pwa': 'die PWA-Erweiterung für Vite: macht den Almanach installierbar wie eine App (Service Worker, Manifest)',
};

/** Funktionen der Node-Module und Methoden ihrer Objekte: `Name` oder `objekt.methode`. */
export const NODE = {
  'fs.readFileSync': 'liest eine Datei vollständig (mit "utf8": als Text)',
  'fs.writeFileSync': 'schreibt eine Datei (eine vorhandene wird überschrieben)',
  'fs.appendFileSync': 'hängt Text an eine Datei an',
  'fs.existsSync': 'prüft, ob es die Datei bzw. den Ordner gibt',
  'fs.mkdirSync': 'legt einen Ordner an (mit recursive: true samt aller fehlenden Zwischenordner)',
  'fs.mkdtempSync': 'legt einen neuen, leeren Ordner mit zufälligem Namen an (für Vorübergehendes)',
  'fs.rmSync': 'löscht eine Datei oder einen Ordner (force: kein Fehler, wenn es ihn nicht gibt)',
  'fs.unlinkSync': 'löscht eine Datei',
  'fs.readdirSync': 'liefert die Einträge eines Ordners',
  'fs.statSync': 'liefert Angaben zu einer Datei (Größe, Änderungszeit, ob Ordner)',
  'fs.copyFileSync': 'kopiert eine Datei',
  'fs.cpSync': 'kopiert eine Datei oder einen ganzen Ordner',
  'fs.renameSync': 'benennt um bzw. verschiebt – in einem Schritt (ganz oder gar nicht)',
  'fs.createWriteStream': 'öffnet eine Datei zum fortlaufenden Schreiben',
  'fs.createReadStream': 'öffnet eine Datei zum fortlaufenden Lesen',
  'fs.watch': 'beobachtet eine Datei auf Änderungen',
  'path.join': 'setzt Pfadstücke mit dem richtigen Trennzeichen zusammen (/ oder \\)',
  'path.resolve': 'macht aus Pfadstücken einen vollständigen (absoluten) Pfad',
  'path.dirname': 'liefert den Ordner, in dem eine Datei liegt',
  'path.basename': 'liefert den Dateinamen ohne Ordner',
  'path.extname': 'liefert die Endung eines Dateinamens (.js)',
  'path.relative': 'liefert den Weg von einem Pfad zum anderen',
  'path.isAbsolute': 'prüft, ob ein Pfad vollständig (absolut) ist',
  'path.sep': 'das Trennzeichen für Pfade auf diesem Rechner (/ bzw. \\)',
  fileURLToPath: 'macht aus einer Adresse file:///… einen gewöhnlichen Pfad',
  pathToFileURL: 'macht aus einem Pfad eine Adresse file:///…',
  randomUUID: 'erzeugt eine zufällige, weltweit eindeutige Kennung (UUID)',
  'crypto.randomUUID': 'erzeugt eine zufällige, weltweit eindeutige Kennung (UUID)',
  randomBytes: 'erzeugt kryptographisch sichere Zufallsbytes',
  'crypto.randomBytes': 'erzeugt kryptographisch sichere Zufallsbytes',
  randomInt: 'würfelt eine sichere Zufallszahl im angegebenen Bereich',
  'crypto.randomInt': 'würfelt eine sichere Zufallszahl im angegebenen Bereich',
  scrypt: 'leitet aus einem Kennwort einen Schlüssel ab – absichtlich langsam, damit Raten teuer wird',
  timingSafeEqual: 'vergleicht zwei Bytefolgen in immer gleicher Zeit – so verrät die Dauer nicht, ab welcher Stelle sie sich unterscheiden',
  createHash: 'beginnt eine Prüfsumme (etwa SHA-256); mit .update(…) füttern, mit .digest(…) ablesen',
  'crypto.createHash': 'beginnt eine Prüfsumme (etwa SHA-256); mit .update(…) füttern, mit .digest(…) ablesen',
  'crypto.generateKeyPairSync': 'erzeugt ein Schlüsselpaar (privat und öffentlich)',
  'crypto.createPrivateKey': 'liest einen privaten Schlüssel ein',
  'crypto.sign': 'unterschreibt Daten mit einem privaten Schlüssel',
  'crypto.X509Certificate': 'liest ein Zertifikat ein, um es zu prüfen',
  createRequire: 'baut eine require-Funktion, mit der ein ES-Modul Pakete auf die ältere Art laden kann',
  promisify: 'macht aus einer Funktion mit Rückruf eine, die eine Zusage (Promise) liefert – damit geht await',
  spawn: 'startet ein anderes Programm und lässt es neben dem eigenen weiterlaufen',
  spawnSync: 'startet ein anderes Programm und wartet, bis es fertig ist',
  execSync: 'führt einen Befehl in der Kommandozeile aus und wartet auf das Ergebnis',
  execFileSync: 'führt ein Programm aus und wartet auf das Ergebnis',
  'os.networkInterfaces': 'liefert die Netzwerkanschlüsse des Rechners samt ihrer Adressen',
  'os.hostname': 'liefert den Namen des Rechners im Netz',
  'os.tmpdir': 'liefert den Ordner für vorübergehende Dateien',
  'os.homedir': 'liefert den Benutzerordner',
  'os.platform': 'liefert das Betriebssystem (win32, darwin, linux)',
  'process.exit': 'beendet das Programm sofort (0 heißt: alles in Ordnung, alles andere: Fehler)',
  'process.argv': 'die Angaben, mit denen das Programm in der Kommandozeile gestartet wurde',
  'process.env': 'die Umgebungsvariablen – Einstellungen, die von außen mitgegeben werden',
  'process.on': 'meldet eine Funktion für ein Ereignis des Programms an (etwa SIGINT: Strg+C)',
  'process.cwd': 'liefert den Ordner, aus dem das Programm gestartet wurde',
  'process.platform': 'das Betriebssystem (win32, darwin, linux)',
  'process.getuid': 'liefert die Benutzerkennung (0 ist root)',
  'process.loadEnvFile': 'liest eine .env-Datei und übernimmt ihre Zeilen als Umgebungsvariablen',
  'process.stdout.write': 'schreibt Text ins Terminal, ohne neue Zeile',
  'process.emitWarning': 'gibt eine Warnung von Node aus',
  'process.nextTick': 'führt eine Funktion aus, sobald der laufende Code fertig ist',
  createServer: 'legt einen Webserver an, der jede Anfrage an die angegebene Funktion (oder Express-App) gibt',
  DatabaseSync: 'öffnet eine SQLite-Datenbank (die Datei wird angelegt, wenn es sie noch nicht gibt); alle Aufrufe warten auf ihr Ergebnis',
};

/** Express und seine Objekte: `app`, `router`, `req` (Anfrage), `res` (Antwort). */
export const EXPRESS = {
  express: 'legt die Express-Anwendung an – den Server, an den alle Wege gehängt werden',
  'express.json': 'Zwischenschritt, der JSON im Rumpf einer Anfrage liest und als `req.body` bereitstellt',
  'express.static': 'Zwischenschritt, der Dateien aus einem Ordner unverändert ausliefert (die gebaute Oberfläche)',
  'express.Router': 'legt einen Router an: eine Gruppe von Wegen, die gemeinsam irgendwo eingehängt wird',
  Router: 'legt einen Router an: eine Gruppe von Wegen, die gemeinsam irgendwo eingehängt wird',
  use: 'hängt einen Zwischenschritt (Middleware) oder Router ein – er läuft für jede passende Anfrage, bevor die Wege dahinter drankommen',
  listen: 'startet den Server: Er lauscht ab jetzt auf dem angegebenen Port',
  'req.params': 'die Platzhalter aus dem Pfad (aus /characters/:id wird req.params.id)',
  'req.body': 'der Rumpf der Anfrage – das, was die Oberfläche mitgeschickt hat (als JSON gelesen)',
  'req.query': 'die Parameter hinter dem ? in der Adresse',
  'req.headers': 'die Kopfzeilen der Anfrage',
  'req.user': 'die angemeldete Person – eingetragen von der Anmeldeprüfung (auth.js)',
  'req.ip': 'die Netzwerkadresse, von der die Anfrage kommt',
  'req.get': 'liest eine Kopfzeile der Anfrage',
  'req.on': 'meldet eine Funktion für ein Ereignis der Anfrage an (close: die Verbindung wurde getrennt)',
  'res.status': 'setzt den Statuscode der Antwort',
  'res.json': 'schickt die Antwort als JSON und beendet sie',
  'res.send': 'schickt die Antwort und beendet sie',
  'res.sendFile': 'schickt eine Datei als Antwort',
  'res.sendStatus': 'antwortet nur mit einem Statuscode',
  'res.setHeader': 'setzt eine Kopfzeile der Antwort',
  'res.set': 'setzt Kopfzeilen der Antwort',
  'res.append': 'fügt einer Kopfzeile der Antwort einen weiteren Wert hinzu',
  'res.type': 'setzt die Art des Inhalts (Content-Type)',
  'res.end': 'beendet die Antwort',
  'res.write': 'schreibt ein Stück der Antwort, ohne sie zu beenden (für den Live-Kanal)',
  'res.writeHead': 'schreibt Status und Kopfzeilen sofort',
  'res.flushHeaders': 'schickt die Kopfzeilen sofort ab, ohne auf den Rumpf zu warten',
  'res.on': 'meldet eine Funktion für ein Ereignis der Antwort an (close: Verbindung getrennt)',
  next: 'gibt die Anfrage an den nächsten Schritt weiter (mit einem Fehler als Argument: an die Fehlerbehandlung)',
};

/** Statuscodes einer Antwort – was sie bedeuten. */
export const STATUS = {
  200: 'OK – alles in Ordnung',
  201: 'Created – angelegt',
  204: 'No Content – erledigt, es gibt nichts zurückzugeben',
  301: 'dauerhaft umgezogen',
  302: 'vorübergehend woanders',
  304: 'unverändert – der Browser darf seine Kopie nehmen',
  400: 'Bad Request – die Anfrage ist fehlerhaft, etwa weil ein Feld fehlt oder falsch ist',
  401: 'Unauthorized – nicht angemeldet',
  403: 'Forbidden – angemeldet, aber nicht berechtigt',
  404: 'Not Found – gibt es nicht',
  405: 'diese Methode ist hier nicht erlaubt',
  409: 'Conflict – widerspricht dem, was schon da ist (etwa ein vergebener Name)',
  410: 'Gone – gab es, gibt es nicht mehr',
  413: 'Payload Too Large – zu groß',
  415: 'falsche Art von Inhalt',
  422: 'Unprocessable – verstanden, aber inhaltlich nicht machbar',
  423: 'Locked – gesperrt',
  429: 'Too Many Requests – zu viele Versuche in kurzer Zeit',
  500: 'Internal Server Error – auf dem Server ist etwas schiefgegangen',
  502: 'Bad Gateway – eine Stelle dahinter hat falsch geantwortet',
  503: 'Service Unavailable – gerade nicht verfügbar',
  504: 'Gateway Timeout – eine Stelle dahinter hat nicht rechtzeitig geantwortet',
};

/** Methoden einer vorbereiteten SQL-Anweisung (node:sqlite). */
export const SQLITE = {
  prepare: 'bereitet eine SQL-Anweisung vor; die ? darin sind Platzhalter, die beim Ausführen der Reihe nach gefüllt werden – so kann kein Wert die Anweisung verändern (Schutz vor SQL-Einschleusung)',
  exec: 'führt SQL direkt aus (auch mehrere Anweisungen hintereinander), ohne Platzhalter und ohne Ergebnis',
  get: 'führt die vorbereitete Anweisung aus und liefert die erste passende Zeile als Objekt (oder undefined)',
  all: 'führt die vorbereitete Anweisung aus und liefert alle passenden Zeilen als Liste von Objekten',
  run: 'führt die vorbereitete Anweisung aus, die etwas ändert (INSERT, UPDATE, DELETE); liefert, wie viele Zeilen betroffen waren',
  iterate: 'führt die Anweisung aus und liefert die Zeilen eine nach der anderen',
  close: 'schließt die Datenbank',
};

/** HTTP-Methoden eines Weges. */
export const METHODE = {
  get: 'GET (lesen)',
  post: 'POST (anlegen oder auslösen)',
  put: 'PUT (als Ganzes ersetzen)',
  patch: 'PATCH (einzelne Felder ändern)',
  delete: 'DELETE (löschen)',
};
