/**
 * Zwölf fertige Charaktere, wie sie ein Spieler am Abend vor der ersten
 * Runde angelegt hätte.
 *
 * Jede Klasse kommt genau einmal vor, jede Spezies genau einmal – die zehn
 * aus dem Regelwerk von 2024, dazu Halbelf und Halbork aus dem älteren Buch,
 * damit auch die beiden nicht fehlen. Alle stehen auf Stufe 1 und tragen die
 * Startausrüstung ihrer Klasse und ihres Hintergrunds.
 *
 * Gebaut sind sie nach dem Standardwertesatz (15, 14, 13, 12, 10, 8), auf den
 * der Hintergrund nach den Regeln von 2024 noch +2 und +1 legt. Halbelf und
 * Halbork bekommen deshalb keine eigenen Attributsboni, sondern nur ihre
 * Eigenschaften – sonst stünden zwei Blätter besser da als die übrigen zehn.
 *
 * Wer eine Vorlage übernehmen will, macht eine Abschrift davon und trägt sich
 * als Spieler ein. Die Vorlage selbst bleibt liegen.
 */

export const HELDEN = [
  /* --- Zwerg · Kämpfer ---------------------------------------------------- */
  {
    schluessel: 'kaempfer-zwerg',
    name: 'Brunhild Erzhammer',
    spezies: 'Zwerg',
    unterart: '',
    klasse: 'Kämpfer',
    hintergrund: 'Wache',
    gesinnung: 'Rechtschaffen Neutral',
    werte: { str: 17, dex: 13, con: 14, int: 10, wis: 13, cha: 8 },
    rettungswuerfe: ['str', 'con'],
    fertigkeiten: ['athletics', 'perception', 'insight', 'intimidation'],
    ruestungsklasse: 17,
    // Wachsam legt den Übungsbonus auf die Initiative.
    initiativeBonus: 2,
    trefferpunkte: 13,
    trefferwuerfel: '1d10',
    bewegung: 30,
    sinne: { darkvision: 120, notes: 'Steinkunde: Erschütterungssinn 18 m auf Stein, als Bonusaktion' },
    verteidigung: { resistances: 'Gift' },
    rettungswurfVermerk: 'Vorteil auf Rettungswürfe gegen Gift (Zwergenwiderstand).',
    uebungen: {
      armor: 'Leichte, mittlere und schwere Rüstung, Schilde',
      weapons: 'Einfache Waffen, Kriegswaffen',
      tools: 'Schmiedewerkzeug, Würfelset',
      languages: 'Gemeinsprache, Zwergisch',
    },
    angriffe: [
      { name: 'Zweihänder', bonus: '+5', damage: '2W6+3 Hieb', notes: 'Schwer, Zweihändig · Meisterschaft: Streifen' },
      { name: 'Dreschflegel', bonus: '+5', damage: '1W8+3 Wucht', notes: 'Meisterschaft: Zermürben' },
      { name: 'Wurfspeer', bonus: '+5', damage: '1W6+3 Stich', notes: 'Wurf 9/36 m · Meisterschaft: Verlangsamen' },
    ],
    aktionen: [
      {
        name: 'Zweiter Wind',
        art: 'bonus',
        description: 'Du erhältst 1W10+1 Trefferpunkte zurück. Zweimal, dann brauchst du eine Rast.',
      },
      {
        name: 'Steinkunde',
        art: 'bonus',
        description: 'Bis zum Ende deines nächsten Zuges nimmst du 18 m weit alles auf Stein wahr.',
      },
    ],
    ressourcen: [{ name: 'Zweiter Wind', current: 2, max: 2, recharge: 'kurz' }],
    merkmale: [
      {
        name: 'Kampfstil: Verteidigung',
        category: 'klasse',
        source: 'PHB-2024',
        page: '106',
        description: 'Solange du eine Rüstung trägst, steigt deine Rüstungsklasse um 1. (Ist oben eingerechnet.)',
      },
      {
        name: 'Zweiter Wind',
        category: 'klasse',
        source: 'PHB-2024',
        page: '106',
        description:
          'Als Bonusaktion 1W10 + Kämpferstufe Trefferpunkte zurück. Zwei Anwendungen, die sich nach einer Kurzen oder Langen Rast erneuern.',
      },
      {
        name: 'Waffenmeisterschaft',
        category: 'klasse',
        source: 'PHB-2024',
        page: '106',
        description:
          'Drei Waffen: Zweihänder (Streifen – auch bei einem Fehlschlag Schaden in Höhe des Attributsmodifikators), Dreschflegel (Zermürben – das Ziel hat Nachteil auf seinen nächsten Angriff), Wurfspeer (Verlangsamen – 3 m weniger Bewegung).',
      },
      { name: 'Dunkelsicht', category: 'spezies', source: 'PHB-2024', page: '189', description: '36 m weit.' },
      {
        name: 'Zwergenwiderstand',
        category: 'spezies',
        source: 'PHB-2024',
        page: '189',
        description: 'Vorteil auf Rettungswürfe gegen Gift, Resistenz gegen Giftschaden.',
      },
      {
        name: 'Zwergenzähigkeit',
        category: 'spezies',
        source: 'PHB-2024',
        page: '189',
        description: 'Dein Trefferpunktemaximum steigt je Stufe um 1. (Ist oben eingerechnet.)',
      },
      {
        name: 'Steinkunde',
        category: 'spezies',
        source: 'PHB-2024',
        page: '189',
        description: 'Als Bonusaktion Erschütterungssinn 18 m, solange du Stein berührst. Übungsbonus-mal je Lange Rast.',
      },
      {
        name: 'Wachsam',
        category: 'talent',
        source: 'PHB-2024',
        page: '200',
        description:
          'Du addierst deinen Übungsbonus auf die Initiative und darfst deine Initiative mit einem einverstandenen Verbündeten tauschen.',
      },
    ],
    zauber: null,
    ausruestung: [
      { name: 'Kettenpanzer', qty: 1, weight: 55, notes: 'RK 16, Nachteil auf Heimlichkeit' },
      { name: 'Zweihänder', qty: 1, weight: 6, notes: '' },
      { name: 'Dreschflegel', qty: 1, weight: 2, notes: '' },
      { name: 'Wurfspeer', qty: 8, weight: 2, notes: '' },
      { name: 'Speer', qty: 1, weight: 3, notes: 'aus der Torwache' },
      { name: 'Leichte Armbrust', qty: 1, weight: 5, notes: '' },
      { name: 'Bolzen', qty: 20, weight: 0.075, notes: '' },
      { name: 'Köcher', qty: 1, weight: 1, notes: '' },
      { name: 'Jagdfalle', qty: 1, weight: 25, notes: '' },
      { name: 'Handschellen', qty: 1, weight: 6, notes: '' },
      { name: 'Würfelset', qty: 1, weight: 0.5, notes: '' },
      { name: 'Reisekleidung', qty: 1, weight: 4, notes: '' },
      {
        name: 'Höhlenforscherpaket',
        qty: 1,
        weight: 55,
        notes: 'Rucksack, Brecheisen, Hammer, 10 Pitons, Fackeln ×10, Zunderkästchen, Rationen ×10, Wasserschlauch, Seil 15 m',
      },
    ],
    muenzen: { gp: 16 },
    aussehen: {
      gender: 'weiblich',
      age: '74',
      size: 'Mittelgroß',
      height: '137 cm',
      weight: '68 kg',
      faith: 'Moradin',
      skin: 'wettergegerbt',
      eyes: 'grau',
      hair: 'rotbraun, in vier Zöpfen',
    },
    wesen: {
      personality: 'Ich zähle die Ausgänge, sobald ich einen Raum betrete. Das ist keine Angst, das ist Ordnung.',
      ideals: 'Pflicht. Ein Tor, das man mir anvertraut, bleibt zu, bis ich es öffne.',
      bonds: 'Die Bergpforte von Kal Durin fiel in meiner Wache. Ich schulde den Toten dort ein zweites Tor.',
      flaws: 'Wer einmal zu spät zum Dienst kam, bleibt für mich ein Drückeberger.',
      backstory:
        'Vierzig Jahre stand Brunhild an der Bergpforte von Kal Durin, und vierzig Jahre geschah nichts. Dann kam eine Nacht, in der etwas geschah, und am Morgen war das Tor offen, die halbe Wache tot und niemand da, der erklären konnte, wer den Riegel gezogen hatte. Man sprach sie frei; sie selbst tat das nicht. Seither wandert sie und stellt sich vor Türen, hinter denen andere schlafen.',
      look: 'Breit, langsam im Gang und schnell im Blick. Der Kettenpanzer ist an der linken Schulter geflickt – dort, wo in jener Nacht etwas durchkam.',
      allies: 'Was von der Torwache von Kal Durin übrig ist: sieben Namen auf einem Zettel in ihrem Gürtel.',
    },
  },

  /* --- Goliath · Barbar --------------------------------------------------- */
  {
    schluessel: 'barbar-goliath',
    name: 'Kaskar Steinatem',
    spezies: 'Goliath',
    unterart: 'Steingigant-Abstammung',
    klasse: 'Barbar',
    hintergrund: 'Soldat',
    gesinnung: 'Chaotisch Gut',
    werte: { str: 17, dex: 14, con: 14, int: 8, wis: 12, cha: 10 },
    rettungswuerfe: ['str', 'con'],
    fertigkeiten: ['athletics', 'intimidation', 'perception', 'survival'],
    // Ohne Rüstung: 10 + Geschicklichkeit + Konstitution.
    ruestungsklasse: 14,
    initiativeBonus: 0,
    trefferpunkte: 14,
    trefferwuerfel: '1d12',
    bewegung: 35,
    sinne: {},
    verteidigung: { resistances: 'Im Zorn: Wucht, Stich, Hieb' },
    rettungswurfVermerk: 'Im Zorn Vorteil auf Stärke-Rettungswürfe und Stärkeproben.',
    uebungen: {
      armor: 'Leichte und mittlere Rüstung, Schilde',
      weapons: 'Einfache Waffen, Kriegswaffen',
      tools: 'Würfelset',
      languages: 'Gemeinsprache, Riesisch',
    },
    angriffe: [
      { name: 'Doppelaxt', bonus: '+5', damage: '1W12+3 Hieb', notes: 'Schwer, Zweihändig · Meisterschaft: Spalten' },
      { name: 'Handaxt', bonus: '+5', damage: '1W6+3 Hieb', notes: 'Leicht, Wurf 6/18 m · Meisterschaft: Ärgern' },
      { name: 'Unbewaffneter Schlag', bonus: '+5', damage: '4 Wucht', notes: '' },
    ],
    aktionen: [
      {
        name: 'Zorn',
        art: 'bonus',
        description:
          '+2 Schaden im Nahkampf mit Stärke, Resistenz gegen Wucht-, Stich- und Hiebschaden, Vorteil auf Stärkeproben und -rettungswürfe. Hält 10 Minuten. Zweimal je Lange Rast.',
      },
      {
        name: 'Steingigant: Standfest',
        art: 'bonus',
        description: 'Ein Geschöpf in 3 m legt einen Stärke-Rettungswurf gegen SG 13 ab oder wird liegend.',
      },
      {
        name: 'Unbändiger Ansturm',
        art: 'frei',
        description: 'Bei einem Zorn-Ausbruch bewegst du dich zusätzlich, ohne dass es deine Bewegung kostet.',
      },
    ],
    ressourcen: [
      { name: 'Zorn', current: 2, max: 2, recharge: 'lang' },
      { name: 'Riesenkraft (Standfest)', current: 2, max: 2, recharge: 'lang' },
    ],
    merkmale: [
      {
        name: 'Zorn',
        category: 'klasse',
        source: 'PHB-2024',
        page: '50',
        description:
          'Als Bonusaktion. Solange er hält: Vorteil auf Stärkeproben und -rettungswürfe, +2 Schaden im Nahkampf mit Stärke, Resistenz gegen Wucht-, Stich- und Hiebschaden. Keine Rüstung, kein Zaubern.',
      },
      {
        name: 'Ungepanzerte Verteidigung',
        category: 'klasse',
        source: 'PHB-2024',
        page: '50',
        description: 'Ohne Rüstung ist deine Rüstungsklasse 10 + Geschicklichkeit + Konstitution. (Ist oben eingerechnet.)',
      },
      {
        name: 'Waffenmeisterschaft',
        category: 'klasse',
        source: 'PHB-2024',
        page: '50',
        description:
          'Zwei Waffen: Doppelaxt (Spalten – bei einem Treffer ein zweiter Angriff gegen ein zweites Ziel in Reichweite), Handaxt (Ärgern – dein nächster Angriff gegen dasselbe Ziel hat Vorteil).',
      },
      {
        name: 'Riesenabstammung: Steingigant',
        category: 'spezies',
        source: 'PHB-2024',
        page: '193',
        description:
          'Als Bonusaktion zwingst du ein Geschöpf in 3 m zu einem Stärke-Rettungswurf (SG 8 + Übungsbonus + Konstitution) oder es wird liegend.',
      },
      {
        name: 'Kraftvoller Körperbau',
        category: 'spezies',
        source: 'PHB-2024',
        page: '193',
        description: 'Du zählst beim Tragen, Schieben, Ziehen und Heben als eine Größenkategorie größer.',
      },
      {
        name: 'Bewegungsrate',
        category: 'spezies',
        source: 'PHB-2024',
        page: '193',
        description: 'Deine Bewegungsrate beträgt 10,5 m statt 9 m.',
      },
      {
        name: 'Wilder Angreifer',
        category: 'talent',
        source: 'PHB-2024',
        page: '209',
        description: 'Einmal je Zug darfst du die Schadenswürfel eines Waffenangriffs neu würfeln und das bessere Ergebnis nehmen.',
      },
    ],
    zauber: null,
    ausruestung: [
      { name: 'Doppelaxt', qty: 1, weight: 7, notes: '' },
      { name: 'Handaxt', qty: 4, weight: 2, notes: 'zwei am Gürtel, zwei am Rücken' },
      { name: 'Speer', qty: 1, weight: 3, notes: 'aus der Dienstzeit' },
      { name: 'Kurzbogen', qty: 1, weight: 2, notes: '' },
      { name: 'Pfeile', qty: 20, weight: 0.05, notes: '' },
      { name: 'Köcher', qty: 1, weight: 1, notes: '' },
      { name: 'Heilerausrüstung', qty: 1, weight: 3, notes: '10 Anwendungen: Sterbende ohne Wurf stabilisieren' },
      { name: 'Würfelset', qty: 1, weight: 0.5, notes: '' },
      { name: 'Reisekleidung', qty: 1, weight: 4, notes: '' },
      {
        name: 'Entdeckerpaket',
        qty: 1,
        weight: 59,
        notes: 'Rucksack, Schlafrolle, Zunderkästchen, Fackeln ×10, Rationen ×10, Wasserschlauch, Seil 15 m',
      },
    ],
    muenzen: { gp: 29 },
    aussehen: {
      gender: 'männlich',
      age: '31',
      size: 'Mittelgroß',
      height: '221 cm',
      weight: '156 kg',
      faith: 'die Ahnen im Fels',
      skin: 'grausteinfarben, mit dunklen Flecken',
      eyes: 'blassblau',
      hair: 'kahl, mit eingeritzten Linien',
    },
    wesen: {
      personality: 'Ich rede wenig und stelle mich vorn hin. Beides spart Zeit.',
      ideals: 'Die Schwachen zuerst. Wer nicht selbst stehen kann, für den steht man.',
      bonds: 'Meine Truppe schickte mich zurück, damit einer die Namen heimbringt. Ich trage sie noch.',
      flaws: 'Ein Rückzug fühlt sich für mich an wie Verrat, auch wenn er der einzige Ausweg wäre.',
      backstory:
        'Kaskar kam von der Hochebene ins Tal, weil man dort Söldner suchte und Riesen fürchtete – ihn hielt man für beides. Drei Jahre trug er die Fahne einer Grenztruppe, bis ein Pass einstürzte und von zwanzig Leuten er allein zurückkam, weil sie ihn losgeschickt hatten. Er hat den Sold nie abgeholt. Stattdessen geht er jetzt dorthin, wo Leute vorne jemanden brauchen.',
      look: 'Ein Kopf größer als jeder im Raum, mit Linien im Schädel, die von seiner Sippe erzählen. Er lehnt an Wänden, weil Stühle unter ihm ächzen.',
      allies: 'Die Grenztruppe „Zwanzig Steine“ – aufgelöst, und ihre Namen stehen auf seinem Unterarm.',
    },
  },

  /* --- Halbelf · Barde ---------------------------------------------------- */
  {
    schluessel: 'barde-halbelf',
    name: 'Lysandre Abendlied',
    spezies: 'Halbelf',
    unterart: '',
    klasse: 'Barde',
    hintergrund: 'Gaukler',
    gesinnung: 'Chaotisch Gut',
    werte: { str: 8, dex: 14, con: 14, int: 10, wis: 12, cha: 17 },
    rettungswuerfe: ['dex', 'cha'],
    fertigkeiten: ['acrobatics', 'performance', 'persuasion', 'deception', 'insight'],
    expertise: ['performance', 'persuasion'],
    ruestungsklasse: 13,
    initiativeBonus: 0,
    trefferpunkte: 10,
    trefferwuerfel: '1d8',
    bewegung: 30,
    sinne: { darkvision: 60 },
    verteidigung: {},
    rettungswurfVermerk: 'Vorteil auf Rettungswürfe gegen Bezauberung (Feenblut).',
    uebungen: {
      armor: 'Leichte Rüstung',
      weapons: 'Einfache Waffen',
      tools: 'Laute, Blockflöte, Trommel',
      languages: 'Gemeinsprache, Elfisch, Zwergisch',
    },
    angriffe: [
      { name: 'Dolch', bonus: '+4', damage: '1W4+2 Stich', notes: 'Finesse, Leicht, Wurf 6/18 m' },
      { name: 'Bösartiger Spott', bonus: 'SG 13', damage: '1W6 psychisch', notes: 'Weisheit-RW; bei Misslingen Nachteil auf den nächsten Angriff' },
    ],
    aktionen: [
      {
        name: 'Bardische Inspiration',
        art: 'bonus',
        description:
          'Ein Verbündeter in 18 m, der dich hört, erhält einen W6. Er darf ihn binnen 10 Minuten auf einen Wurf addieren – auch nachdem er gewürfelt hat. Dreimal je Lange Rast.',
      },
    ],
    ressourcen: [{ name: 'Bardische Inspiration (W6)', current: 3, max: 3, recharge: 'lang' }],
    merkmale: [
      {
        name: 'Bardische Inspiration',
        category: 'klasse',
        source: 'PHB-2024',
        page: '52',
        description:
          'Als Bonusaktion einem Verbündeten einen W6 geben, den er auf eine Probe, einen Angriff oder einen Rettungswurf addieren darf. Charisma-Modifikator-mal je Lange Rast.',
      },
      {
        name: 'Zauberwirken',
        category: 'klasse',
        source: 'PHB-2024',
        page: '52',
        description: 'Charisma ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5.',
      },
      {
        name: 'Dunkelsicht',
        category: 'spezies',
        source: 'PHB',
        page: '',
        description: '18 m weit – das Erbe der elfischen Seite.',
      },
      {
        name: 'Feenblut',
        category: 'spezies',
        source: 'PHB',
        page: '',
        description: 'Vorteil auf Rettungswürfe gegen Bezauberung, und Magie kann dich nicht schlafen legen.',
      },
      {
        name: 'Vielseitige Begabung',
        category: 'spezies',
        source: 'PHB',
        page: '',
        description: 'Du erhältst Übung in zwei Fertigkeiten deiner Wahl – hier Überzeugen und Motiv erkennen.',
      },
      {
        name: 'Musiker',
        category: 'talent',
        source: 'PHB-2024',
        page: '203',
        description:
          'Nach einer Rast kannst du Übungsbonus-vielen Verbündeten, die zuhören, Heldenhafte Inspiration schenken.',
      },
    ],
    zauber: {
      attribut: 'cha',
      plaetze: { 1: { max: 2, used: 0 } },
      liste: [
        {
          name: 'Bösartiger Spott',
          level: 0,
          prepared: true,
          index: 'vicious-mockery',
          source: 'Barde',
          save: 'WEI-RW',
          time: '1 A',
          range: '18 m',
          components: 'V',
          duration: 'Sofort',
          page: 'PHB-2024 312',
          notes: 'Bei Misslingen 1W6 psychisch und Nachteil auf den nächsten Angriffswurf.',
        },
        {
          name: 'Blendwerk',
          level: 0,
          prepared: true,
          index: 'prestidigitation',
          source: 'Barde',
          save: '--',
          time: '1 A',
          range: '3 m',
          components: 'V, S',
          duration: 'bis 1 Std.',
          page: 'PHB-2024 289',
          notes: 'Das Werkzeug für alles, was kein Kampf ist.',
        },
        {
          name: 'Heilendes Wort',
          level: 1,
          prepared: true,
          index: 'healing-word',
          source: 'Barde',
          save: '--',
          time: '1 BA',
          range: '18 m',
          components: 'V',
          duration: 'Sofort',
          page: 'PHB-2024 268',
          notes: 'Bonusaktion – hebt einen Gefallenen aus 18 m wieder auf die Beine.',
        },
        {
          name: 'Feenfeuer',
          level: 1,
          prepared: true,
          index: 'faerie-fire',
          source: 'Barde',
          save: 'GES-RW',
          time: '1 A',
          range: '18 m',
          components: 'V',
          duration: 'K, 1 Min.',
          page: 'PHB-2024 261',
          notes: 'Würfel 6 m: Angriffe gegen Umrissene haben Vorteil. Der beste erste Zug der Gruppe.',
        },
        {
          name: 'Dissonantes Flüstern',
          level: 1,
          prepared: true,
          index: 'dissonant-whispers',
          source: 'Barde',
          save: 'WEI-RW',
          time: '1 A',
          range: '18 m',
          components: 'V',
          duration: 'Sofort',
          page: 'PHB-2024 259',
          notes: '3W6 psychisch; bei Misslingen flieht das Ziel und löst Gelegenheitsangriffe aus.',
        },
        {
          name: 'Person bezaubern',
          level: 1,
          prepared: true,
          index: 'charm-person',
          source: 'Barde',
          save: 'WEI-RW',
          time: '1 A',
          range: '9 m',
          components: 'V, S',
          duration: '1 Std.',
          page: 'PHB-2024 249',
          notes: 'Außerhalb des Kampfes. Das Ziel weiß hinterher, dass es bezaubert war.',
        },
      ],
    },
    ausruestung: [
      { name: 'Lederrüstung', qty: 1, weight: 10, notes: 'RK 11 + Geschicklichkeit' },
      { name: 'Dolch', qty: 2, weight: 1, notes: '' },
      { name: 'Laute', qty: 1, weight: 2, notes: 'Zauberfokus' },
      { name: 'Kostüm', qty: 2, weight: 4, notes: '' },
      { name: 'Spiegel', qty: 1, weight: 0.5, notes: '' },
      { name: 'Parfüm', qty: 1, weight: 0, notes: '' },
      { name: 'Reisekleidung', qty: 1, weight: 4, notes: '' },
      {
        name: 'Gauklerpaket',
        qty: 1,
        weight: 38,
        notes: 'Rucksack, Schlafrolle, Kostüme ×2, Kerzen ×5, Rationen ×5, Wasserschlauch, Verkleidungsset',
      },
    ],
    muenzen: { gp: 30 },
    aussehen: {
      gender: 'weiblich',
      age: '34',
      size: 'Mittelgroß',
      height: '174 cm',
      weight: '61 kg',
      faith: 'keiner, aber allen freundlich',
      skin: 'hell mit Sommersprossen',
      eyes: 'haselnussbraun, das linke heller',
      hair: 'dunkelblond, kurz geschnitten',
    },
    wesen: {
      personality: 'Ich merke mir jeden Namen beim ersten Hören. Das kostet nichts und öffnet alles.',
      ideals: 'Freiheit. Ein Lied gehört niemandem, und ein Mensch auch nicht.',
      bonds: 'Die Truppe, die mich aufnahm, als beide Elternhäuser mich nicht wollten. Sie ist auseinander – ich suche sie.',
      flaws: 'Ich verspreche im Rausch des Auftritts Dinge, an die ich mich am Morgen nur ungefähr erinnere.',
      backstory:
        'Zu elfisch für das Dorf, zu menschlich für den Hain – Lysandre hörte das, bevor sie lesen konnte. Mit vierzehn hängte sie sich an eine fahrende Truppe, die keine Fragen stellte, und lernte dort, dass ein Publikum nicht wissen will, woher jemand kommt, sondern nur, ob er es kann. Als die Truppe nach einem schlechten Winter auseinanderfiel, blieb ihr die Laute und die Liste der Orte, an denen die anderen zuletzt gesehen wurden.',
      look: 'Auffällig gekleidet, aber immer beweglich. Spricht mit den Händen und hört mit dem ganzen Gesicht zu.',
      allies: 'Die fahrende Truppe „Sieben Fenster“ – zerstreut über vier Städte.',
    },
  },

  /* --- Aasimar · Kleriker -------------------------------------------------- */
  {
    schluessel: 'kleriker-aasimar',
    name: 'Seraphine Morgenlicht',
    spezies: 'Aasimar',
    unterart: '',
    klasse: 'Kleriker',
    hintergrund: 'Akolyth',
    gesinnung: 'Rechtschaffen Gut',
    werte: { str: 12, dex: 10, con: 14, int: 8, wis: 17, cha: 14 },
    rettungswuerfe: ['wis', 'cha'],
    fertigkeiten: ['insight', 'religion', 'medicine', 'persuasion'],
    ruestungsklasse: 15,
    initiativeBonus: 0,
    trefferpunkte: 10,
    trefferwuerfel: '1d8',
    bewegung: 30,
    sinne: { darkvision: 60 },
    verteidigung: { resistances: 'Nekrotisch, gleißend' },
    rettungswurfVermerk: '',
    uebungen: {
      armor: 'Leichte und mittlere Rüstung, Schilde',
      weapons: 'Einfache Waffen',
      tools: 'Kalligraphenbedarf',
      languages: 'Gemeinsprache, Himmlisch',
    },
    angriffe: [
      { name: 'Streitkolben', bonus: '+3', damage: '1W6+1 Wucht', notes: '' },
      { name: 'Heilige Flamme', bonus: 'SG 13', damage: '1W8 gleißend', notes: 'GES-RW, Deckung hilft nicht' },
    ],
    aktionen: [
      {
        name: 'Heilende Hände',
        art: 'aktion',
        description: 'Berührung: 1W4 Trefferpunkte zurück. Einmal je Lange Rast.',
      },
      {
        name: 'Segnen (Konzentration)',
        art: 'aktion',
        description: 'Drei Verbündete addieren 1W4 auf Angriffe und Rettungswürfe. Der stärkste Zauber, den du auf Stufe 1 hast.',
      },
    ],
    ressourcen: [
      { name: 'Heilende Hände', current: 1, max: 1, recharge: 'lang' },
      { name: 'Kanalisierte Göttlichkeit', current: 2, max: 2, recharge: 'kurz' },
    ],
    merkmale: [
      {
        name: 'Zauberwirken',
        category: 'klasse',
        source: 'PHB-2024',
        page: '68',
        description: 'Weisheit ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5. Du bereitest vier Zauber vor.',
      },
      {
        name: 'Göttlicher Orden: Beschützer',
        category: 'klasse',
        source: 'PHB-2024',
        page: '68',
        description: 'Übung mit schweren Rüstungen und Kriegswaffen – für den Fall, dass du sie findest.',
      },
      {
        name: 'Dunkelsicht',
        category: 'spezies',
        source: 'PHB-2024',
        page: '184',
        description: '18 m weit.',
      },
      {
        name: 'Himmlische Widerstandskraft',
        category: 'spezies',
        source: 'PHB-2024',
        page: '184',
        description: 'Resistenz gegen nekrotischen und gleißenden Schaden.',
      },
      {
        name: 'Heilende Hände',
        category: 'spezies',
        source: 'PHB-2024',
        page: '184',
        description: 'Als Aktion 1W4 Trefferpunkte durch Berührung. Einmal je Lange Rast.',
      },
      {
        name: 'Lichtträger',
        category: 'spezies',
        source: 'PHB-2024',
        page: '184',
        description: 'Du kennst den Zaubertrick Licht.',
      },
      {
        name: 'Magiekundig (Kleriker)',
        category: 'hintergrund',
        source: 'PHB-2024',
        page: '202',
        description: 'Zwei Zaubertricks und ein Zauber vom 1. Grad aus der Klerikerliste, einmal je Lange Rast ohne Platz.',
      },
    ],
    zauber: {
      attribut: 'wis',
      plaetze: { 1: { max: 2, used: 0 } },
      liste: [
        {
          name: 'Heilige Flamme',
          level: 0,
          prepared: true,
          index: 'sacred-flame',
          source: 'Kleriker',
          save: 'GES-RW',
          time: '1 A',
          range: '18 m',
          components: 'V, S',
          duration: 'Sofort',
          page: 'PHB-2024 293',
          notes: 'Deckung nützt dem Ziel nichts – gut gegen alles hinter Steinen.',
        },
        {
          name: 'Führung',
          level: 0,
          prepared: true,
          index: 'guidance',
          source: 'Kleriker',
          save: '--',
          time: '1 A',
          range: 'Berührung',
          components: 'V, S',
          duration: 'K, 1 Min.',
          page: 'PHB-2024 267',
          notes: '+1W4 auf eine Attributsprobe. Außerhalb des Kampfes fast immer angebracht.',
        },
        {
          name: 'Licht',
          level: 0,
          prepared: true,
          index: 'light',
          source: 'Aasimar',
          save: '--',
          time: '1 A',
          range: 'Berührung',
          components: 'V, M',
          duration: '1 Std.',
          page: 'PHB-2024 275',
          notes: '',
        },
        {
          name: 'Segnen',
          level: 1,
          prepared: true,
          index: 'bless',
          source: 'Kleriker',
          save: '--',
          time: '1 A',
          range: '9 m',
          components: 'V, S, M',
          duration: 'K, 1 Min.',
          page: 'PHB-2024 247',
          notes: 'Drei Ziele, +1W4 auf Angriffe und Rettungswürfe. Zuerst wirken, dann alles andere.',
        },
        {
          name: 'Wunden heilen',
          level: 1,
          prepared: true,
          index: 'cure-wounds',
          source: 'Kleriker',
          save: '--',
          time: '1 A',
          range: 'Berührung',
          components: 'V, S',
          duration: 'Sofort',
          page: 'PHB-2024 255',
          notes: '2W8 + 3 Trefferpunkte.',
        },
        {
          name: 'Führender Blitz',
          level: 1,
          prepared: true,
          index: 'guiding-bolt',
          source: 'Kleriker',
          save: '--',
          time: '1 A',
          range: '36 m',
          components: 'V, S',
          duration: '1 Runde',
          page: 'PHB-2024 268',
          notes: '4W6 gleißend, und der nächste Angriff gegen das Ziel hat Vorteil.',
        },
        {
          name: 'Schild des Glaubens',
          level: 1,
          prepared: true,
          index: 'shield-of-faith',
          source: 'Kleriker',
          save: '--',
          time: '1 BA',
          range: '18 m',
          components: 'V, S, M',
          duration: 'K, 10 Min.',
          page: 'PHB-2024 296',
          notes: '+2 RK für einen Verbündeten. Bonusaktion.',
        },
      ],
    },
    ausruestung: [
      { name: 'Kettenhemd', qty: 1, weight: 20, notes: 'RK 13 + Geschicklichkeit (max. 2)' },
      { name: 'Schild', qty: 1, weight: 6, notes: '+2 RK' },
      { name: 'Streitkolben', qty: 1, weight: 4, notes: '' },
      { name: 'Heiliges Symbol', qty: 1, weight: 1, notes: 'Zauberfokus' },
      { name: 'Kalligraphenbedarf', qty: 1, weight: 5, notes: '' },
      { name: 'Gebetbuch', qty: 1, weight: 5, notes: '' },
      { name: 'Pergament', qty: 10, weight: 0, notes: '' },
      { name: 'Robe', qty: 1, weight: 4, notes: '' },
      {
        name: 'Priesterpaket',
        qty: 1,
        weight: 25,
        notes: 'Rucksack, Decke, Kerzen ×10, Zunderkästchen, Almosenbüchse, Weihrauch ×2, Räuchergefäß, Gewand, Rationen ×2, Wasserschlauch',
      },
    ],
    muenzen: { gp: 15 },
    aussehen: {
      gender: 'weiblich',
      age: '27',
      size: 'Mittelgroß',
      height: '169 cm',
      weight: '63 kg',
      faith: 'Lathander',
      skin: 'warm, mit einem schwachen Schimmer an den Schläfen',
      eyes: 'bernsteinfarben, ohne sichtbare Pupille im Licht',
      hair: 'weißblond',
    },
    wesen: {
      personality: 'Ich frage zuerst, was jemand braucht, und erst danach, wer er ist.',
      ideals: 'Barmherzigkeit. Wer um Hilfe bittet, hat damit genug gesagt.',
      bonds: 'Das Waisenhaus am Morgentor hat mich großgezogen, ohne zu wissen, was ich bin. Es hat kein Geld.',
      flaws: 'Ich heile weiter, wenn längst Zeit wäre zu fliehen, und reiße die anderen mit hinein.',
      backstory:
        'Sie wurde in einem Korb an der Tür des Waisenhauses am Morgentor gefunden, und die Schwestern behielten für sich, dass das Kind im Dunkeln leuchtete. Mit siebzehn hörte Seraphine zum ersten Mal die Stimme, die ihr sagte, wohin sie gehen solle – und sie ging, weil die Alternative war, weiter Suppe auszuteilen, während draußen etwas Falsches geschah. Zurück schickt sie jeden Monat, was sie erübrigen kann.',
      look: 'Ruhig, aufrecht, mit einem Blick, den Leute länger halten als beabsichtigt. Im Halbdunkel sieht man, dass ihre Haut ein wenig Licht abgibt.',
      allies: 'Das Waisenhaus am Morgentor und Schwester Ilva, die ihr schreibt.',
    },
  },

  /* --- Gnom · Druide ------------------------------------------------------- */
  {
    schluessel: 'druide-gnom',
    name: 'Fibbel Wurzelbart',
    spezies: 'Gnom',
    unterart: 'Waldgnom',
    klasse: 'Druide',
    hintergrund: 'Einsiedler',
    gesinnung: 'Neutral Gut',
    werte: { str: 8, dex: 13, con: 15, int: 12, wis: 17, cha: 10 },
    rettungswuerfe: ['int', 'wis'],
    fertigkeiten: ['medicine', 'religion', 'nature', 'perception'],
    ruestungsklasse: 14,
    initiativeBonus: 0,
    trefferpunkte: 10,
    trefferwuerfel: '1d8',
    bewegung: 30,
    sinne: { darkvision: 60 },
    verteidigung: {},
    rettungswurfVermerk: 'Vorteil auf Rettungswürfe gegen Magie bei Intelligenz, Weisheit und Charisma (Gnomenschläue).',
    uebungen: {
      armor: 'Leichte und mittlere Rüstung, Schilde (nichts aus Metall)',
      weapons: 'Einfache Waffen',
      tools: 'Kräuterkundeausrüstung',
      languages: 'Gemeinsprache, Gnomisch, Druidisch',
    },
    angriffe: [
      { name: 'Sichel', bonus: '+1', damage: '1W4-1 Hieb', notes: 'Leicht – im Ernstfall lieber zaubern' },
      { name: 'Flamme erzeugen', bonus: '+5', damage: '1W8 Feuer', notes: 'Fernkampf 9 m, Licht in der Hand' },
    ],
    aktionen: [
      {
        name: 'Verstricken (Konzentration)',
        art: 'aktion',
        description: '6-m-Quadrat wird schwieriges Gelände; wer den Stärke-RW nicht schafft, ist festgesetzt.',
      },
      {
        name: 'Donnerwoge',
        art: 'aktion',
        description: '4,5-m-Würfel: 2W8 Donner und 3 m weggestoßen. Der Notausgang, wenn zu viele zu nah stehen.',
      },
    ],
    ressourcen: [{ name: 'Druidenkunde: Wetterfühlig', current: 1, max: 1, recharge: 'lang' }],
    merkmale: [
      {
        name: 'Zauberwirken',
        category: 'klasse',
        source: 'PHB-2024',
        page: '82',
        description: 'Weisheit ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5. Du bereitest vier Zauber vor.',
      },
      {
        name: 'Druidisch',
        category: 'klasse',
        source: 'PHB-2024',
        page: '82',
        description: 'Die Geheimsprache der Druiden. Du hinterlässt damit Zeichen, die nur Eingeweihte lesen.',
      },
      {
        name: 'Grundausbildung: Druidenkunde',
        category: 'klasse',
        source: 'PHB-2024',
        page: '82',
        description: 'Der Zaubertrick Druidenkunde ist immer vorbereitet.',
      },
      { name: 'Dunkelsicht', category: 'spezies', source: 'PHB-2024', page: '191', description: '18 m weit.' },
      {
        name: 'Gnomenschläue',
        category: 'spezies',
        source: 'PHB-2024',
        page: '191',
        description: 'Vorteil auf Intelligenz-, Weisheits- und Charisma-Rettungswürfe.',
      },
      {
        name: 'Gnomenabstammung: Waldgnom',
        category: 'spezies',
        source: 'PHB-2024',
        page: '191',
        description: 'Du kennst den Zaubertrick Kleine Illusion und kannst mit kleinen Tieren sprechen.',
      },
      {
        name: 'Heiler',
        category: 'talent',
        source: 'PHB-2024',
        page: '202',
        description:
          'Mit einer Heilerausrüstung als Bonusaktion 1W6 + 4 Trefferpunkte heilen. Außerdem würfelst du eine 1 bei Heilwürfeln neu.',
      },
    ],
    zauber: {
      attribut: 'wis',
      plaetze: { 1: { max: 2, used: 0 } },
      liste: [
        {
          name: 'Druidenkunst',
          level: 0,
          prepared: true,
          index: 'druidcraft',
          source: 'Druide',
          save: '--',
          time: '1 A',
          range: '9 m',
          components: 'V, S',
          duration: 'Sofort',
          page: 'PHB-2024 260',
          notes: 'Wetter voraussagen, eine Blüte öffnen, ein Feuer löschen.',
        },
        {
          name: 'Flamme erzeugen',
          level: 0,
          prepared: true,
          index: 'produce-flame',
          source: 'Druide',
          save: '--',
          time: '1 A',
          range: 'Selbst / 9 m',
          components: 'V, S',
          duration: '10 Min.',
          page: 'PHB-2024 289',
          notes: 'Licht und Angriff in einem – die Flamme bleibt, bis du sie wirfst.',
        },
        {
          name: 'Kleine Illusion',
          level: 0,
          prepared: true,
          index: 'minor-illusion',
          source: 'Waldgnom',
          save: '--',
          time: '1 A',
          range: '9 m',
          components: 'S, M',
          duration: '1 Min.',
          page: 'PHB-2024 280',
          notes: '',
        },
        {
          name: 'Verstricken',
          level: 1,
          prepared: true,
          index: 'entangle',
          source: 'Druide',
          save: 'STÄ-RW',
          time: '1 A',
          range: '27 m',
          components: 'V, S',
          duration: 'K, 1 Min.',
          page: 'PHB-2024 261',
          notes: 'Hält eine ganze Reihe von Gegnern auf, ohne dass jemand Schaden nimmt.',
        },
        {
          name: 'Feenfeuer',
          level: 1,
          prepared: true,
          index: 'faerie-fire',
          source: 'Druide',
          save: 'GES-RW',
          time: '1 A',
          range: '18 m',
          components: 'V',
          duration: 'K, 1 Min.',
          page: 'PHB-2024 261',
          notes: 'Vorteil für alle Angriffe der Gruppe gegen die Umrissenen.',
        },
        {
          name: 'Heilendes Wort',
          level: 1,
          prepared: true,
          index: 'healing-word',
          source: 'Druide',
          save: '--',
          time: '1 BA',
          range: '18 m',
          components: 'V',
          duration: 'Sofort',
          page: 'PHB-2024 268',
          notes: '',
        },
        {
          name: 'Donnerwoge',
          level: 1,
          prepared: true,
          index: 'thunderwave',
          source: 'Druide',
          save: 'KON-RW',
          time: '1 A',
          range: 'Selbst (4,5-m-Würfel)',
          components: 'V, S',
          duration: 'Sofort',
          page: 'PHB-2024 303',
          notes: '2W8 Donner und 3 m Stoß – schafft Luft.',
        },
      ],
    },
    ausruestung: [
      { name: 'Lederrüstung', qty: 1, weight: 10, notes: 'RK 11 + Geschicklichkeit' },
      { name: 'Holzschild', qty: 1, weight: 6, notes: '+2 RK, kein Metall' },
      { name: 'Sichel', qty: 1, weight: 2, notes: '' },
      { name: 'Kampfstab', qty: 1, weight: 4, notes: 'Druidenfokus' },
      { name: 'Kräuterkundeausrüstung', qty: 1, weight: 3, notes: '' },
      { name: 'Heilerausrüstung', qty: 1, weight: 3, notes: 'für das Talent Heiler' },
      { name: 'Schlafrolle', qty: 1, weight: 7, notes: '' },
      { name: 'Buch über Pilze', qty: 1, weight: 5, notes: 'eigenhändig geschrieben' },
      { name: 'Lampe', qty: 1, weight: 1, notes: '' },
      { name: 'Öl', qty: 3, weight: 1, notes: '' },
      { name: 'Reisekleidung', qty: 1, weight: 4, notes: '' },
      {
        name: 'Entdeckerpaket',
        qty: 1,
        weight: 59,
        notes: 'Rucksack, Schlafrolle, Zunderkästchen, Fackeln ×10, Rationen ×10, Wasserschlauch, Seil 15 m',
      },
    ],
    muenzen: { gp: 25 },
    aussehen: {
      gender: 'männlich',
      age: '118',
      size: 'Klein',
      height: '99 cm',
      weight: '19 kg',
      faith: 'der Alte Hain',
      skin: 'nussbraun',
      eyes: 'moosgrün',
      hair: 'grau, mit Flechten im Bart',
    },
    wesen: {
      personality: 'Ich rede mit allem, was wächst, und warte tatsächlich die Antwort ab.',
      ideals: 'Gleichgewicht. Nimm, was du brauchst, und lege zurück, was du kannst.',
      bonds: 'Der Alte Hain hat mich vierzig Jahre beherbergt. Was ihn kahl frisst, geht mich an.',
      flaws: 'Menschen und ihre Eile ermüden mich, und das merkt man mir an.',
      backstory:
        'Vierzig Jahre lebte Fibbel allein am Rand des Alten Hains, sammelte Pilze, schrieb ein Buch darüber, das niemand las, und sprach mit den Eichhörnchen, die ihm antworteten. Dann kam die Fäule aus dem Norden, und die Bäume, die er beim Namen kannte, starben von innen. Er packte seinen Stab und ging los, weil man von einer Sache nicht heilen kann, deren Ursache man nicht kennt.',
      look: 'Reicht den meisten bis zur Hüfte und wirkt trotzdem nie klein. Trägt Flechten im Bart, die er als Vorrat bezeichnet.',
      allies: 'Der Alte Hain und ein Marder namens Nussknack, der ihm manchmal folgt.',
    },
  },

  /* --- Halbling · Mönch ---------------------------------------------------- */
  {
    schluessel: 'moench-halbling',
    name: 'Pip Sommerfeld',
    spezies: 'Halbling',
    unterart: '',
    klasse: 'Mönch',
    hintergrund: 'Weltenbummler',
    gesinnung: 'Chaotisch Gut',
    werte: { str: 12, dex: 17, con: 14, int: 8, wis: 14, cha: 10 },
    rettungswuerfe: ['str', 'dex'],
    fertigkeiten: ['insight', 'stealth', 'acrobatics', 'athletics'],
    // Ohne Rüstung: 10 + Geschicklichkeit + Weisheit.
    ruestungsklasse: 15,
    initiativeBonus: 0,
    trefferpunkte: 10,
    trefferwuerfel: '1d8',
    bewegung: 30,
    sinne: {},
    verteidigung: {},
    rettungswurfVermerk: 'Vorteil auf Rettungswürfe gegen Verängstigt (Mutig).',
    uebungen: {
      armor: 'keine',
      weapons: 'Einfache Waffen, Kurzschwerter',
      tools: 'Diebeswerkzeug, Würfelset',
      languages: 'Gemeinsprache, Halblingisch',
    },
    angriffe: [
      { name: 'Kampfstab (zweihändig)', bonus: '+5', damage: '1W8+3 Wucht', notes: 'Vielseitig – oder 1W6 als Kampfkunstwaffe' },
      { name: 'Unbewaffneter Schlag', bonus: '+5', damage: '1W6+3 Wucht', notes: 'Kampfkunst' },
      { name: 'Dolch', bonus: '+5', damage: '1W4+3 Stich', notes: 'Finesse, Wurf 6/18 m' },
    ],
    aktionen: [
      {
        name: 'Kampfkunst: Zusatzangriff',
        art: 'bonus',
        description: 'Nach einem unbewaffneten Angriff oder einem Angriff mit einer Mönchswaffe ein weiterer unbewaffneter Schlag.',
      },
      {
        name: 'Glück',
        art: 'frei',
        description:
          'Dreimal je Lange Rast: Vorteil auf einen Angriff, eine Probe oder einen Rettungswurf – oder Nachteil auf einen Angriff gegen dich.',
      },
    ],
    ressourcen: [{ name: 'Glück (Talent)', current: 3, max: 3, recharge: 'lang' }],
    merkmale: [
      {
        name: 'Kampfkunst',
        category: 'klasse',
        source: 'PHB-2024',
        page: '110',
        description:
          'Ohne Rüstung und ohne Schild: Geschicklichkeit für unbewaffnete Angriffe und Mönchswaffen, W6 Schadenswürfel, und als Bonusaktion ein zusätzlicher unbewaffneter Schlag.',
      },
      {
        name: 'Ungepanzerte Verteidigung',
        category: 'klasse',
        source: 'PHB-2024',
        page: '110',
        description: 'Ohne Rüstung ist deine Rüstungsklasse 10 + Geschicklichkeit + Weisheit. (Ist oben eingerechnet.)',
      },
      {
        name: 'Mutig',
        category: 'spezies',
        source: 'PHB-2024',
        page: '192',
        description: 'Vorteil auf Rettungswürfe gegen die Bedingung Verängstigt.',
      },
      {
        name: 'Halblingsglück',
        category: 'spezies',
        source: 'PHB-2024',
        page: '192',
        description: 'Würfelst du bei einem W20 eine 1, würfelst du ihn neu und musst das neue Ergebnis nehmen.',
      },
      {
        name: 'Flinkheit',
        category: 'spezies',
        source: 'PHB-2024',
        page: '192',
        description: 'Du kannst dich durch den Raum jedes Geschöpfes bewegen, das größer ist als du.',
      },
      {
        name: 'Von Natur aus unauffällig',
        category: 'spezies',
        source: 'PHB-2024',
        page: '192',
        description: 'Du kannst dich verstecken, wenn ein größeres Geschöpf dich verdeckt.',
      },
      {
        name: 'Glück',
        category: 'talent',
        source: 'PHB-2024',
        page: '202',
        description: 'Dreimal je Lange Rast Vorteil auf einen eigenen W20 – oder Nachteil auf einen Angriff gegen dich.',
      },
    ],
    zauber: null,
    ausruestung: [
      { name: 'Kampfstab', qty: 1, weight: 4, notes: 'Mönchswaffe, vielseitig' },
      { name: 'Speer', qty: 1, weight: 3, notes: '' },
      { name: 'Dolch', qty: 7, weight: 1, notes: 'fünf aus der Klasse, zwei von der Straße' },
      { name: 'Diebeswerkzeug', qty: 1, weight: 1, notes: '' },
      { name: 'Würfelset', qty: 1, weight: 0.5, notes: '' },
      { name: 'Schlafrolle', qty: 1, weight: 7, notes: '' },
      { name: 'Beutel', qty: 2, weight: 1, notes: '' },
      { name: 'Reisekleidung', qty: 1, weight: 4, notes: '' },
      {
        name: 'Entdeckerpaket',
        qty: 1,
        weight: 59,
        notes: 'Rucksack, Schlafrolle, Zunderkästchen, Fackeln ×10, Rationen ×10, Wasserschlauch, Seil 15 m',
      },
    ],
    muenzen: { gp: 27 },
    aussehen: {
      gender: 'männlich',
      age: '29',
      size: 'Klein',
      height: '94 cm',
      weight: '18 kg',
      faith: 'die Straße kennt keinen Gott',
      skin: 'sonnengebräunt',
      eyes: 'dunkelbraun',
      hair: 'schwarz, lockig, meist zu kurz geschnitten',
    },
    wesen: {
      personality: 'Ich stehe nie da, wo man mich zuletzt gesehen hat. Gewohnheit, keine Absicht.',
      ideals: 'Beweglichkeit. Wer an einem Ort bleibt, wird von ihm eingeholt.',
      bonds: 'Der alte Mann am Flussweg brachte mir bei, wie man fällt, ohne zu brechen. Ich weiß bis heute nicht, wer er war.',
      flaws: 'Ich nehme mir, was herumliegt, auch wenn ich es nicht brauche – aus reiner Übung.',
      backstory:
        'Pip wuchs in den Gassen einer Hafenstadt auf, wo Kleinsein ein Vorteil war und Schnellsein die einzige Rente. Mit zweiundzwanzig griff er in die falsche Tasche, wurde nicht erwischt, sondern aufgehalten – von einem alten Mann, der ihm die Hand umdrehte, ohne sie zu brechen, und ihn dann zum Essen einlud. Sieben Jahre lernte er bei ihm, dann war der Alte eines Morgens fort, und Pip nahm seinen Stab und die Gewohnheit, weiterzugehen.',
      look: 'Klein, drahtig, immer in Bewegung – wippt auf den Fußballen, auch im Sitzen. Barfuß, wo es geht.',
      allies: 'Niemand mit Namen. Aber in vier Städten gibt es Küchen, in denen er essen darf.',
    },
  },

  /* --- Drachenblütiger · Paladin ------------------------------------------ */
  {
    schluessel: 'paladin-drachenbluetiger',
    name: 'Vaskir Goldschuppe',
    spezies: 'Drachenblütiger',
    unterart: 'Messingdrache',
    klasse: 'Paladin',
    hintergrund: 'Adliger',
    gesinnung: 'Rechtschaffen Gut',
    werte: { str: 16, dex: 10, con: 13, int: 8, wis: 12, cha: 16 },
    rettungswuerfe: ['wis', 'cha'],
    fertigkeiten: ['history', 'persuasion', 'athletics', 'religion'],
    ruestungsklasse: 18,
    initiativeBonus: 0,
    trefferpunkte: 11,
    trefferwuerfel: '1d10',
    bewegung: 30,
    sinne: { darkvision: 60 },
    verteidigung: { resistances: 'Feuer' },
    rettungswurfVermerk: '',
    uebungen: {
      armor: 'Leichte, mittlere und schwere Rüstung, Schilde',
      weapons: 'Einfache Waffen, Kriegswaffen',
      tools: 'Würfelset',
      languages: 'Gemeinsprache, Drakonisch',
    },
    angriffe: [
      { name: 'Langschwert', bonus: '+5', damage: '1W8+3 Hieb', notes: 'Vielseitig (1W10) · Meisterschaft: Zermürben' },
      { name: 'Wurfspeer', bonus: '+5', damage: '1W6+3 Stich', notes: 'Wurf 9/36 m · Meisterschaft: Verlangsamen' },
      { name: 'Odemwaffe (Feuer)', bonus: 'SG 13', damage: '1W10 Feuer', notes: 'Kegel 4,5 m, GES-RW für halben Schaden' },
    ],
    aktionen: [
      {
        name: 'Handauflegen',
        art: 'bonus',
        description:
          'Berührung: Trefferpunkte aus einem Vorrat von 5, frei aufteilbar. Für 5 Punkte stattdessen die Bedingung Vergiftet aufheben.',
      },
      {
        name: 'Odemwaffe',
        art: 'aktion',
        description: 'Kegel von 4,5 m, 1W10 Feuer, Geschicklichkeits-Rettungswurf gegen SG 13 für die Hälfte. Zweimal je Lange Rast.',
      },
    ],
    ressourcen: [
      { name: 'Handauflegen (TP-Vorrat)', current: 5, max: 5, recharge: 'lang' },
      { name: 'Odemwaffe', current: 2, max: 2, recharge: 'lang' },
    ],
    merkmale: [
      {
        name: 'Handauflegen',
        category: 'klasse',
        source: 'PHB-2024',
        page: '109',
        description:
          'Ein Vorrat an Heilkraft von 5 Punkten je Lange Rast. Als Bonusaktion durch Berührung verteilen; 5 Punkte heben stattdessen Vergiftet auf.',
      },
      {
        name: 'Zauberwirken',
        category: 'klasse',
        source: 'PHB-2024',
        page: '110',
        description: 'Charisma ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5. Du bereitest zwei Zauber vor.',
      },
      {
        name: 'Waffenmeisterschaft',
        category: 'klasse',
        source: 'PHB-2024',
        page: '110',
        description:
          'Zwei Waffen: Langschwert (Zermürben – das Ziel hat Nachteil auf seinen nächsten Angriff), Wurfspeer (Verlangsamen – 3 m weniger Bewegung).',
      },
      {
        name: 'Odemwaffe',
        category: 'spezies',
        source: 'PHB-2024',
        page: '188',
        description:
          'Statt eines Angriffs ein Kegel von 4,5 m: 1W10 Feuerschaden, Geschicklichkeits-Rettungswurf für die Hälfte. Übungsbonus-mal je Lange Rast.',
      },
      {
        name: 'Schadensresistenz',
        category: 'spezies',
        source: 'PHB-2024',
        page: '188',
        description: 'Resistenz gegen Feuerschaden – die Farbe deiner Schuppen entscheidet.',
      },
      { name: 'Dunkelsicht', category: 'spezies', source: 'PHB-2024', page: '188', description: '18 m weit.' },
      {
        name: 'Geübt',
        category: 'talent',
        source: 'PHB-2024',
        page: '207',
        description: 'Übung in drei weiteren Fertigkeiten oder Werkzeugen – hier Athletik, Religion und das Würfelset.',
      },
    ],
    zauber: {
      attribut: 'cha',
      plaetze: { 1: { max: 2, used: 0 } },
      liste: [
        {
          name: 'Segnen',
          level: 1,
          prepared: true,
          index: 'bless',
          source: 'Paladin',
          save: '--',
          time: '1 A',
          range: '9 m',
          components: 'V, S, M',
          duration: 'K, 1 Min.',
          page: 'PHB-2024 247',
          notes: 'Drei Ziele, +1W4 auf Angriffe und Rettungswürfe.',
        },
        {
          name: 'Wunden heilen',
          level: 1,
          prepared: true,
          index: 'cure-wounds',
          source: 'Paladin',
          save: '--',
          time: '1 A',
          range: 'Berührung',
          components: 'V, S',
          duration: 'Sofort',
          page: 'PHB-2024 255',
          notes: '2W8 + 3 – zusätzlich zum Handauflegen.',
        },
      ],
    },
    ausruestung: [
      { name: 'Kettenpanzer', qty: 1, weight: 55, notes: 'RK 16, Nachteil auf Heimlichkeit' },
      { name: 'Schild', qty: 1, weight: 6, notes: '+2 RK' },
      { name: 'Langschwert', qty: 1, weight: 3, notes: '' },
      { name: 'Wurfspeer', qty: 6, weight: 2, notes: '' },
      { name: 'Heiliges Symbol', qty: 1, weight: 1, notes: 'Zauberfokus, Messing' },
      { name: 'Würfelset', qty: 1, weight: 0.5, notes: 'aus dem Haus, mit Wappen' },
      { name: 'Feine Kleidung', qty: 1, weight: 6, notes: '' },
      { name: 'Parfüm', qty: 1, weight: 0, notes: '' },
      {
        name: 'Priesterpaket',
        qty: 1,
        weight: 25,
        notes: 'Rucksack, Decke, Kerzen ×10, Zunderkästchen, Almosenbüchse, Weihrauch ×2, Räuchergefäß, Gewand, Rationen ×2, Wasserschlauch',
      },
    ],
    muenzen: { gp: 38 },
    aussehen: {
      gender: 'männlich',
      age: '23',
      size: 'Mittelgroß',
      height: '196 cm',
      weight: '112 kg',
      faith: 'der Eid, nicht der Gott',
      skin: 'messingfarbene Schuppen, an den Unterarmen dunkler',
      eyes: 'kupferrot',
      hair: 'keines',
    },
    wesen: {
      personality: 'Ich sage, was ich tun werde, und tue es dann. Das verwirrt die Leute mehr, als es sollte.',
      ideals: 'Wort. Ein gegebenes Versprechen wiegt schwerer als das eigene Leben.',
      bonds: 'Mein Haus verkaufte den Pachtbauern das Land unter den Füßen weg. Ich zahle es zurück, Hof für Hof.',
      flaws: 'Ich halte auch dann an einem Versprechen fest, wenn es längst mehr schadet als nützt.',
      backstory:
        'Das Haus Goldschuppe war reich geworden, indem es in Notzeiten Land aufkaufte, und Vaskir hörte am Tisch zu, wie man das für Klugheit hielt. Mit zwanzig ritt er zum ersten Mal selbst hinaus, um einen Hof einzuziehen, und sah die Familie, die dort stand. Er ritt ohne den Hof zurück, legte den Eid ab und nahm nichts mit als Rüstung, Klinge und die Liste der Höfe, die sein Haus noch hält.',
      look: 'Hochgewachsen, Schuppen wie poliertes Messing, die Bewegungen eines Menschen, dem beigebracht wurde, wie man einen Saal betritt.',
      allies: 'Niemand aus dem Haus mehr. Dafür acht Pachtfamilien, die seinen Namen kennen.',
    },
  },

  /* --- Elf · Waldläufer ---------------------------------------------------- */
  {
    schluessel: 'waldlaeufer-elf',
    name: 'Naelith Silberpfeil',
    spezies: 'Elf',
    unterart: 'Waldelf',
    klasse: 'Waldläufer',
    hintergrund: 'Fährtensucher',
    gesinnung: 'Neutral Gut',
    werte: { str: 12, dex: 17, con: 14, int: 10, wis: 14, cha: 8 },
    rettungswuerfe: ['str', 'dex'],
    fertigkeiten: ['stealth', 'survival', 'perception', 'nature', 'insight'],
    expertise: [],
    ruestungsklasse: 15,
    initiativeBonus: 0,
    trefferpunkte: 12,
    trefferwuerfel: '1d10',
    bewegung: 35,
    sinne: { darkvision: 60 },
    verteidigung: {},
    rettungswurfVermerk: 'Vorteil auf Rettungswürfe gegen Bezauberung, und Magie kann dich nicht schlafen legen (Feenblut, Trance).',
    uebungen: {
      armor: 'Leichte und mittlere Rüstung, Schilde',
      weapons: 'Einfache Waffen, Kriegswaffen',
      tools: 'Kartografenwerkzeug',
      languages: 'Gemeinsprache, Elfisch, Sylvanisch',
    },
    angriffe: [
      { name: 'Langbogen', bonus: '+5', damage: '1W8+3 Stich', notes: '45/180 m, Schwer, Zweihändig · Meisterschaft: Verlangsamen' },
      { name: 'Kurzschwert', bonus: '+5', damage: '1W6+3 Stich', notes: 'Finesse, Leicht · Meisterschaft: Ärgern' },
      { name: 'Krummsäbel', bonus: '+5', damage: '1W6+3 Hieb', notes: 'Finesse, Leicht' },
    ],
    aktionen: [
      {
        name: 'Jagdzeichen',
        art: 'bonus',
        description:
          'Ein Ziel in 27 m markieren: +1W6 Schaden bei jedem deiner Treffer, solange du dich konzentrierst. Zweimal ohne Zauberplatz je Lange Rast.',
      },
      {
        name: 'Fesselnder Schlag',
        art: 'bonus',
        description: 'Der nächste Treffer umschlingt das Ziel: 1W6 Stich je Runde, festgesetzt bis zum Befreien (STÄ, SG 13).',
      },
    ],
    ressourcen: [{ name: 'Jagdzeichen (frei)', current: 2, max: 2, recharge: 'lang' }],
    merkmale: [
      {
        name: 'Bevorzugter Feind: Jagdzeichen',
        category: 'klasse',
        source: 'PHB-2024',
        page: '131',
        description:
          'Jagdzeichen ist immer vorbereitet und kostet dich übungsbonus-mal je Lange Rast keinen Zauberplatz.',
      },
      {
        name: 'Zauberwirken',
        category: 'klasse',
        source: 'PHB-2024',
        page: '131',
        description: 'Weisheit ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5. Du bereitest zwei Zauber vor.',
      },
      {
        name: 'Waffenmeisterschaft',
        category: 'klasse',
        source: 'PHB-2024',
        page: '131',
        description:
          'Zwei Waffen: Langbogen (Verlangsamen – 3 m weniger Bewegung), Kurzschwert (Ärgern – dein nächster Angriff gegen dasselbe Ziel hat Vorteil).',
      },
      { name: 'Dunkelsicht', category: 'spezies', source: 'PHB-2024', page: '190', description: '18 m weit.' },
      {
        name: 'Feenblut',
        category: 'spezies',
        source: 'PHB-2024',
        page: '190',
        description: 'Vorteil auf Rettungswürfe, um die Bedingung Bezaubert zu vermeiden oder zu beenden.',
      },
      {
        name: 'Scharfe Sinne',
        category: 'spezies',
        source: 'PHB-2024',
        page: '190',
        description: 'Übung in Wahrnehmung.',
      },
      {
        name: 'Trance',
        category: 'spezies',
        source: 'PHB-2024',
        page: '190',
        description: 'Du schläfst nicht. Eine Lange Rast dauert für dich vier Stunden wacher Meditation.',
      },
      {
        name: 'Elfische Abstammung: Waldelf',
        category: 'spezies',
        source: 'PHB-2024',
        page: '190',
        description: 'Bewegungsrate 10,5 m, und du kennst den Zauber Weitschritt (einmal je Lange Rast ohne Platz).',
      },
      {
        name: 'Magiekundig (Urtümlich)',
        category: 'hintergrund',
        source: 'PHB-2024',
        page: '202',
        description: 'Zwei Zaubertricks und ein Zauber vom 1. Grad aus der Druidenliste, einmal je Lange Rast ohne Platz.',
      },
    ],
    zauber: {
      attribut: 'wis',
      plaetze: { 1: { max: 2, used: 0 } },
      liste: [
        {
          name: 'Jagdzeichen',
          level: 1,
          prepared: true,
          index: 'hunters-mark',
          source: 'Bevorzugter Feind',
          save: '--',
          time: '1 BA',
          range: '27 m',
          components: 'V',
          duration: 'K, 1 Std.',
          page: 'PHB-2024 272',
          notes: 'Immer vorbereitet. Erste Bonusaktion jedes Kampfes.',
        },
        {
          name: 'Fesselnder Schlag',
          level: 1,
          prepared: true,
          index: 'ensnaring-strike',
          source: 'Waldläufer',
          save: 'STÄ-RW',
          time: '1 BA',
          range: 'Selbst',
          components: 'V',
          duration: 'K, 1 Min.',
          page: 'PHB-2024 261',
          notes: 'Hält einen Gegner fest, ohne dass jemand hin muss.',
        },
        {
          name: 'Wunden heilen',
          level: 1,
          prepared: true,
          index: 'cure-wounds',
          source: 'Waldläufer',
          save: '--',
          time: '1 A',
          range: 'Berührung',
          components: 'V, S',
          duration: 'Sofort',
          page: 'PHB-2024 255',
          notes: '2W8 + 2 – die einzige Heilung der Gruppe, wenn kein Kleriker dabei ist.',
        },
        {
          name: 'Druidenkunst',
          level: 0,
          prepared: true,
          index: 'druidcraft',
          source: 'Magiekundig',
          save: '--',
          time: '1 A',
          range: '9 m',
          components: 'V, S',
          duration: 'Sofort',
          page: 'PHB-2024 260',
          notes: '',
        },
        {
          name: 'Weitschritt',
          level: 1,
          prepared: true,
          index: 'longstrider',
          source: 'Waldelf',
          save: '--',
          time: '1 A',
          range: 'Berührung',
          components: 'V, S, M',
          duration: '1 Std.',
          page: 'PHB-2024 277',
          notes: 'Einmal je Lange Rast ohne Zauberplatz. +3 m Bewegung für eine Stunde.',
        },
      ],
    },
    ausruestung: [
      { name: 'Nietlederrüstung', qty: 1, weight: 13, notes: 'RK 12 + Geschicklichkeit' },
      { name: 'Langbogen', qty: 1, weight: 2, notes: '' },
      { name: 'Pfeile', qty: 40, weight: 0.05, notes: 'zwanzig aus der Klasse, zwanzig vom Hintergrund' },
      { name: 'Köcher', qty: 2, weight: 1, notes: '' },
      { name: 'Kurzschwert', qty: 1, weight: 2, notes: '' },
      { name: 'Krummsäbel', qty: 1, weight: 3, notes: '' },
      { name: 'Kurzbogen', qty: 1, weight: 2, notes: 'als Ersatz im Gepäck' },
      { name: 'Druidenfokus (Mistelzweig)', qty: 1, weight: 0, notes: '' },
      { name: 'Kartografenwerkzeug', qty: 1, weight: 6, notes: '' },
      { name: 'Schlafrolle', qty: 1, weight: 7, notes: '' },
      { name: 'Zelt', qty: 1, weight: 20, notes: 'für zwei Personen' },
      { name: 'Reisekleidung', qty: 1, weight: 4, notes: '' },
      {
        name: 'Entdeckerpaket',
        qty: 1,
        weight: 59,
        notes: 'Rucksack, Schlafrolle, Zunderkästchen, Fackeln ×10, Rationen ×10, Wasserschlauch, Seil 15 m',
      },
    ],
    muenzen: { gp: 10 },
    aussehen: {
      gender: 'weiblich',
      age: '142',
      size: 'Mittelgroß',
      height: '178 cm',
      weight: '58 kg',
      faith: 'die Wege selbst',
      skin: 'kupferbraun',
      eyes: 'waldgrün',
      hair: 'kastanienbraun, an einer Seite geflochten',
    },
    wesen: {
      personality: 'Ich gehe voraus und sage erst etwas, wenn ich etwas gefunden habe.',
      ideals: 'Umsicht. Der Weg, den man kennt, ist den Umweg wert.',
      bonds: 'Ich habe eine Karawane in einen Pass geführt, aus dem nur ich zurückkam. Die Karte war meine.',
      flaws: 'Ich vertraue meinen eigenen Augen mehr als jedem Menschen, auch wenn beide sich irren.',
      backstory:
        'Naelith führte vierzig Jahre lang Leute über die Nordpässe und verlor in dieser Zeit niemanden – bis zu dem Winter, in dem ein Weg, den sie hundertmal gegangen war, unter einer Karawane wegbrach. Man gab ihr keine Schuld; das machte es nicht besser. Seither zeichnet sie jede Route doppelt, geht als Erste und ist bei jeder Gruppe, die sie begleitet, unangenehm gründlich.',
      look: 'Bewegt sich, ohne Geräusche zu machen, und bleibt oft stehen, um etwas anzusehen, das sonst niemand bemerkt hat.',
      allies: 'Die Kartografengilde von Weißfurt, die ihre Karten noch immer kauft.',
    },
  },

  /* --- Tiefling · Schurke -------------------------------------------------- */
  {
    schluessel: 'schurke-tiefling',
    name: 'Zaira Kesselflick',
    spezies: 'Tiefling',
    unterart: 'Höllische Abstammung',
    klasse: 'Schurke',
    hintergrund: 'Verbrecher',
    gesinnung: 'Chaotisch Neutral',
    werte: { str: 8, dex: 17, con: 14, int: 14, wis: 12, cha: 10 },
    rettungswuerfe: ['dex', 'int'],
    fertigkeiten: ['sleightOfHand', 'deception', 'investigation', 'acrobatics'],
    expertise: ['stealth', 'perception'],
    ruestungsklasse: 14,
    // Wachsam legt den Übungsbonus auf die Initiative.
    initiativeBonus: 2,
    trefferpunkte: 10,
    trefferwuerfel: '1d8',
    bewegung: 30,
    sinne: { darkvision: 60 },
    verteidigung: { resistances: 'Feuer' },
    rettungswurfVermerk: '',
    uebungen: {
      armor: 'Leichte Rüstung',
      weapons: 'Einfache Waffen, Finessewaffen, Leichte Waffen',
      tools: 'Diebeswerkzeug',
      languages: 'Gemeinsprache, Infernalisch',
    },
    angriffe: [
      { name: 'Kurzschwert', bonus: '+5', damage: '1W6+3 Stich', notes: 'Finesse, Leicht · Meisterschaft: Ärgern' },
      { name: 'Kurzbogen', bonus: '+5', damage: '1W6+3 Stich', notes: '24/96 m · Meisterschaft: Ärgern' },
      { name: 'Dolch', bonus: '+5', damage: '1W4+3 Stich', notes: 'Finesse, Leicht, Wurf 6/18 m' },
      { name: 'Hinterhältiger Angriff', bonus: '—', damage: '+1W6', notes: 'Bei Vorteil oder wenn ein Verbündeter neben dem Ziel steht' },
    ],
    aktionen: [
      {
        name: 'Verstecken',
        art: 'aktion',
        description: 'Heimlichkeit +7 gegen SG 15. Gelingt es, hast du Vorteil – und damit den Hinterhältigen Angriff.',
      },
      {
        name: 'Diebeskunst',
        art: 'frei',
        description: 'Diebeswerkzeug mit doppeltem Übungsbonus: Schlösser +7, Fallen entschärfen +7.',
      },
    ],
    ressourcen: [],
    merkmale: [
      {
        name: 'Hinterhältiger Angriff',
        category: 'klasse',
        source: 'PHB-2024',
        page: '134',
        description:
          'Einmal je Zug +1W6 Schaden mit einer Finesse- oder Fernkampfwaffe, wenn du Vorteil hast oder ein Verbündeter neben dem Ziel steht.',
      },
      {
        name: 'Sachkenntnis',
        category: 'klasse',
        source: 'PHB-2024',
        page: '134',
        description: 'Doppelter Übungsbonus in Heimlichkeit und Wahrnehmung.',
      },
      {
        name: 'Diebesjargon',
        category: 'klasse',
        source: 'PHB-2024',
        page: '134',
        description: 'Eine Geheimsprache aus Andeutungen und Zeichen, die nur andere Schurken verstehen.',
      },
      {
        name: 'Waffenmeisterschaft',
        category: 'klasse',
        source: 'PHB-2024',
        page: '134',
        description: 'Zwei Waffen: Kurzschwert und Kurzbogen, beide mit Ärgern – dein nächster Angriff gegen dasselbe Ziel hat Vorteil.',
      },
      { name: 'Dunkelsicht', category: 'spezies', source: 'PHB-2024', page: '197', description: '18 m weit.' },
      {
        name: 'Höllisches Erbe',
        category: 'spezies',
        source: 'PHB-2024',
        page: '197',
        description: 'Resistenz gegen Feuerschaden und der Zaubertrick Thaumaturgie.',
      },
      {
        name: 'Überirdische Gegenwart',
        category: 'spezies',
        source: 'PHB-2024',
        page: '197',
        description: 'Du kennst den Zaubertrick Thaumaturgie und wirkst ihn mit Charisma.',
      },
      {
        name: 'Wachsam',
        category: 'talent',
        source: 'PHB-2024',
        page: '200',
        description: 'Du addierst deinen Übungsbonus auf die Initiative und darfst sie mit einem einverstandenen Verbündeten tauschen.',
      },
    ],
    zauber: {
      attribut: 'cha',
      plaetze: {},
      liste: [
        {
          name: 'Thaumaturgie',
          level: 0,
          prepared: true,
          index: 'thaumaturgy',
          source: 'Höllische Abstammung',
          save: '--',
          time: '1 A',
          range: '9 m',
          components: 'V',
          duration: 'bis 1 Min.',
          page: 'PHB-2024 302',
          notes: 'Türen aufspringen lassen, die Stimme dreimal so laut – meist reicht das.',
        },
      ],
    },
    ausruestung: [
      { name: 'Lederrüstung', qty: 1, weight: 10, notes: 'RK 11 + Geschicklichkeit' },
      { name: 'Kurzschwert', qty: 1, weight: 2, notes: '' },
      { name: 'Kurzbogen', qty: 1, weight: 2, notes: '' },
      { name: 'Pfeile', qty: 20, weight: 0.05, notes: '' },
      { name: 'Köcher', qty: 1, weight: 1, notes: '' },
      { name: 'Dolch', qty: 4, weight: 1, notes: 'zwei aus der Klasse, zwei aus alten Zeiten' },
      { name: 'Diebeswerkzeug', qty: 1, weight: 1, notes: 'Sachkenntnis: +7' },
      { name: 'Brecheisen', qty: 1, weight: 5, notes: '' },
      { name: 'Beutel', qty: 1, weight: 1, notes: '' },
      { name: 'Reisekleidung', qty: 1, weight: 4, notes: '' },
      {
        name: 'Einbrecherpaket',
        qty: 1,
        weight: 42,
        notes: 'Rucksack, Kugellager ×1000, Seil 3 m, Glocke, Kerzen ×5, Brecheisen, Hammer, Pitons ×10, Blendlaterne, Öl ×2, Rationen ×5, Zunderkästchen, Wasserschlauch, Seil 15 m',
      },
    ],
    muenzen: { gp: 24 },
    aussehen: {
      gender: 'weiblich',
      age: '26',
      size: 'Mittelgroß',
      height: '171 cm',
      weight: '59 kg',
      faith: 'abergläubisch, aber gläubig nicht',
      skin: 'aschrot',
      eyes: 'einfarbig schwarz',
      hair: 'schwarz, kurz, mit abgesägten Hörnern darüber',
    },
    wesen: {
      personality: 'Ich frage nie, wem etwas gehört. Ich frage, wer es vermissen wird.',
      ideals: 'Wiedergutmachung. Wer sich am Elend anderer bereichert hat, bezahlt bei mir Zinsen.',
      bonds: 'Meine Schwester sitzt für etwas ein, das ich getan habe. Ich hole sie da raus.',
      flaws: 'Ich kann eine offene Tür nicht sehen, ohne durchzugehen – auch wenn sie eine Falle ist.',
      backstory:
        'Zaira wuchs im Kesselviertel auf, wo Hörner an einem Kind bedeuteten, dass man ihm ohnehin alles zutraute – also lernte sie früh, ihrem Ruf zu entsprechen. Ihre Schwester Mira hielt sie da heraus, bis Zaira eines Nachts das falsche Kontor aufbrach und Mira am Morgen dafür abgeführt wurde, weil ein Zeuge zwei rote Gestalten nicht auseinanderhalten konnte. Zaira hat sich die Hörner abgesägt, den Namen behalten und arbeitet seither auf die Summe hin, die eine Berufung kostet.',
      look: 'Dunkel gekleidet, ohne dass es auffällt. Trägt Handschuhe, auch im Sommer, und sitzt nie mit dem Rücken zur Tür.',
      allies: 'Niemand offen. Zwei Hehler und ein Schreiber, der Akten verschwinden lässt.',
    },
  },

  /* --- Ork · Zauberer ------------------------------------------------------ */
  {
    schluessel: 'zauberer-ork',
    name: 'Ghorza Sturmader',
    spezies: 'Ork',
    unterart: '',
    klasse: 'Zauberer',
    hintergrund: 'Händler',
    gesinnung: 'Chaotisch Neutral',
    werte: { str: 8, dex: 14, con: 14, int: 10, wis: 12, cha: 17 },
    rettungswuerfe: ['con', 'cha'],
    fertigkeiten: ['animalHandling', 'persuasion', 'arcana', 'intimidation'],
    // Ohne Rüstung 12; mit Magierrüstung 15.
    ruestungsklasse: 12,
    initiativeBonus: 0,
    trefferpunkte: 8,
    trefferwuerfel: '1d6',
    bewegung: 30,
    sinne: { darkvision: 120 },
    verteidigung: {},
    rettungswurfVermerk: 'Fällst du auf 0 Trefferpunkte, ohne getötet zu werden, bleibst du einmal je Lange Rast bei 1 (Unbeugsame Ausdauer).',
    uebungen: {
      armor: 'keine',
      weapons: 'Einfache Waffen',
      tools: 'Navigationswerkzeug',
      languages: 'Gemeinsprache, Orkisch',
    },
    angriffe: [
      { name: 'Feuerblitz', bonus: '+5', damage: '1W10 Feuer', notes: 'Fernkampf 36 m – dein Grundangriff' },
      { name: 'Speer', bonus: '+1', damage: '1W6-1 Stich', notes: 'nur im Notfall' },
      { name: 'Magisches Geschoss', bonus: 'trifft immer', damage: '3 × (1W4+1) Energie', notes: 'Kein Wurf, keine Rettung' },
    ],
    aktionen: [
      {
        name: 'Angeborene Zauberei',
        art: 'bonus',
        description:
          'Für 1 Minute: +1 auf deinen Zauber-SG und Vorteil auf alle deine Zauberangriffe. Zweimal je Lange Rast.',
      },
      {
        name: 'Adrenalinschub',
        art: 'bonus',
        description: 'Spurten als Bonusaktion und 2 temporäre Trefferpunkte. Übungsbonus-mal je Rast.',
      },
    ],
    ressourcen: [
      { name: 'Angeborene Zauberei', current: 2, max: 2, recharge: 'lang' },
      { name: 'Adrenalinschub', current: 2, max: 2, recharge: 'kurz' },
      { name: 'Unbeugsame Ausdauer', current: 1, max: 1, recharge: 'lang' },
    ],
    merkmale: [
      {
        name: 'Angeborene Zauberei',
        category: 'klasse',
        source: 'PHB-2024',
        page: '139',
        description:
          'Als Bonusaktion für 1 Minute: Zauber-SG +1 und Vorteil auf alle Zauberangriffswürfe. Zweimal je Lange Rast.',
      },
      {
        name: 'Zauberwirken',
        category: 'klasse',
        source: 'PHB-2024',
        page: '139',
        description: 'Charisma ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5. Vier Zaubertricks, zwei Zauber bekannt.',
      },
      { name: 'Dunkelsicht', category: 'spezies', source: 'PHB-2024', page: '194', description: '36 m weit.' },
      {
        name: 'Adrenalinschub',
        category: 'spezies',
        source: 'PHB-2024',
        page: '194',
        description:
          'Spurten als Bonusaktion, dazu temporäre Trefferpunkte in Höhe deines Übungsbonus. Übungsbonus-mal, erneuert sich nach einer Rast.',
      },
      {
        name: 'Unbeugsame Ausdauer',
        category: 'spezies',
        source: 'PHB-2024',
        page: '194',
        description: 'Fällst du auf 0 Trefferpunkte, ohne getötet zu werden, bleibst du stattdessen bei 1. Einmal je Lange Rast.',
      },
      {
        name: 'Glückspilz',
        category: 'talent',
        source: 'PHB-2024',
        page: '202',
        description: 'Übungsbonus-viele Glückspunkte je Lange Rast: Vorteil auf einen eigenen W20 oder Nachteil auf einen Angriff gegen dich.',
      },
    ],
    zauber: {
      attribut: 'cha',
      plaetze: { 1: { max: 2, used: 0 } },
      liste: [
        {
          name: 'Feuerblitz',
          level: 0,
          prepared: true,
          index: 'fire-bolt',
          source: 'Zauberer',
          save: '--',
          time: '1 A',
          range: '36 m',
          components: 'V, S',
          duration: 'Sofort',
          page: 'PHB-2024 264',
          notes: 'Dein Grundangriff. 1W10 Feuer, entzündet brennbare Gegenstände.',
        },
        {
          name: 'Licht',
          level: 0,
          prepared: true,
          index: 'light',
          source: 'Zauberer',
          save: '--',
          time: '1 A',
          range: 'Berührung',
          components: 'V, M',
          duration: '1 Std.',
          page: 'PHB-2024 275',
          notes: '',
        },
        {
          name: 'Kleine Illusion',
          level: 0,
          prepared: true,
          index: 'minor-illusion',
          source: 'Zauberer',
          save: '--',
          time: '1 A',
          range: '9 m',
          components: 'S, M',
          duration: '1 Min.',
          page: 'PHB-2024 280',
          notes: '',
        },
        {
          name: 'Blendwerk',
          level: 0,
          prepared: true,
          index: 'prestidigitation',
          source: 'Zauberer',
          save: '--',
          time: '1 A',
          range: '3 m',
          components: 'V, S',
          duration: 'bis 1 Std.',
          page: 'PHB-2024 289',
          notes: '',
        },
        {
          name: 'Magierrüstung',
          level: 1,
          prepared: true,
          index: 'mage-armor',
          source: 'Zauberer',
          save: '--',
          time: '1 A',
          range: 'Berührung',
          components: 'V, S, M',
          duration: '8 Std.',
          page: 'PHB-2024 278',
          notes: 'Morgens auf dich selbst: RK 15 statt 12, den ganzen Tag.',
        },
        {
          name: 'Magisches Geschoss',
          level: 1,
          prepared: true,
          index: 'magic-missile',
          source: 'Zauberer',
          save: '--',
          time: '1 A',
          range: '36 m',
          components: 'V, S',
          duration: 'Sofort',
          page: 'PHB-2024 278',
          notes: 'Trifft ohne Wurf – der sichere Schaden, wenn es knapp wird.',
        },
      ],
    },
    ausruestung: [
      { name: 'Speer', qty: 1, weight: 3, notes: '' },
      { name: 'Dolch', qty: 2, weight: 1, notes: '' },
      { name: 'Arkaner Fokus (Kristall)', qty: 1, weight: 1, notes: 'ein Stück Blitzglas aus der Steppe' },
      { name: 'Navigationswerkzeug', qty: 1, weight: 2, notes: '' },
      { name: 'Beutel', qty: 2, weight: 1, notes: '' },
      { name: 'Reisekleidung', qty: 1, weight: 4, notes: '' },
      {
        name: 'Höhlenforscherpaket',
        qty: 1,
        weight: 55,
        notes: 'Rucksack, Brecheisen, Hammer, Pitons ×10, Fackeln ×10, Zunderkästchen, Rationen ×10, Wasserschlauch, Seil 15 m',
      },
    ],
    muenzen: { gp: 50 },
    aussehen: {
      gender: 'weiblich',
      age: '24',
      size: 'Mittelgroß',
      height: '188 cm',
      weight: '94 kg',
      faith: 'keiner, aber sie dankt dem Sturm',
      skin: 'graugrün',
      eyes: 'gelb',
      hair: 'schwarz, an den Seiten geschoren',
    },
    wesen: {
      personality: 'Ich handle über alles, auch wenn ich es gar nicht will. Feilschen beruhigt mich.',
      ideals: 'Vertrag. Ein Handschlag gilt, sonst funktioniert nichts davon.',
      bonds: 'Der Karren meiner Mutter, mit dem sie dreißig Jahre über die Steppe fuhr. Er steht noch bei mir.',
      flaws: 'Wenn die Magie in mir hochkommt, tue ich Dinge, für die ich mich hinterher entschuldigen muss.',
      backstory:
        'Ghorza wuchs auf einem Handelskarren auf und lernte rechnen, bevor sie sprechen konnte. Mit neunzehn schlug ein Blitz in den Karren, tötete das Zugtier und ließ sie unversehrt zurück – mit etwas im Blut, das seither knistert, wenn sie sich aufregt. Ihre Mutter starb ein Jahr später, und Ghorza fährt weiter, verkauft, was sie findet, und sucht nach jemandem, der ihr erklären kann, was der Blitz in ihr gelassen hat.',
      look: 'Groß, breit, mit einem Lächeln, das gleichzeitig freundlich und geschäftlich ist. Bei Aufregung stehen ihr die Haare buchstäblich ab.',
      allies: 'Die Steppenhändler vom Langen Weg, die ihren Namen kennen und ihr Kredit geben.',
    },
  },

  /* --- Halbork · Hexenmeister ---------------------------------------------- */
  {
    schluessel: 'hexenmeister-halbork',
    name: 'Mek Halbmond',
    spezies: 'Halbork',
    unterart: '',
    klasse: 'Hexenmeister',
    hintergrund: 'Scharlatan',
    gesinnung: 'Neutral',
    werte: { str: 8, dex: 14, con: 14, int: 10, wis: 12, cha: 17 },
    rettungswuerfe: ['wis', 'cha'],
    fertigkeiten: ['deception', 'sleightOfHand', 'arcana', 'intimidation'],
    ruestungsklasse: 13,
    initiativeBonus: 0,
    trefferpunkte: 10,
    trefferwuerfel: '1d8',
    bewegung: 30,
    sinne: { darkvision: 60 },
    verteidigung: {},
    rettungswurfVermerk: 'Fällst du auf 0 Trefferpunkte, ohne getötet zu werden, bleibst du einmal je Lange Rast bei 1 (Unbeugsame Ausdauer).',
    uebungen: {
      armor: 'Leichte Rüstung',
      weapons: 'Einfache Waffen',
      tools: 'Fälscherausrüstung',
      languages: 'Gemeinsprache, Orkisch, Abyssisch',
    },
    angriffe: [
      { name: 'Schauerlicher Strahl', bonus: '+5', damage: '1W10+3 Energie', notes: 'Fernkampf 36 m, Zermalmender Strahl' },
      { name: 'Sichel', bonus: '+4', damage: '1W4+2 Hieb', notes: 'Leicht' },
      { name: 'Dolch', bonus: '+4', damage: '1W4+2 Stich', notes: 'Finesse, Wurf 6/18 m' },
    ],
    aktionen: [
      {
        name: 'Fluch (Konzentration)',
        art: 'bonus',
        description: '+1W6 Energieschaden bei jedem deiner Treffer gegen das Ziel, dazu Nachteil auf Proben eines Attributs deiner Wahl.',
      },
      {
        name: 'Rüstung des Agathys',
        art: 'aktion',
        description: '5 temporäre Trefferpunkte, und wer dich im Nahkampf trifft, nimmt 5 Kälteschaden.',
      },
    ],
    ressourcen: [
      { name: 'Pakt-Zauberplatz (Grad 1)', current: 1, max: 1, recharge: 'kurz' },
      { name: 'Unbeugsame Ausdauer', current: 1, max: 1, recharge: 'lang' },
    ],
    merkmale: [
      {
        name: 'Paktmagie',
        category: 'klasse',
        source: 'PHB-2024',
        page: '154',
        description:
          'Ein Zauberplatz vom 1. Grad, der sich schon nach einer Kurzen Rast erneuert. Deshalb lohnt es sich, ihn früh auszugeben.',
      },
      {
        name: 'Schauerliche Anrufung: Zermalmender Strahl',
        category: 'klasse',
        source: 'PHB-2024',
        page: '155',
        description: 'Du addierst deinen Charisma-Modifikator auf den Schaden jedes Strahls des Schauerlichen Strahls.',
      },
      {
        name: 'Jenseitiger Fürsprecher',
        category: 'klasse',
        source: 'PHB-2024',
        page: '154',
        description: 'Charisma ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5.',
      },
      { name: 'Dunkelsicht', category: 'spezies', source: 'PHB', page: '', description: '18 m weit.' },
      {
        name: 'Unbeugsame Ausdauer',
        category: 'spezies',
        source: 'PHB',
        page: '',
        description: 'Fällst du auf 0 Trefferpunkte, ohne getötet zu werden, bleibst du stattdessen bei 1. Einmal je Lange Rast.',
      },
      {
        name: 'Wilde Angriffe',
        category: 'spezies',
        source: 'PHB',
        page: '',
        description: 'Bei einem kritischen Treffer mit einer Waffe würfelst du einen zusätzlichen Schadenswürfel.',
      },
      {
        name: 'Bedrohlich',
        category: 'spezies',
        source: 'PHB',
        page: '',
        description: 'Übung in Einschüchtern.',
      },
      {
        name: 'Geübt',
        category: 'talent',
        source: 'PHB-2024',
        page: '207',
        description: 'Übung in drei weiteren Fertigkeiten oder Werkzeugen – hier Arkane Kunde, Fingerfertigkeit und die Fälscherausrüstung.',
      },
    ],
    zauber: {
      attribut: 'cha',
      plaetze: { 1: { max: 1, used: 0 } },
      liste: [
        {
          name: 'Schauerlicher Strahl',
          level: 0,
          prepared: true,
          index: 'eldritch-blast',
          source: 'Hexenmeister',
          save: '--',
          time: '1 A',
          range: '36 m',
          components: 'V, S',
          duration: 'Sofort',
          page: 'PHB-2024 261',
          notes: 'Mit Zermalmendem Strahl 1W10+3. Der beste Grundangriff, den Stufe 1 zu bieten hat.',
        },
        {
          name: 'Kleine Illusion',
          level: 0,
          prepared: true,
          index: 'minor-illusion',
          source: 'Hexenmeister',
          save: '--',
          time: '1 A',
          range: '9 m',
          components: 'S, M',
          duration: '1 Min.',
          page: 'PHB-2024 280',
          notes: 'Das Handwerkszeug eines Scharlatans.',
        },
        {
          name: 'Fluch',
          level: 1,
          prepared: true,
          index: 'hex',
          source: 'Hexenmeister',
          save: '--',
          time: '1 BA',
          range: '27 m',
          components: 'V, S, M',
          duration: 'K, 1 Std.',
          page: 'PHB-2024 271',
          notes: 'Erste Bonusaktion des Kampfes: +1W6 auf jeden Strahl.',
        },
        {
          name: 'Rüstung des Agathys',
          level: 1,
          prepared: true,
          index: 'armor-of-agathys',
          source: 'Hexenmeister',
          save: '--',
          time: '1 A',
          range: 'Selbst',
          components: 'V, S, M',
          duration: '1 Std.',
          page: 'PHB-2024 245',
          notes: '5 temporäre TP, und wer dich im Nahkampf trifft, bekommt 5 Kälteschaden zurück.',
        },
      ],
    },
    ausruestung: [
      { name: 'Lederrüstung', qty: 1, weight: 10, notes: 'RK 11 + Geschicklichkeit' },
      { name: 'Sichel', qty: 1, weight: 2, notes: '' },
      { name: 'Dolch', qty: 2, weight: 1, notes: '' },
      { name: 'Arkaner Fokus (Kugel)', qty: 1, weight: 3, notes: 'trüb, und nachts wärmer als die Luft' },
      { name: 'Buch okkulter Überlieferungen', qty: 1, weight: 5, notes: 'zur Hälfte in fremder Handschrift' },
      { name: 'Fälscherausrüstung', qty: 1, weight: 5, notes: '' },
      { name: 'Kostüm', qty: 1, weight: 4, notes: '' },
      { name: 'Feine Kleidung', qty: 1, weight: 6, notes: 'für Auftritte als jemand anderes' },
      {
        name: 'Gelehrtenpaket',
        qty: 1,
        weight: 40,
        notes: 'Rucksack, Buch, Tinte, Federkiel, Pergament ×10, Beutel Sand, Federmesser',
      },
    ],
    muenzen: { gp: 30 },
    aussehen: {
      gender: 'männlich',
      age: '31',
      size: 'Mittelgroß',
      height: '191 cm',
      weight: '101 kg',
      faith: 'er nennt keinen Namen',
      skin: 'olivgrün, an den Wangen heller',
      eyes: 'braun, das rechte seit dem Pakt milchig',
      hair: 'dunkel, zurückgebunden',
    },
    wesen: {
      personality: 'Ich rede mich aus allem heraus, und wenn nicht, rede ich weiter, bis es klappt.',
      ideals: 'Selbstbestimmung. Ich habe unterschrieben, also gehört mir wenigstens die Entscheidung.',
      bonds: 'Das Dorf Halbmond hätte den Winter nicht überstanden. Deshalb steht mein Name in diesem Buch.',
      flaws: 'Ich lüge auch dann, wenn die Wahrheit mir mehr nützen würde. Übung schlägt Verstand.',
      backstory:
        'Als der Winter über Halbmond kam und die Vorräte verbrannt waren, ging Mek in die Ruine, von der alle abrieten, und kam mit Korn zurück – und mit etwas, das seither in seinem rechten Auge sitzt. Das Dorf überstand den Winter und warf ihn im Frühjahr hinaus, weil man das eine dem anderen vorzog. Er zieht seitdem als Wahrsager, Heiler und was sonst gefragt ist von Ort zu Ort, sammelt Bücher über Pakte und sucht nach der Klausel, die er damals überlesen hat.',
      look: 'Wirkt teurer gekleidet, als er ist. Lächelt viel, und das rechte Auge lächelt nicht mit.',
      allies: 'Das Dorf Halbmond, das ihn nicht zurückhaben will, ihm aber jedes Jahr ein Fass schickt.',
    },
  },

  /* --- Mensch · Magier ----------------------------------------------------- */
  {
    schluessel: 'magier-mensch',
    name: 'Aldric Fenn',
    spezies: 'Mensch',
    unterart: '',
    klasse: 'Magier',
    hintergrund: 'Gelehrter',
    gesinnung: 'Neutral Gut',
    werte: { str: 8, dex: 14, con: 14, int: 17, wis: 12, cha: 10 },
    rettungswuerfe: ['int', 'wis'],
    fertigkeiten: ['arcana', 'history', 'investigation', 'insight', 'perception'],
    // Ohne Rüstung 12; mit Magierrüstung 15.
    ruestungsklasse: 12,
    // Wachsam legt den Übungsbonus auf die Initiative.
    initiativeBonus: 2,
    trefferpunkte: 8,
    trefferwuerfel: '1d6',
    bewegung: 30,
    sinne: {},
    verteidigung: {},
    rettungswurfVermerk: '',
    uebungen: {
      armor: 'keine',
      weapons: 'Einfache Waffen',
      tools: 'Kalligraphenbedarf',
      languages: 'Gemeinsprache, Draconisch, Zwergisch, Elfisch',
    },
    angriffe: [
      { name: 'Feuerblitz', bonus: '+5', damage: '1W10 Feuer', notes: 'Fernkampf 36 m – dein Grundangriff' },
      { name: 'Magisches Geschoss', bonus: 'trifft immer', damage: '3 × (1W4+1) Energie', notes: 'Kein Wurf, keine Rettung' },
      { name: 'Dolch', bonus: '+4', damage: '1W4+2 Stich', notes: 'Finesse, Wurf 6/18 m' },
    ],
    aktionen: [
      {
        name: 'Schild',
        art: 'reaktion',
        description: 'Wenn dich ein Angriff trifft: +5 RK bis zum Beginn deines nächsten Zuges. Wehrt Magisches Geschoss ganz ab.',
      },
      {
        name: 'Schlaf',
        art: 'aktion',
        description: '5W8 Trefferpunkte an Geschöpfen in einer 6-m-Kugel schlafen ein, von den schwächsten aufwärts. Beendet ganze Kämpfe.',
      },
      {
        name: 'Ritual: Magie entdecken',
        art: 'frei',
        description: 'Als Ritual gewirkt kostet es keinen Zauberplatz, nur zehn Minuten mehr.',
      },
    ],
    ressourcen: [{ name: 'Heldenhafte Inspiration', current: 1, max: 1, recharge: 'lang' }],
    merkmale: [
      {
        name: 'Zauberwirken',
        category: 'klasse',
        source: 'PHB-2024',
        page: '162',
        description:
          'Intelligenz ist dein Zauberattribut. Zauber-SG 13, Zauberangriffsbonus +5. Vier Zauber aus dem Buch vorbereitet.',
      },
      {
        name: 'Ritualwirken',
        category: 'klasse',
        source: 'PHB-2024',
        page: '162',
        description: 'Zauber mit dem Vermerk Ritual kannst du aus dem Buch wirken, ohne einen Platz auszugeben.',
      },
      {
        name: 'Arkane Erholung',
        category: 'klasse',
        source: 'PHB-2024',
        page: '162',
        description: 'Nach einer Kurzen Rast einmal am Tag einen Zauberplatz vom 1. Grad zurückgewinnen.',
      },
      {
        name: 'Findig',
        category: 'spezies',
        source: 'PHB-2024',
        page: '194',
        description: 'Nach jeder Langen Rast erhältst du Heldenhafte Inspiration.',
      },
      {
        name: 'Geschickt',
        category: 'spezies',
        source: 'PHB-2024',
        page: '194',
        description: 'Übung in einer weiteren Fertigkeit – hier Wahrnehmung.',
      },
      {
        name: 'Vielseitig',
        category: 'spezies',
        source: 'PHB-2024',
        page: '194',
        description: 'Ein zusätzliches Ursprungstalent – hier Wachsam.',
      },
      {
        name: 'Wachsam',
        category: 'talent',
        source: 'PHB-2024',
        page: '200',
        description: 'Übungsbonus auf die Initiative, und du darfst sie mit einem einverstandenen Verbündeten tauschen.',
      },
      {
        name: 'Magiekundig (Magier)',
        category: 'hintergrund',
        source: 'PHB-2024',
        page: '202',
        description: 'Zwei Zaubertricks und ein Zauber vom 1. Grad aus der Magierliste, einmal je Lange Rast ohne Platz.',
      },
    ],
    zauber: {
      attribut: 'int',
      plaetze: { 1: { max: 2, used: 0 } },
      liste: [
        {
          name: 'Feuerblitz',
          level: 0,
          prepared: true,
          index: 'fire-bolt',
          source: 'Magier',
          save: '--',
          time: '1 A',
          range: '36 m',
          components: 'V, S',
          duration: 'Sofort',
          page: 'PHB-2024 264',
          notes: 'Dein Grundangriff, solange Plätze knapp sind.',
        },
        {
          name: 'Magierhand',
          level: 0,
          prepared: true,
          index: 'mage-hand',
          source: 'Magier',
          save: '--',
          time: '1 A',
          range: '9 m',
          components: 'V, S',
          duration: '1 Min.',
          page: 'PHB-2024 278',
          notes: 'Hebel ziehen, Fallen auslösen, Dinge holen – aus sicherer Entfernung.',
        },
        {
          name: 'Blendwerk',
          level: 0,
          prepared: true,
          index: 'prestidigitation',
          source: 'Magier',
          save: '--',
          time: '1 A',
          range: '3 m',
          components: 'V, S',
          duration: 'bis 1 Std.',
          page: 'PHB-2024 289',
          notes: '',
        },
        {
          name: 'Magisches Geschoss',
          level: 1,
          prepared: true,
          index: 'magic-missile',
          source: 'Zauberbuch',
          save: '--',
          time: '1 A',
          range: '36 m',
          components: 'V, S',
          duration: 'Sofort',
          page: 'PHB-2024 278',
          notes: 'Trifft ohne Wurf. Der sichere Schaden.',
        },
        {
          name: 'Schild',
          level: 1,
          prepared: true,
          index: 'shield',
          source: 'Zauberbuch',
          save: '--',
          time: '1 R',
          range: 'Selbst',
          components: 'V, S',
          duration: '1 Runde',
          page: 'PHB-2024 296',
          notes: 'Reaktion: +5 RK. Der Grund, warum du mit RK 12 überlebst.',
        },
        {
          name: 'Schlaf',
          level: 1,
          prepared: true,
          index: 'sleep',
          source: 'Zauberbuch',
          save: '--',
          time: '1 A',
          range: '27 m',
          components: 'V, S, M',
          duration: 'K, 1 Min.',
          page: 'PHB-2024 298',
          notes: 'Der stärkste Zauber vom 1. Grad auf niedrigen Stufen.',
        },
        {
          name: 'Magierrüstung',
          level: 1,
          prepared: false,
          index: 'mage-armor',
          source: 'Zauberbuch',
          save: '--',
          time: '1 A',
          range: 'Berührung',
          components: 'V, S, M',
          duration: '8 Std.',
          page: 'PHB-2024 278',
          notes: 'Im Buch. Morgens vorbereiten, dann RK 15 für den ganzen Tag.',
        },
        {
          name: 'Magie entdecken',
          level: 1,
          prepared: false,
          index: 'detect-magic',
          source: 'Zauberbuch',
          save: '--',
          time: '1 A',
          range: 'Selbst (9 m)',
          components: 'V, S',
          duration: 'K, 10 Min.',
          page: 'PHB-2024 258',
          notes: 'Ritual – kostet als solches keinen Platz.',
        },
        {
          name: 'Schmierfett',
          level: 1,
          prepared: false,
          index: 'grease',
          source: 'Zauberbuch',
          save: 'GES-RW',
          time: '1 A',
          range: '18 m',
          components: 'V, S, M',
          duration: '1 Min.',
          page: 'PHB-2024 267',
          notes: 'Im Buch. 3-m-Quadrat schwieriges Gelände, wer nicht besteht, wird liegend.',
        },
      ],
    },
    ausruestung: [
      { name: 'Dolch', qty: 2, weight: 1, notes: '' },
      { name: 'Kampfstab', qty: 1, weight: 4, notes: 'Arkaner Fokus' },
      { name: 'Robe', qty: 1, weight: 4, notes: '' },
      { name: 'Zauberbuch', qty: 1, weight: 3, notes: 'sechs Zauber vom 1. Grad' },
      { name: 'Kalligraphenbedarf', qty: 1, weight: 5, notes: '' },
      { name: 'Buch über die Belagerung von Fenn', qty: 1, weight: 5, notes: 'sein eigenes, unvollendet' },
      { name: 'Pergament', qty: 8, weight: 0, notes: '' },
      {
        name: 'Gelehrtenpaket',
        qty: 1,
        weight: 40,
        notes: 'Rucksack, Buch, Tinte, Federkiel, Pergament ×10, Beutel Sand, Federmesser',
      },
    ],
    muenzen: { gp: 13 },
    aussehen: {
      gender: 'männlich',
      age: '41',
      size: 'Mittelgroß',
      height: '177 cm',
      weight: '70 kg',
      faith: 'die Archive',
      skin: 'blass, wenig draußen gewesen',
      eyes: 'grau',
      hair: 'dunkelbraun, an den Schläfen ergraut',
    },
    wesen: {
      personality: 'Ich schreibe mit, während andere reden. Nicht aus Misstrauen – ich vergesse sonst.',
      ideals: 'Wahrheit. Eine Quelle, die nicht geprüft ist, ist ein Gerücht mit Fußnote.',
      bonds: 'Die Bibliothek von Fenn brannte, und ich rettete elf Bände. Ich weiß bis heute, welche zwölf ich liegen ließ.',
      flaws: 'Ich halte einen Streit für gewonnen, sobald ich recht habe – und merke zu spät, dass das nicht dasselbe ist.',
      backstory:
        'Aldric verbrachte zwanzig Jahre im Archiv seiner Heimatstadt und hätte dort auch die nächsten zwanzig verbracht, hätte in der Nacht der Belagerung nicht das Dach gebrannt. Er trug hinaus, was er tragen konnte, und schrieb später auf, was in den verlorenen Bänden gestanden hatte – aus dem Gedächtnis, mit einer Sorgfalt, die ihn selbst quält. Um die Lücken zu füllen, muss er nun an die Orte, über die er bisher nur gelesen hat.',
      look: 'Schmal, immer ein wenig zerstreut wirkend, mit Tinte an den Fingern und einem Blick, der Räume liest wie Seiten.',
      allies: 'Die Archivarsgilde von Fenn, die ihm Ausleihen gewährt, die sonst niemand bekommt.',
    },
  },
];
